### ISSUE TITLE
How to use "Try To Fix!"

### ISSUE THREAD

**Issue by DessaiImrane** [shinken-monitoring/mod-webui#104]
Hi,

Maybe I missed something in the doc, but how this button works and how can we configure it ?

Can we use it to refer to an External Link (for instance to our internal Knowledge Database) ?

**Comment by ThomasBarach** [comment]
Hi,

Did you figure this out ?

Regards

**Comment by naparuba** [comment]
It try to launch the event_handler in fact :)

**Comment by mohierf** [comment]
I close because a valid answer has been published.
