### ISSUE TITLE
How to figure out  the timezone of the webUI use for scheduled downtime

### ISSUE THREAD

**Issue by andyxning** [shinken-monitoring/mod-webui#105]
I have set the timezone to "Asia/Shanghai", however it comes out that the timezone for the scheduled downtime of webui does not take it. And, appears less that the specified timezone with 8 hours, which come to a hint that webui used UTC time.

Is there any method to configure the timezone of webUI?

**Comment by mohierf** [comment]
Closing ... future release fixes.
