### ISSUE TITLE
Port number 7767 hardcoded

### ISSUE THREAD

**Issue by Dual-Boot** [shinken-monitoring/mod-webui#107]
Hello,

I test webui and I notice that when I click on Shinken -> Shinken UI , I am redirected to myserver.mydomain.tld:7767 .
But I use an apache 2.4 proxy in front of Shinken, so it redirected me to myserver.mydomain.tld:7767 which should be (I suppose) myserver.mydomain.tld .
All proxy redirections are good except this one.
I grep 7767 into /var/lib/shinken/modules/webui/ and I found these references : 
```
shinken@srv-mon01:/etc/shinken$ grep -R 7767 /var/lib/shinken/modules/webui/*
/var/lib/shinken/modules/webui/htdocs/js/shinkenui.js:    var Port = 7767;
/var/lib/shinken/modules/webui/htdocs/js/shinkenui.js:    $("a[href=':7767']").attr('href', webui());
/var/lib/shinken/modules/webui/module.py:        self.port = int(getattr(modconf, 'port', '7767'))
Fichier binaire /var/lib/shinken/modules/webui/module.pyc correspondant
/var/lib/shinken/modules/webui/views/header_element_skonf.tpl:            <li><a href=":7767">Shinken UI </a></li>
/var/lib/shinken/modules/webui/views/header_element.tpl:      $("a[href=':7767']").attr('href', webui());
/var/lib/shinken/modules/webui/views/header_element.tpl:            <li><a href=":7767">Shinken UI </a></li>
shinken@srv-mon01:/etc/shinken$
```
  How to fix this issue.

 Thanks you, regards,

PS: shinken 2.0.3 with webui installed by ```shinken install webui```

**Comment by mohierf** [comment]
Closing ... future release fixes.
