### ISSUE TITLE
Group downtimes

### ISSUE THREAD

**Issue by maximebrun** [shinken-monitoring/mod-webui#111]
Hello,

It is sometime useful to add a downtime on multiple hosts/services.
I found nothing in the issues about that. I'm not sure how to do that with webui evolution so i didn't propose a pull request.

I added downtime action in problem plugin, so it is possible to plan a downtime for a selection.

Do you have a roadmap or something like that for webui next ?

**Comment by Frescha** [comment]
Hi, sounds interesting. If you have interest to improve the WebUI with us, feel free and send a pull request. 

https://github.com/shinken-monitoring/mod-webui#contributing
https://github.com/shinken-monitoring/mod-webui/blob/master/roadmap.md

**Comment by mohierf** [comment]
In BS3 branch, I added a *Schedule downtime* action in the problems view. You may be able to select all hosts from an hostgroup and then apply Schedule downtime action on all the hosts of the group. The downtime is scheduled for one day ...

**Comment by mohierf** [comment]
Closing ... @maximebrun comment if you are still interested.
