### ISSUE TITLE
[2.2RC1]Fix import from plugins for shinken 2.2

### ISSUE THREAD

**Issue by david-guenault** [shinken-monitoring/mod-webui#112]
There were changes in the way module are imported in shinken. This make nearly every webui branch unusable bescause of import problem. 

One exemple : 
in wall.py from helper import .... does not work anymore (not in the global namespace) you must use from webui.helper import .... 

There are a lot of other examples

**Comment by mohierf** [comment]
Seems ok on all modules now ? At least on bs3 branch ...

**Comment by mohierf** [comment]
Closing ... future release fixes.
