### ISSUE TITLE
Error 500 on mobile view

### ISSUE THREAD

**Issue by tchene** [shinken-monitoring/mod-webui#114]
Hi, I have some problem with the mobile interface. The server return an error 500 with this comment : 

"Sorry, the requested URL 'http://192.168.1.33:7767/mobile/main' caused an error:

Template u'header_element_mobile' not found."

I don't know what is a template for webui. I try to search the words "element", "template" or "header_element" in my files, but I have no result. 

Anyone know what am I doing for fix it?

**Comment by Frescha** [comment]
WebUI Version and branch?
If you use the current version, there is no working mobile interface anymore. sorry

**Comment by tchene** [comment]
I use the current version of the master branch, so it's ok. But do you know how can I download an usable mobile ui?

**Comment by mohierf** [comment]
Mobile view is to be removed ... Bootstrap takes care natively for mobile devices
