### ISSUE TITLE
Not found /config & /profile

### ISSUE THREAD

**Issue by arthurlogilab** [shinken-monitoring/mod-webui#118]
On debian jessie install I get ```Not found: '/config'``` on ```http:/IP:7767/config``` (same goes for /profile)

ii  shinken                           2.0.3-4

**Comment by mohierf** [comment]
? Should you explain a little more about why/how you requested on  */config* or */profile*

**Comment by arthurlogilab** [comment]
Click on the menu at the top left, click on the button "configuration" or button "profile" 
![untitled](https://cloud.githubusercontent.com/assets/445200/7177995/926e7412-e42b-11e4-81a0-fc2ec6fa9d8b.jpg)

**Comment by mohierf** [comment]
Ok, I suppose it is some remainings of the initial mock-up @Frescha ?

**Comment by mohierf** [comment]
No more necessary with recent BS3 developments ...

**Comment by Cyrille37** [comment]
Hi,
But debian jessie still the current version (march 2017) and still got those dead menu entries.
Cheers.

**Comment by mohierf** [comment]
@Cyrille37 : be sure to follow the steps described here to setup :https://github.com/shinken-monitoring/mod-webui/wiki
