### ISSUE TITLE
Shinken IO plugin

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#119]
A seamless integration for the Shinken IO daemons view should be interesting ? I made a test with an iframe ... but it should be interesting to bypass the user login : @naparuba ?

![image](https://cloud.githubusercontent.com/assets/2932687/7016801/733723aa-dcec-11e4-99d6-61361bf5275c.png)

![image](https://cloud.githubusercontent.com/assets/2932687/7016793/374761f2-dcec-11e4-94d1-0ab8982641ce.png)

**Comment by naparuba** [comment]
Why not, but we just need a way to authentificate with http like with the
key+secret, but so they will appears in a webui user. I don't see any other
way than this currently. any idea?

**Comment by mohierf** [comment]
The idea should be to allow only admin users to have this view ... and so, the admin user should have key + secret parameters in his configuration.

 Let us say I have these parameters, how should I authenticate : any web service on your server ?

**Comment by naparuba** [comment]
only user+pass or api+secret. Last one is only for push, first is for UI
login. but then set cookie so only need one login after all.

**Comment by naparuba** [comment]
but as we can add new admin feature there, isn't it dangerous to allow all
webui user to see these part? after all all user don't need to see the
daemons state/names. such view should be restricted to shinken admins at
minimum i think :)

**Comment by mohierf** [comment]
Yes, you are right ... this view should be restricted to admin users !

I can make a test for this. which Web Service should I call to log in kernel.shinken.io ?

**Comment by naparuba** [comment]
POST http://shinken.io/login

name <== the shinken.io username
password <=== I think you know what is it ^^


It will answer with a json object:
{"status": 200, "text": "OK", "api_key": "BLABLALBA", "email":
"THEUSEREMAIL"}

and will set a cookie that is userd after to retrive/auth the user for
other calls.


^^

**Comment by mohierf** [comment]
It would be better to allow connection to this WS with an UI login ... but not that easy to implement ... the user is not a Shinken modules project contributor :/P

**Comment by mohierf** [comment]
Available but no included in default configuraton ... too much specific! Sorry @naparuba ...
