### ISSUE TITLE
[branch bs3] Method get_services_tagged_with doesn't exist in shinken.misc.Datamanager

### ISSUE THREAD

**Issue by t0xicCode** [shinken-monitoring/mod-webui#124]
The `get_services_tagged_with` method is called on the [Datamanager](https://github.com/naparuba/shinken/blob/master/shinken/misc/datamanager.py) in many places (mainly in the [tags plugin](https://github.com/shinken-monitoring/mod-webui/blob/bs3/module/plugins/tags/tags.py)). That method should either be added to the shinken Datamanager, or removed from webui.

**Comment by mohierf** [comment]
You are right ... those methods have never been added to DataManager class because they are only used in WebUI ... I just added with some other in module.py of WebUI. It may be ok now ...

**Comment by t0xicCode** [comment]
Still getting the error. The methods need to be added to the Datamanager class in shinken proper (the better option) or the calls in the webui need to be changed to remove the `datamgr` part.

**Comment by mohierf** [comment]
I just commited a bunch of modifications in BS3 branch to manage those functions ... I added a lot of functions initially located in datamanager as a stub in module.py ... the idea is to isolate the WebUI from Shinken core modifications.

 I tested in my env that the services tag are well managed ! 

 Please give it a try ...
