### ISSUE TITLE
Downtime Can trigger in log, but Not showing in webui

### ISSUE THREAD

**Issue by tarak666** [shinken-monitoring/mod-webui#127]
Hi,

We have shinken2.2 installed using pip, everything working fine for me but only downtime is not working.
When i add downtime it showing in log, but not showing  on webui or commant box.

Shinken Version:- shinken 2.2
Log in shinken.log
=======
 EXTERNAL COMMAND: [142912347187] SCHEDULE_SVC_DOWNTIME;localhost;Check Memory Usage;142345340;142345540;1;0;0;tarak;sdsad

Can any one help me to fix this issue

Thanks in advance.

**Comment by maethor** [comment]
I know it may not be the answer you expected, but we are working hard on the `bs3` branch. You should try it, I think this bug is fixed in this branch.

**Comment by mohierf** [comment]
Yes, this bug is fixed. I made some tests yesterday with ack and downtimes and all are displayed correctly.
