### ISSUE TITLE
How to develop a custom view for a plugin in webui

### ISSUE THREAD

**Issue by Peter-YAN** [shinken-monitoring/mod-webui#131]
Hi, could you give some guide about developing view for a plugin?
I need to write a brand new plugin, i hope to config it using page1 and show it result in page2.
Please guide me to develop page1 and page2, and how to add this pages into webui?

**Comment by Peter-YAN** [comment]
Please also list the technologies about developing webui?
I am a new to developing web page, i have some knowledge about python.
Thanks.

**Comment by mohierf** [comment]
For custom views you should have a look in the bs3 branch in ```plugins/cv_*``` directories. Each of these directories is a custom view and you will find useful information in the source code ...

 If you are not easy with the technologies used in the WebUI it will be quite hard to you to manage this easily : python, bottle templates, html, javascript and, finally, HTML5 canvas ...

 In a few words, you should copy one of the existing views and then modify to build a new one in a new cv_xxx directory. Then you add the custom_views property on the concerned hosts and the WebUI creates as much tab as you have view names in this property ...

 Hope this may help ... feel free to ask for more ... with samples, it will be easier to help :-)

**Comment by mohierf** [comment]
I suppose my previous comment is ok, so I close .
