### ISSUE TITLE
How to develop a email notification with a html attachment

### ISSUE THREAD

**Issue by Peter-YAN** [shinken-monitoring/mod-webui#132]
Hi,
Could i use shinken to send a email notification, and the email should be a custom format, such as highlight text, use table form; attachment is also want to used in the email.

I found zabbix could run external script to meet this requirement.
But I do not find it in Shinken,

**Comment by Peter-YAN** [comment]
I found zabbix could run external script to meet this requirement.
But I do not find it in Shinken,

**Comment by mohierf** [comment]
The Shinken WebUI is not concerned by this feature ... to send an email notification you should configure the host/service/contact notifications attributes in your Shinken hosts/services/contacts configuration file.
