### ISSUE TITLE
globally disabled notification can not be reflected in WebUI

### ISSUE THREAD

**Issue by andyxning** [shinken-monitoring/mod-webui#135]
currently, WebUI displays service or host Notifications with `elt.notifications_enabled` variable, however, if we use the 'DISABLE_NOTIFICATIONS' external commands we only change the value of `enabled_notifications` of the conf which is then inherited by service, host  and contact. Thus notification is disabled globally.

So, if we issued an `DISABLE_NOTIFICATIONS` external command then the **Notifications** status of host and service in WebUI will not be changed. 

So, i think we can add one more variable check in  [eltdetail.tpl](https://github.com/shinken-monitoring/mod-webui/blob/master/module/plugins/eltdetail/views/eltdetail.tpl#L284) with below:
```
%if not (elt.notifications_enabled and elt.enabled_notifications):
```
for more info please take a look at [this](https://github.com/naparuba/shinken/blob/master/shinken/objects/service.py#L1126)

**Comment by maethor** [comment]
I also see a bug when there is no notification_period. I think we can generalize to this:

```
%if elt.notifications_enabled and elt.notification_period:
```

I have a PR coming with this modification.

**Comment by mohierf** [comment]
+1

**Comment by andyxning** [comment]
@maethor , i think you should take `elt.enabled_notifications` into the test clause. And, can you please explain what does the "a bug when there is no notification_period" mean and under which circumstance we can see this bug? :)

**Comment by andyxning** [comment]
@mohierf , can you please take a look at this issue. I have see what is in  @maethor RP, i think it is based on your bs-3 branch.

**Comment by mohierf** [comment]
Should be an interesting feature to be able to view global configuration in WebUI ...

**Comment by mohierf** [comment]
Opened #230 for this feature
