### ISSUE TITLE
BS3 improvements - ideas are welcome ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#136]
**Note:** I open this issue to track ideas for improving Shinken BS3 WebUI ... please feel free to drop your ideas in this check-list ...

Improvements : 
- [ ] open a global Shinken parameters page
- [ ] allow to schedule a downtime for a contact

Look and feel : 
- [x] real bootstrap theme / skinnable interface

**Comment by maethor** [comment]
Hello,

I'm just beggining to use the BS3 branch, I have one major comment.

Some pages are really too long to display few information. `/commands` and `/contacts`, for instance, could be a very efficient using simply a bootstrap table.

In my opinion, the best example is `/problems`. This page looked wonderful at the first look… and then I realized it is completely unusable. On this page, efficiency should be more important than beauty. Take a look at the old webui or even at thruk: it's just a table, but we have everything we need in one page, without having to scroll and click to unfold stuff.

To everyone working on this, thanks for your work!

**Comment by mohierf** [comment]
Thank you for your comment and time. BS3 was, at first, built as a moke-up and you are right ... some pages seriously need to be reworked to be more efficient when used ... I am currently working on some improvements for the problems page ! 

 I already refactored some of this page building process but do not yet have a commitable version ...

 For more information, how many objects do you have in your configuration : hosts, services, contacts, timeperiods, groups, tags ?

**Comment by maethor** [comment]
Hi, thanks for your answer. I'm available to discuss it and to help you on the code if you want. I use shinken every day and I know very well bootstrap. I never contribute to the shinken code, but I'd be happy to.

I have around 150 hosts and more than 2000 services. I have currently 27 services down, 20 warning and 8 unknown. I have 3 contacts, the usual 5 or 6 timeperiods, around 15 hostgroups and no tag.

**Comment by mohierf** [comment]
I am never connected on the IRC channel ;-)

I know quite well the WebUI source code based upon python bottle Web server and its templating feature ... but I am not an expert in bootstrap coding. This is why I am interested in your proposal for helping with the bootstrap code ... it may really help if you could build an HTML/Bootstrap moke-up for a problems page based upon a bootstrap table ?

 Please feel free to contact directly by email (frederic.mohier@gmail.com) instead of this issue ...

**Comment by mohierf** [comment]
Boostrap theme and skinnable seems to be ok. Build your own bootstrap theme and copy in *webui/htdocs/js*, *webui/htdocs/css*, *webui/htdocs/fonts* directories ...
