### ISSUE TITLE
Business impact issue webui

### ISSUE THREAD

**Issue by Frescha** [shinken-monitoring/mod-webui#14]
Hello,

I think there is a issue in shinken on business_impact business_impact and modulation

In fact I configured on one service business_impact 2 in normal
and I specified a businessimpactmodulation to 3 over the period 8h-18h

{define businessimpactmodulation
business_impact_modulation_name period neo-
business_impact 3
modulation_period workhours neo-
}

the scale of the impact between 2 and 3 in the WebUI is good so during workhours period neo- I have my service that is visible with a business impact High and when I'm over the period my service switches to 2 business impact is normal.

till now no problems.

However when i pass to workhours period neo-impact business 3 (minimum to appear in the tab Impacts) the service does not appear in the Impact tab.

regards

**Comment by mohierf** [comment]
Closing ... should be tested on future release. But seems to be related on Shinken framework behaviour ....
