### ISSUE TITLE
Comments, acknowledgements, ... with accented characters

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#141]
French accented charcarcters seem not to be considered ...  to be checked and fixed if buggy !

**Comment by maethor** [comment]
With or without accents, the comments doesn't works for me. I can post a comment, but the content is "undefined".

**Comment by mohierf** [comment]
I am trying to fix the accented characters bug ... but it is not very simple ! There is a solution that is to convert all accented characters in the WebUI to their non accented version, but it is not very user friendly ...

**Comment by maethor** [comment]
Failing is not user friendly. If you can fix by removing the accents, I think it's OK for a workaround. We can always improve later.

**Comment by mohierf** [comment]
I think this will be the first scenario ... because it does not seem that
easy to deal with accented characters in Shinken :/P

2015-06-03 18:39 GMT+02:00 Guillaume Subiron <notifications@github.com>:
