### ISSUE TITLE
Element state icons ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#147]
We decided to make more consistent the element's state rendered by the WebUI ... as of it this issue explains the rules used for this ..

Element (host/service) state icons rules definition : 
- for an host : 
  - use the same icon whatever the state is
  - icon color is *success* if host is UP
  - icon color is *alert* if host is UNREACHABLE
  - icon color is *danger* if host is DOWN
  - icon color is *info* if host is UNKNOWN / PENDING

 - for a service : 
  - use icon *thumbs-up* if service is OK
  - use icon *warning* if service is WARNING
  - use icon *remove* if service is CRITICAL
  - use icon *question-circle* if service is UNKNOWN
  - use icon *circle-o-notch* if service is PENDING
  - icon color is *success* if service is OK
  - icon color is *alert* if service is WARNING
  - icon color is *danger* if service is CRITICAL
  - icon color is *info* if service is UNKNOWN / PENDING

- for an host or service : 
  - stack a *check* icon if host/service is a problem and it has been acknowledged
  - add an *ambulance* icon if host is a scheduled downtime
  - add a *spin* icon if host is flapping

**Comment by maethor** [comment]
Instead of `thumbs-up` and `remove`, we could simply use up and down, like in `eltview`. Using `check` for the acknowledged state is a good idea.

**Comment by maethor** [comment]
I propose a new set of rules:

- Whatever the state is, stack an icon on a plain circle. The icon is white (fa-inverse), and the plain circle has a CSS class `font-{{state.lower()}}` (`font-ok`, for instance). These CSS classes are already declared in the CSS. So we don't use bootstrap's color anymore (they are not punchy enought).

- For an host, the icon is always fa-server.

- For a service:
  - use `fa-up` if the service is OK
  - use `fa-down` if the service is DOWN
  - use `fa-exclamation` if the service is WARNING
  - use `fa-question` if the service is UNKNOWN
  - use `fa-circle-or-notch` if the service is PENDING

- Special cases (apply on hosts and services):
  - use `fa-check` if the object is acknowledged
  - use `fa-ambulance` if the object is in scheduled downtime
  - if the service is pending, replace the `fa-circle` (background) by `fa-spinner fa-spin`, and colorize the object icon like the `fa-spinner`.

This spec has the big avantage to work with only one icon. We may loose a little information in some special cases (for instance, if we have a downtime or ack object, we don't know if it's a host or a service), but the icon is never display alone, so it's not a big deal. More over, I suggest to always put a title on the icon: for exemple "service is WARNING and acknowledged and flapping". So with a simple hover, we have all the informations.

Theses new rules are already implemented in this PR: https://github.com/Sysnove/mod-webui/commit/19c69db5524127decc9141492b6cf2b4587435a3

**Comment by mohierf** [comment]
Really nice ! 

![image](https://cloud.githubusercontent.com/assets/2932687/7897311/dbf4853a-06d7-11e5-95f6-8246baa8b388.png)

**Comment by maethor** [comment]
I also really like it. The next thing I will do is to replace every icons by theses ones… or at least try to :)

Typically, it would be nice to use this function in the problems synthesis. Maybe with a base function that would be more generic, I don't know. What I'm sure is that we should convert states to icons in only one place.

**Comment by maethor** [comment]
I propose a new set of rules:

- Whatever the state is, stack an icon on a plain circle. The icon is white (fa-inverse), and the plain circle has a CSS class `font-{{state.lower()}}` (`font-ok`, for instance). These CSS classes are already declared in the CSS. So we don't use bootstrap's color anymore (they are not punchy enought).

- For an host, the icon is always fa-server.

- For a service:
  - use `fa-up` if the service is OK
  - use `fa-down` if the service is DOWN
  - use `fa-exclamation` if the service is WARNING
  - use `fa-question` if the service is UNKNOWN
  - use `fa-circle-or-notch` if the service is PENDING

- Special cases (apply on hosts and services):
  - use `fa-check` if the object is acknowledged
  - use `fa-ambulance` if the object is in scheduled downtime
  - if the service is pending, replace the `fa-circle` (background) by `fa-spinner fa-spin`, and colorize the object icon like the `fa-spinner`.

This spec has the big avantage to work with only one icon. We may loose a little information in some special cases (for instance, if we have a downtime or ack object, we don't know if it's a host or a service), but the icon is never display alone, so it's not a big deal. More over, I suggest to always put a title on the icon: for exemple "service is WARNING and acknowledged and flapping". So with a simple hover, we have all the informations.

Theses new rules are already implemented in this PR: https://github.com/Sysnove/mod-webui/commit/19c69db5524127decc9141492b6cf2b4587435a3

**Comment by mohierf** [comment]
Hi @maethor ... what is the difference with your previous comment 2 days ago ?

**Comment by maethor** [comment]
The difference is that I posted the comment two days ago, and today it's a javascript bug in my browser that reposted the comment :)

I was about to do the same modifications, so thank you :)

**Comment by mohierf** [comment]
I close this ..

**Comment by mohierf** [comment]
I think that changing opacity for acknowledged and downtimed elements will be interesting ...

![image](https://cloud.githubusercontent.com/assets/2932687/8258262/d82246ea-16b3-11e5-9c3d-51fb0c223404.png)

What do yout hink about it ? @maethor

**Comment by maethor** [comment]
I think it's very nice!

Just an idea, did you try to change only the opacity of the inner icon, not the background?

**Comment by mohierf** [comment]
Really nicer with this opacity: 
![image](https://cloud.githubusercontent.com/assets/2932687/8307779/d27d48ba-19c0-11e5-8b63-6af1b2738878.png)

**Comment by maethor** [comment]
I agree, this is awesome.

**Comment by mohierf** [comment]
Available in all the WebUI, except for dependency graph and impacts view ...
