### ISSUE TITLE
List views pagination

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#148]
Some rules about pagination in list views : 
 - [x] pagination widget include buttons for : 
   - First page
   - Previous page ( X-1 )
   - Current page (X)
   - Next page (X+1)
   - Last page

 - [x] pagination widget allows to modify the current number of displayed elements in the view

 - [x] current number of elements may be stored in user's preferences

**Comment by mohierf** [comment]
@maethor: should you modify pagination or we close ?

**Comment by maethor** [comment]
You can close.
