### ISSUE TITLE
what is the release cycle about mod-webui

### ISSUE THREAD

**Issue by andyxning** [shinken-monitoring/mod-webui#157]
@mohierf , i think we have make the WebUI more robust under bs-3 branch. So, my question is what is the release cycle about mod-webui. I want to make a chance with bs-3, however, when i click the release tab in Github, i have seen that we have about currenly 139 commits ahead of the release bs-3. 

So, i was confused that,
* can i use bs-3 with the expect that we have make more enhancement proposed in the issues, or should i just clone the master branch.
* what is the release cycle about bs-3.

**Comment by mohierf** [comment]
We are still in a transition phase with this project and BS3 branch is a really good candidate to become the new master branch of the Shinken WebUI!

 We made real improvements on this branch and we are still testing if it is stable enough to become the new master ... discussions are ongoing about it.

 As of it, we did not yet defined a roadmap or a release cycle. As you may see, we are regularly pushing some modifications and we will probably tag a release in the next few days as I did on early April.

 If I remember well, you are monitoring a quite important configuration ... would you mind having a look at this branch and report about it ?

**Comment by andyxning** [comment]
Absolutely Yes, then i decide to get the BS3 branch to make a tempt instead
of the BS3 release.

If i have some questions, i will let you know soon. :-)

++++++
Ning Xie


2015-06-04 11:52 GMT+08:00 Frédéric MOHIER <notifications@github.com>:

**Comment by andyxning** [comment]
@mohierf , can you please see the PR #115 about default downtime values. It is very simple. :)

**Comment by mohierf** [comment]
Opened a roadmap issue ... https://github.com/shinken-monitoring/mod-webui/issues/195
