### ISSUE TITLE
[BS3] New filter system

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#158]
To unify `problems`, `hosts`, `services`, and `all`, I think we should work on a new, simple, filter system. So I was looking around on the web to find something nice, and I think I'm really in love with the Github issues filter.

With a system like this, we could regroup bookmarks and filters in one line, and we could present some common presets to the user (problems, ack, etc.). It would be really easier to use.

As a matter of facts, the actual system is close to this, so it will be simple to modify the webui while keeping the filter algorithm.

What do you think @mohierf ? I will do a PR to try this idea.

**Comment by mohierf** [comment]
Nice idea ... up to you !

**Comment by maethor** [comment]
Hm… besides the filters, there is a small difference between /problems and /all.

In /problems, the elements are retrieved using `app.get_all_problems()`. Impacts are regrouped under the main issue, and are not displayed. 

In /all, the elements are retrieved using `app.get_all_hosts_and_services()`. The impacts are regrouped under the main issue, but there are also returned by the function, and displayed in the list.

I think get_all_hosts_and_services() should take an argument `get_impacts=False`, and that we should use this argument to filter the impacts and don't display them in /all. What do you think @mohierf ?

Then, it will be possible to remove `get_all_problems`, and to filter OK/UP/PENDING elements in the view.

**Comment by mohierf** [comment]
Seems to be a good idea. You propose a modification in this way in a PR ?

**Comment by maethor** [comment]
Yes. it works just fine. In fact, I have completely remove the /problems page, the controller now redirects to `/all ?search=isnot:OK isnot:UP isnot:PENDING ack:false downtime:false`.

I don't have time to commit right now, but tonight you'll see it.

**Comment by maethor** [comment]
I see you merged my PR. What do you think @mohierf ?

**Comment by mohierf** [comment]
I just made few tests and I like it ... just fixed a problem with navigation element :-)

Filters dropdown may include downtimed ?

**Comment by maethor** [comment]
Filters dropdown may include anything.

In fact, I think they will include global bookmarks, and the bookmark dropdown will only include user bookmarks. That way, we could deliver the webui with some pre-configured global bookmarks, and allow the user to do what he want with them (create, update, delete…). The only problem with this idea is that I don't know how to add the "Problems" global bookmark to everyone without breaking anything.

**Comment by mohierf** [comment]
I will have a look on it ...

I am currently looking how to implement global and user's preferences ... how it is implemented and how to enrich this feature !
