### ISSUE TITLE
details info show Error with Internal server error.

### ISSUE THREAD

**Issue by andyxning** [shinken-monitoring/mod-webui#159]
i have test BS3 branch in our situation with the install guide given in the readme.md. However, when i want to get  the detail info about a service or host i get an internal server.

![image](https://cloud.githubusercontent.com/assets/2404712/7980831/4fc3b3ce-0add-11e5-87b7-5644ffaa2233.png)

And when i choose the hostgroups something is still wrong.

![Uploading image.png…]()
![Uploading error.png…]()

The same with servicegroups.

And many other views are going answer with an "Internal server error".

Any thing is wrong?

**Comment by mohierf** [comment]
@andyxning : your screen captures did not copied ...  I made more tests this evening on hostgroups and servicegroups but did not found any problem. Please copy new captures or error messages, I will have a look ASAP.

**Comment by maethor** [comment]
Instead of making screenshot, you can also simply copy paste the Traceback blocks.

**Comment by maethor** [comment]
Hum, I just see that @mohierf have made a commit yesterday that should fix your bug in `eltview`. Please update to the head of the branch and try again.

**Comment by maethor** [comment]
@andyxning can you confirm this issue is closed, and close it, please?

**Comment by andyxning** [comment]
Yes, it can be closed.

++++++
Ning Xie


2015-06-09 23:38 GMT+08:00 Guillaume Subiron <notifications@github.com>:
