### ISSUE TITLE
[BS3]minemap : Internal Server Error

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-webui#161]
with the lastest  BS3 version, I have the error below with minemap. I missed something ? 

Error: 500 Internal Server Error

Sorry, the requested URL 'http://192.168.0.100:7767/minemap/all' caused an error:

Internal Server Error

Exception:

KeyError('minemap_hostsHide',)

Traceback:

Traceback (most recent call last):
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui/module.py", line 539, in lock_version
    return f(**args)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 3615, in wrapper
    result = func(*args, **kwargs)
  File "/var/lib/shinken/modules/webui/plugins/minemap/minemap.py", line 96, in show_minemap
    if h.get_name() in params['minemap_hostsHide']:
KeyError: 'minemap_hostsHide'

**Comment by mohierf** [comment]
Sorry but I did not reproduced this problem on my test environment ... do you have a *plugin.cfg* file in your minemap directory ?

In this file you may declare the hosts to be hidden in the minemap in the *minemap_hostsHide* variable ...

 It should look like this : 
```
[plugin]
# How many elements per page
elts_per_page=20


# Minemap hosts are filtered 
# - list of hosts business level to display
# The hosts with the defined business levels are the only hosts displayed in the minemap
# map_hostsLevel=1,2,3,4,5
# For all hosts to be displayed
minemap_hostsLevel=3,4,5
# Only the most important one ...

# - list of services to display (always)
# The hosts defined in this list are always displayed whatever their business level
minemap_hostsShow=shinken24

# - list of hosts to hide (always)
# The hosts defined in this list are never displayed whatever their business level
minemap_hostsHide=


# Map services are filtered 
# - list of services business level to display
# The services with the defined business levels are the only services used to build the hosts overall state in the minemap
# Whatever their business level, they are displayed in the minemap except if they are in the map_servicesHide list ...
minemap_servicesLevel=1,2,3,4,5

# - list of services to hide (always)
# The services defined in this list are never displayed whatever their business level
minemap_servicesHide=
```

**Comment by b-keller** [comment]
no, any plugin.cfg... this file doesn't exist on the BS3 repo.
I created the file with the line above but I made one little change 
`minemap_hostsLevel=1,2,3,4,5` Instead of `minemap_hostsLevel=3,4,5`
Otherwise no hosts are diplay on Minemap...

**Comment by mohierf** [comment]
Sorry for the mistake ... I committed a file
