### ISSUE TITLE
Problems view : responsive design ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#163]
Depending on browser viewport resolution ... take car about table columns ... some columns should not be displayed for lower resolutions : 
 - duration and output should be hidden
 - in panel : realm, active/passive check information should also be hidden

**Comment by maethor** [comment]
I agree, I can do it in the problems view.

**Comment by maethor** [comment]
This is done by #185. @mohierf you can close this issue.
