### ISSUE TITLE
[BS3]navbar : small bugs

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-webui#165]
with 1366*768 resolution, there are some small bugs on the navbar : 
- search box hide the date 
- problems and impact icons focus overflow

![sans titre](https://cloud.githubusercontent.com/assets/12746104/8015814/4d606c80-0bdc-11e5-8efd-5201cfecc96b.png)

**Comment by mohierf** [comment]
Should be fixed with my last commits ...
