### ISSUE TITLE
Sidebar layout of menu items ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#166]
On wide screens, the menu items in the sidebar are not displayed correctly :/P

![image](https://cloud.githubusercontent.com/assets/2932687/8028420/749ec26a-0dad-11e5-8038-54592ade7e30.png)

**Comment by maethor** [comment]
@mohierf tu as regardé le thème sb-admin-2 de bootstrap ? Je pense que ça pourrait fournir une bonne webui pour l'interface.

**Comment by maethor** [comment]
Since I rewrite this to use "sb-admin-2", @mohierf you can close this issue.
