### ISSUE TITLE
[BS3] WebUI fu**ed up

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#167]
@mohierf I just pull the lasts commits… what have you done!? :D 

I seems the skin doesn't works anymore, neither does the JS in `/problems`.

**Comment by mohierf** [comment]
I do not understand ... the modifications I commited are clean on my environment ! The JS on problems page are Ok ... I even installed on my production and it is ok !

It only changed the look and feel of the pages ...

 Whar are exactly your problems ?

**Comment by maethor** [comment]
I sent you an email with the screenshot, you'll see :)

**Comment by maethor** [comment]
Since I completely rewrote the layout to use sb-admin-2, I can close this issue.
