### ISSUE TITLE
User's preference : elements per page

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#168]
The number of elements per page is saved as a user preference.

The number of elements per page is displayed and editable in the pagination component (as an input field and as a selectable item).

The main poroblem is that the pagination element is only displayed if needed on a page ... and if it not displayed the user is not able to change the number of elements per page ! Deadlock ...

 A solution should be to allow this parameter to be editable from the navigation bar ?

**Comment by maethor** [comment]
It's not a problem. I can do this tonight.

**Comment by maethor** [comment]
@mohierf you can close this issue.

But there is still a bug in the widget. The field always display "25" instead of the actual number of elements per page.

**Comment by mohierf** [comment]
I leave open for the "25" ... :-)

**Comment by maethor** [comment]
@mohierf now you can close this issue.
