### ISSUE TITLE
WebUI user's class: role, profile, ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#174]
The sidebar menu configuration currently in a *menu.cfg* that has been removed to be replaced by parameters to be stored in the User's preference.

**Comment by maethor** [comment]
Is it really a useful feature ?

**Comment by mohierf** [comment]
Find this useful if it is coupled with a kind of user's profile ...

**Comment by mohierf** [comment]
Create a WebUI user class with its role, profile, ...

**Comment by maethor** [comment]
The WebUI user class is still very limited, and we maybe could move authentication and preferences methods in it. But for 2.0 I think it's a good base so I close this issue.
