### ISSUE TITLE
WebUI BS3 roadmap proposal

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#176]
The BS3 WebUI roadmap doc (https://github.com/shinken-monitoring/mod-webui/blob/bs3/roadmap.md) has been updated.

The main idea is to focus on building an effective and pleasant interface that implements the main necessary features for daily monitoring.

Main features: 
 - clean and pleasant layout
 - filterable monitored resources lists
 - bookmarkable filters
 - backend configuration for application and users
   users preference in DB - remove config files
 - hosts/services are only the one that the logged in user is linked with

**Comment by maethor** [comment]
I'm OK with this. I think we are close to the goal.

**Comment by mohierf** [comment]
Edited the initial comment to add the last line ...

**Comment by maethor** [comment]
Oh yep! I forgot about that, it would be great indeed.
