### ISSUE TITLE
WebUI should have its own DataManager class

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#178]
Currently, the Shinken data model is stored in a "standard" Shinken DataManager but some methods should be overloaded for easier object management ...

Methods used by the WebUI have been included in the *module.py* file but should be moved to a specific DataManager inheriting from Shinken one.

**Comment by mohierf** [comment]
@ddurieux : what do you think about it ?

Main ideas are:
- [ ] build Shinken configuration from hosts inventory
- [ ] store hosts/services/contacts/ .... indeed monitoring configuration objects  in a monitoring backend
- [ ] use an API to get/set monitoring objects

**Comment by maethor** [comment]
@mohierf what do you have in mind about this DataManager class?

**Comment by maethor** [comment]
I think the goal is achieved, so I close this ticket. @mohierf you can reopen if you think there is still some work to do on the datamanager.
