### ISSUE TITLE
Dashboard - relooking

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#179]
Top bar indicating : 
- hosts state : total hosts number / percentage of hosts down
- services state : total service number / percentage of service critical
- number of IT problems
- number of impacts

![image](https://cloud.githubusercontent.com/assets/2932687/8145409/967dadb6-1207-11e5-92a4-8c8a404509dd.png)

**Comment by ddurieux** [comment]
I think the button "+ Add new widget" is too big, perhaps only have button "+" and the text in 'alt' of < img >

**Comment by maethor** [comment]
@ddurieux we don't need to save space. So I think explicit is better than implicit.

@mohierf I like the dashboard. I think when we click on "Hosts DOWN" and "Services KO" we should be going to `/all?search=type:host isnot:OK` and `/all?search=type:service isnot:OK` instead of hosts-group and minemap.

**Comment by ddurieux** [comment]
Sorry, not explain enough :p
It's not a space problem, but it's too big and so eyes see it more / same than other important information

**Comment by mohierf** [comment]
I agree with both of you ... but I think that the button should be removed from the top bar ... but where should we place it ... to be discussed and tested ...

**Comment by mohierf** [comment]
Dashboard currently view (click on eye icon in the navigation bar ...)

![image](https://cloud.githubusercontent.com/assets/2932687/8153359/203267e2-132d-11e5-954f-7cc3debbe7dc.png)

**Comment by ddurieux** [comment]
I prefer text horizontal instead vertical because verticial is not easy to read :p

**Comment by maethor** [comment]
I agree with @ddurieux.

**Comment by mohierf** [comment]
Relooking, horizontal texts ...

![image](https://cloud.githubusercontent.com/assets/2932687/8159605/94d7b864-1368-11e5-8133-4013cfd7503d.png)

**Comment by mohierf** [comment]
New dashboard currently version : 
![image](https://cloud.githubusercontent.com/assets/2932687/8257807/89bf3b1e-16b0-11e5-8230-1f726d7ddccd.png)

**Comment by maethor** [comment]
@mohierf I think you can close this issue.
