### ISSUE TITLE
[BS3] Minemap sorting

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#182]
In the minemap, I think we should sort columns (services) by the frequency they appears in the hosts. For example, in my minemap, the ~50'ths firsts columns are "Backups hostname.sysnove.net", a service that present only on my backup server. On the contrary, I have to scroll a lot horizontally for "SWAP usage", a service present on every host.

@mohierf I can do this, if you are OK.

**Comment by mohierf** [comment]
Ok for me.

**Comment by maethor** [comment]
@mohierf you can close this issue.

**Comment by mohierf** [comment]
Nice feature !

![image](https://cloud.githubusercontent.com/assets/2932687/8165222/fd443a0a-138e-11e5-936e-2f11ccfd6198.png)
