### ISSUE TITLE
Layout broken on low resolution

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#183]
On low resolution device, the new layout is broken because the sidebar seems to be fixed on top of the screen.

![image](https://cloud.githubusercontent.com/assets/2932687/8152642/54395b02-1320-11e5-9db2-02620101ab63.png)

**Comment by maethor** [comment]
Yes, the input field should be responsive, but I don't know how to do it.

**Comment by mohierf** [comment]
Made a test with last commit: https://github.com/shinken-monitoring/mod-webui/commit/ee800841ff27f519fee3507b9232a8fa4e363333, do not set input field width. It is not yet responsive but the navigation bar seems mode fluid :/P

**Comment by maethor** [comment]
I agree, this commit is nice.

**Comment by mohierf** [comment]
My last commit (https://github.com/shinken-monitoring/mod-webui/commit/82d5b972bd80b02d7a1e73b42e374c8f876db6b4) intends to make the navigation bar more fluid, but it is still broken on smaller resolution ... :/P

Width >= 1200px
![image](https://cloud.githubusercontent.com/assets/2932687/8154872/d8c6a564-133e-11e5-9e39-4c4a4bebf6ee.png)

Width < 1200px
![image](https://cloud.githubusercontent.com/assets/2932687/8154891/1fba17b2-133f-11e5-833b-6be2c62c7d5c.png)

Width < 992px:
![image](https://cloud.githubusercontent.com/assets/2932687/8154916/46663a12-133f-11e5-8c36-40254ac1e7eb.png)


Width <= 768px: Still broken !!!
![image](https://cloud.githubusercontent.com/assets/2932687/8154931/65340028-133f-11e5-8978-e5f5bc399bb0.png)

**Comment by maethor** [comment]
On wide screens, the input field should be wider.

**Comment by mohierf** [comment]
You are right ... but it does not seem that easy :/P

**Comment by maethor** [comment]
Oh, it's not that complicated either. But I was looking for a way to do it with pure bootstrap classes (like col-sm-*), and I can't find a way to make it work.

**Comment by mohierf** [comment]
Neither did I ! It seems that pure bootstrap is not enough ... I propose to leave as is and to create an issue to keep tracking this problem. We will manage this feature later ?

**Comment by maethor** [comment]
OK.

**Comment by maethor** [comment]
For low resolution screens. I see 2 solutions:
- remove the input field (and every wide and dispensable elements),
- or set a min-width (maybe 780px, I don't know).

**Comment by maethor** [comment]
@mohierf I think you can close this issue.
