### ISSUE TITLE
Main page improvement, still some to do ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#184]
We still should try to improve the main page layout:
- filters and bookmarks buttons should only have an icon, at least on low resolution (md)
- filter input box should be responsive
- minimize the breadcrumb
- elements per page input form

![image](https://cloud.githubusercontent.com/assets/2932687/8152695/e7ff4b94-1320-11e5-859e-afd6312dc4df.png)

I will commit a simple modification that makes it as of it ... 
![image](https://cloud.githubusercontent.com/assets/2932687/8153218/86d38d62-132a-11e5-922b-6627cea710af.png)

 Navigation bar is broken ... right, but it seems important to restore information about overall state of the system.

 There are still some improvements that have to be done but I think that when we will get rid of the input field, il will be easier !

 The input form for elements per page is almost the same problem as the "Add a widget" button in the dashbaord page ... where should we locate those extra controls ?

**Comment by maethor** [comment]
Hm… We don't have the same display.

![2015-06-15-074800_1600x900_scrot](https://cloud.githubusercontent.com/assets/2410576/8153789/00606170-1333-11e5-9b64-2a37512bc1a3.png)

**Comment by maethor** [comment]
@mohierf did you find why the navigation links are not right aligned in your webui ?

**Comment by mohierf** [comment]
No. I still have this problem with a screen width at 800px ...
![image](https://cloud.githubusercontent.com/assets/2932687/8159894/535e6ace-136b-11e5-9ce5-0377f66690d5.png)

**Comment by maethor** [comment]
This is crazy, 800px looks fine on my computer.

![capture d ecran 2015-06-15 a 17 01 44](https://cloud.githubusercontent.com/assets/2410576/8162891/56c39f12-1380-11e5-8d64-a6ea5fed8fe9.png)

**Comment by maethor** [comment]
I see, with Chromium I get a different result, and indeed on 800px I see your screenshot.
