### ISSUE TITLE
Navigation bar layout for low resolution devices

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#186]
For low resolution devices the current layout of the navigation bar is corrupted because of the search input field: 

![image](https://cloud.githubusercontent.com/assets/2932687/8157826/0cd00df0-1358-11e5-9d88-1bb75fbbfcd3.png)

The input field width seems to get width = 100 %

Several solutions:
- adapt the search input field width
- remove the input field,
- change the min-width (maybe 780px, I don't know)

A really nice solution should be to use this kind of template : http://ironsummitmedia.github.io/startbootstrap-simple-sidebar/, @maethor ?

**Comment by maethor** [comment]
I think we need the top navbar. And my last PR is already fixing this issue.

**Comment by mohierf** [comment]
You are right. I close this issue.
