### ISSUE TITLE
Bug displaying overall states icons in navbar

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#189]
Since https://github.com/shinken-monitoring/mod-webui/commit/d1be3105f4937a3d8571621183f85737c0b3e2d5, the content of the buttons is not aligned with the "blocks".

![2015-06-15-172529_1600x900_scrot](https://cloud.githubusercontent.com/assets/2410576/8163500/addd4610-1383-11e5-9423-040e4db79c5f.png)

**Comment by mohierf** [comment]
Probably, I should try a badger on top and one on bottom ... on top, number of hosts and on bottom percentage of hosts UP. What do you think @maethor ?

**Comment by maethor** [comment]
Should be nice.

**Comment by mohierf** [comment]
![image](https://cloud.githubusercontent.com/assets/2932687/8184284/d8d94a70-143d-11e5-91aa-2c37faeb94e1.png)

What do yout think @maethor  : 
- host overall state goes to */all?search=type:host* or */all?search=type:host%20isnot:OK* ? First choice seems better ...
- service overall state goes to */all?search=type:service* or */all?search=type:service%20isnot:OK* ? First choice also seems better ...

**Comment by maethor** [comment]
I think the top badger should be "nb_down/total", because with the current display it's impossible to tell what is displayed (down ? up ? total ?).

And I think the link should filter to only display the problems. So second choice seems better to me. But I'm not sure. I never use them.

**Comment by maethor** [comment]
By the way, I really like having one on top and one on bottom!

**Comment by maethor** [comment]
And I think you should also filter the downtime and acknowledged elements in the links. And on the hosts link, you have to do "isnot:UP" instead of "isnot:OK".

**Comment by mohierf** [comment]
Ok, I will make some tests for the top badger to display nb_down / total ... but I am not sure it will be quite explicit ...

For the link, we have the Problems sidebar menu that displays the problems ... I think that these two buttons should display all the hosts/services whatever their current state is ? If you want the same as Problems, click on problems ... no ?

**Comment by maethor** [comment]
I don't know. As I was saying, I'm not using this links, so… you can do as you want :)

**Comment by maethor** [comment]
@mohierf This bug is fixed, but there is a new one :(

![2015-06-18-110853_1920x2100_scrot](https://cloud.githubusercontent.com/assets/2410576/8227853/aac5e7ba-15aa-11e5-8782-1eeb59687d02.png)

**Comment by mohierf** [comment]
You are right ... this is why I did not closed this issue. I am testing on a production environment if these information are consistent and useful ... I will rework the navigation bar once validated.

**Comment by mohierf** [comment]
Closed by #212
