### ISSUE TITLE
Element synthesis

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#193]
We have to decide if the elements (hosts and services) synthesis should be based on the current page or on all the elements matching the current filter.

For now, it's based on the current page. I think it's a mistake.

What do you think @mohierf ?

**Comment by mohierf** [comment]
You are right ... I observed it today and discussed about it ... I think the synthesis should consider all hosts/services matching the filter and not only the currently displayed.

 My idea about it is that it should be a *module.py* function that returns an array of states that may be used in any page ... a function that should be like *get_all_problems*, *get_nb_problems*, ...

**Comment by maethor** [comment]
I agree. I am refactoring element search right now (with a new function in module.py). I can follow with this tonight.

**Comment by mohierf** [comment]
Thanks

2015-06-16 17:44 GMT+02:00 Guillaume Subiron <notifications@github.com>:

**Comment by maethor** [comment]
@mohierf you can close this issue.
