### ISSUE TITLE
Debian 8 : very long time before login available

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#194]
On a Debian 8 Jessie, the login page of the WebUI is displayed but the user authentication is not available before several minutes (4/5 minutes). This problem is probably to be related with the many connections errors that occurs between the Shinken daemons (https://github.com/naparuba/shinken/issues/1659).

In fact, the WebUI does not receive its configuration from the scheduler and, as of it, do not find any contact to authenticate against ...

The same configuration of Shinken with the same modules do not have the same behavior on Shinken 7 Wheezy ...

**Comment by maethor** [comment]
I'm on Debian 8, but I don't have this problem.

**Comment by mohierf** [comment]
Do not have no more ... I came back to a Debian 7 :-)

I suppose this problem was due to Shinken issue.

**Comment by david-guenault** [comment]
https://github.com/naparuba/shinken/commit/e8d929c5aa8fb0e9e8b524919997715640335485



2015-06-18 5:57 GMT+02:00 Frédéric MOHIER <notifications@github.com>:

**Comment by mohierf** [comment]
Already tried this fix ... no success.

**Comment by mohierf** [comment]
Seems to indepedent from WebUI

**Comment by cwahl-Treeptik** [comment]
I am also facing this issue.

**Comment by mohierf** [comment]
Sorry, we should not help very much ... this problem seems to be a Shinken one. I saw you opened an issue in Shinken project ... I also did it, but with no success. I downgraded to Shinken Wheezy ...

**Comment by cwahl-Treeptik** [comment]
I have actually found a work around though it's not very elegant. Since I use a distributed architecture, with many hosts and several realms, and only the shinken master is based on Debian 8, I simply use a distant poller for this host. Then, I got no more error message from the broker and all my hosts are properly monitored.
