### ISSUE TITLE
Problems view : responsive table

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#198]
Should be interesting to be able to see long_output for problems. For instance, the displayed output is truncated and the check long_output is not visible.

![image](https://cloud.githubusercontent.com/assets/2932687/8203545/e2d8c0f0-14e2-11e5-853b-6bbb483eccf8.png)

We should implement a popover to display output and long_ouput ?

**Comment by maethor** [comment]
I was planning to try to do this to avoid huge outputs.

The only question is how to truncate ? It should depends on the screen width. Do you have an idea ?

**Comment by mohierf** [comment]
Why not using a popover like for perfometer ?

**Comment by maethor** [comment]
That's not my question. Correct me if I'm wrong:
- The popover will display the "long_output" when we hover the "short_output", right?
- The idea is that this "short_output" should not exceed one line in the output column of the table, right?

So how to you compute this "short_output"? It completely depends on the screen width.

**Comment by mohierf** [comment]
What I propose for the check output overall management by the WebUI : 

 There are parameters for this feature in WebUI.cfg :
```
   allow_html_output          1
                              ; Allow or not HTML chars in plugins output.
                              ; WARNING: Allowing can be a security issue.
                        
   max_output_length          1024
                              ; Maximum output length for plugin output in webui
```

 We should make this management consistent in element and problems view, so I propose : 
 - the output of the check is displayed and truncated to *max_output_length* value
 - in the views, we should truncate the truncated output to be more responsive ?
 - when hovering this output, we display a popover including the complete output and the long_output

 I know that we almost achieved this in the element view ...

**Comment by maethor** [comment]
I agree to this solution. But we have to find a way to make the output responsive to the browser width. I don't know how, but it should be possible.

With that said, I can begin to work with the `max_output_length`.

**Comment by mohierf** [comment]
BS3 responsive truncation seems to be possible : http://stackoverflow.com/questions/23431970/bootstrap-3-truncate-long-text-inside-rows-of-a-table-in-a-responsive-way

**Comment by maethor** [comment]
This is so awesome… I'll try it right now.

**Comment by mohierf** [comment]
I added **Bug** label because of this : 
![image](https://cloud.githubusercontent.com/assets/2932687/8238064/a9253f34-15f3-11e5-9c00-54d25aa82071.png)

It seems that the new table layout is not really responsive ... :/P

**Comment by maethor** [comment]
f**k :(

The problem is that we have to use `table-display:fixed;` on the table. So the table columns are not responsible anymore: column sizes are fixed. I think we should try to use percents instead of px in the column widths. But it will be hard to make this responsive :(
I don't know…

**Comment by mohierf** [comment]
Last commit allows this:
![image](https://cloud.githubusercontent.com/assets/2932687/8307968/3a48a042-19c2-11e5-9e00-089266d8d616.png)

**Comment by maethor** [comment]
I like it. I don't want popovers poping everywhere when I just move my mouse around. And I think clicking on the line to unfold it is nicer. It should be better to put directly "long output" instead of "output" in the output column.

**Comment by mohierf** [comment]
You must have output **and** long_output because they are not the same ... *output* is the first part of the first line output by the check, and the long_output contains all the lines after the first lines, but wihout the extra perfdata. What a mess this specification !

We should activate the popover only on click instead of hovering ?

**Comment by maethor** [comment]
"on click" will not work nicely because it will be visually in conflict with the collapse.

I think the collapse is enough. When it's "closed", it will show only the first line of the output. When it's "open" it will show all the lines.

**Comment by mohierf** [comment]
Ok for collapsing ... should you make this modification ?

**Comment by maethor** [comment]
OK, I'm adding this to my todolist for tonight :)

**Comment by maethor** [comment]
@mohierf I'm currently testing the responsiveness of the elements table. What should be the minimum supported screen width?

**Comment by mohierf** [comment]
I believe that we should be able to downgrade the interface to 640px ... which is the resolution of many smartphones ?

**Comment by maethor** [comment]
OK!
