### ISSUE TITLE
Element (host/service) tags in element view

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#199]
![image](https://cloud.githubusercontent.com/assets/2932687/8215350/99e6fec8-152f-11e5-9d7b-b8efed78ace8.png)

Logical behind this display is: 
1/ search tag image in share dir, if found (image provided by an installed monitoring pack) use this image
2/ else, search tag image in own tags library (common tags), but if not found ...
3/ use a default tag image 
![image](https://cloud.githubusercontent.com/assets/2932687/8215490/768ab22a-1530-11e5-90f6-37fc3554b8ad.png)

**Comment by mohierf** [comment]
My lastest commit ...

**Comment by maethor** [comment]
I'm not found of the default image, because we loss the information at first sight. But this is nice. It could encourage to deliver icons with the packs.

**Comment by mohierf** [comment]
I prepared a version with small labels but I did not found it nice : 
![image](https://cloud.githubusercontent.com/assets/2932687/8223610/875cd76e-157a-11e5-9e3b-47efb2483281.png)

**Comment by mohierf** [comment]
Event with some buttons, but ...
![image](https://cloud.githubusercontent.com/assets/2932687/8223713/eaf20dfc-157b-11e5-9027-ec459f959d86.png)


At end, I found the image only version to be the best solution

**Comment by mohierf** [comment]
Forgot this version ... with simple buttons.
![image](https://cloud.githubusercontent.com/assets/2932687/8223771/7eb2eb7e-157c-11e5-8402-f3aa12357358.png)

**Comment by maethor** [comment]
When we find an icon, the label is not useful anymore, so there is no need to print it. But when we don't find the icon, maybe we should print label he instead of a generic icon label.

**Comment by mohierf** [comment]
Why not ... I will try this solution
