### ISSUE TITLE
Mobile plugin

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#201]
The mobile plugin doesn't work at all. One of the goals of BS3 is to propose a responsive interface, so this plugin should not be usefull anymore. I think we should remove it.

What do you think @mohierf ?

**Comment by ddurieux** [comment]
+1 for remove it

**Comment by mohierf** [comment]
+1

**Comment by maethor** [comment]
@mohierf you can close this issue.

**Comment by mohierf** [comment]
You won :D

**Comment by maethor** [comment]
Fatality! :)
