### ISSUE TITLE
Problems view : count elements per business impact

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#205]
Should be nice to include number of elements in each Business impact ... using a badge ?

![image](https://cloud.githubusercontent.com/assets/2932687/8229627/f35f052a-15b8-11e5-86f5-61fb5abb3c6f.png)

**Comment by maethor** [comment]
Why not. It's quite simple, I can try it.

**Comment by maethor** [comment]
Hm… the number of elements… in the current page, or in all the items retrieved by the search ? :)

**Comment by mohierf** [comment]
In all the items ... should be more logical, no ?

**Comment by maethor** [comment]
Logical, yes, but right now it's not that simple :D

**Comment by maethor** [comment]
I need to rewrite the pagination system to make this work. For now I can submit a PR with the elements in the current page. They are not displayed in a badge (because it was ugly), but right aligned in the panel.

**Comment by maethor** [comment]
It has been added to my last PR : #207

**Comment by mohierf** [comment]
You may leave it for the moment ... I will have a look to store in the module or in the regenerator some global counters. May be we should then use : app.services.count_bi['important'] ...

**Comment by maethor** [comment]
This seems like an insult to the entire python philosophy, I can't use this, sorry :D

More seriously, the count should take the be done after the filters. I know how to do it, you can leave it to me. I'll do it next week.

**Comment by mohierf** [comment]
+1 for you ... philosophy and Shinken are not that friends :-)

I thought that when the regenerator receives updates from the scheduler, he may update counters for services OK, WARNING, ... and that we may use these counters without to be obliged to iterate throught lists to fetch the number of services that are OK ... not really philosophical, but efficient for the WebUI ?

**Comment by maethor** [comment]
Counting a list with `len()` is O(1). Basic filtering is O(n).

We talk about… what… maybe 500k elements maximum? I don't think we should care about optimizing O(n) functions. We'd better limit the number of function to avoid bugs and improve maintainability

**Comment by mohierf** [comment]
This is joining mathematics and philosophy ... I really do agree ! +1 for you :+1:

**Comment by mohierf** [comment]
![image](https://cloud.githubusercontent.com/assets/2932687/8275318/441327c0-18a3-11e5-8c7e-29a311f0e098.png)
