### ISSUE TITLE
Problems view : link to filtered view from synthesis panel

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#208]
![image](https://cloud.githubusercontent.com/assets/2932687/8236249/675e1596-15e7-11e5-9c7f-cfa6419607be.png)

From this panel, it should be interesting to link directly to a filtered view ... clicking on Warning services links to a filtered view showing services with a Warning state.

**Comment by maethor** [comment]
Yes, I was already planning to allow enabling and disabling filter by clicking on the icons. I should not be very difficult, but I want to rewrite the pagination first. Next week :)

**Comment by mohierf** [comment]
@maethor : You may have a look at #179 ... I used the synthesis and I linked the big icons to /all with appropriate filters

**Comment by maethor** [comment]
I'm sorry but I don't see how this is related to the current issue.

**Comment by mohierf** [comment]
Simply to add a link to icons :-)

**Comment by mohierf** [comment]
Same as #302 ... duplicate!
