### ISSUE TITLE
New ajax refresh breaks the element view refresh ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#209]
The new Ajax refresh currently breaks the element view refresh ...

**Comment by maethor** [comment]
Can you describe your problem a little more ? For me it's working perfectly.

**Comment by mohierf** [comment]
I noticed a problem when refreshing a tab in element view ... especially the graphs tab. I simply logged this issue to keep tracking the problem ...

**Comment by mohierf** [comment]
In fact, the page loaded javascript code is not executed after refresh. As of it, come elements are not properly updated, like popovers, event handlers, ... I am investigating

**Comment by maethor** [comment]
The JS need to be included in the page div to be reloaded too. See the end of `problems.tpl`.

**Comment by maethor** [comment]
Indeed, I see a bug. The tab following works before but not after refresh.

**Comment by mohierf** [comment]
Yes, that is right. I think I fixed this with my last commits ...

**Comment by maethor** [comment]
Nope. But I found a solution, PR coming soon.
