### ISSUE TITLE
Business impact : labels used for business impact levels

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#210]
Proposal for labels used for each business impact levels : 
- 0 : None
- 1 : Low
- 2 : Normal
- 3 : Important
- 4 : Very important
- 5 : Business critical

Inspired by thruk using 6 levels ... what do you think about it ?

Actually: 
- 0 : None
- 1 : Low
- 2 : Normal
- 3 : High
- 4 : Very important
- 5 : Top for business

**Comment by ddurieux** [comment]
Seems better, except perhaps rename 'normal' in 'medium'

**Comment by maethor** [comment]
Seems good to me. @ddurieux I prefer "Normal" than "Medium".

I think "None" should be "No-importance". But in fact I don't care :)

**Comment by mohierf** [comment]
+1 for normal!

I prefer None : "Business impact is none" ...

Except if you shout very loud, I close :-)
