### ISSUE TITLE
Bookmarks creation - common bookmarks

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#211]
When the current user creates a bookmark and he is an administrator, he may choose between common and user bookmark. Currently, only user bookmarks can be created ...

**Comment by maethor** [comment]
After creating the bookmark he can move it to the common bookmarks. This is inspired by the previous workflow for creating bookmarks.

**Comment by mohierf** [comment]
Previous workflow may need to be improved ... keep this issue opened and we
will see when using the bookmarks what should be more practical ?

2015-06-22 19:00 GMT+02:00 Guillaume Subiron <notifications@github.com>:

**Comment by maethor** [comment]
I agree.

**Comment by mohierf** [comment]
Current behaviour seems ok: create a user bookmark and then copy to common bookmarks.
