### ISSUE TITLE
Navigation bar - hosts / services state indication

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#212]
I simplified hosts . services states icons in the navigation bar ... a coloured percentage is enough ! Popover allows to have more details ...

![image](https://cloud.githubusercontent.com/assets/2932687/8272965/1d373690-1859-11e5-99c0-4b60d657e9e5.png)

![image](https://cloud.githubusercontent.com/assets/2932687/8272967/2a00e9fc-1859-11e5-866e-c60fed0b714d.png)

**Comment by maethor** [comment]
This is really nice!

But the popover width is not good on my install:

![2015-06-22-190224_1920x2100_scrot](https://cloud.githubusercontent.com/assets/2410576/8287634/502bfc76-1911-11e5-9003-a4494d543711.png)

**Comment by mohierf** [comment]
I noticed this also on my install this afternoon ... but I do not have this
problem anymore. Perharps something to be refined ... keep opened for this
issue.

2015-06-22 19:03 GMT+02:00 Guillaume Subiron <notifications@github.com>:

**Comment by maethor** [comment]
It's OK, I don't see the problem anymore. Probably a CSS cache problem.

**Comment by maethor** [comment]
Hm. I see this only on the /all module. Everywhere else I don't.

**Comment by mohierf** [comment]
We will try to fix this later, no ? When all the pages will be clean ...

**Comment by maethor** [comment]
This is fixed by my last commit.

**Comment by mohierf** [comment]
+1 for you !
