### ISSUE TITLE
Command modal disappears quickly

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#213]
When a modal command window is opened on element view, it disappears almost immediatly ...

**Comment by maethor** [comment]
Do you have an example? I don't see the problem when I click on "Add a comment"…

**Comment by mohierf** [comment]
Click on "Add a downtime" in element view ... I always have this problem.

2015-06-22 19:06 GMT+02:00 Guillaume Subiron <notifications@github.com>:

**Comment by maethor** [comment]
Ok, I see the same problem.

**Comment by mohierf** [comment]
I think I found a solution  ...
