### ISSUE TITLE
Command modal does not hide sidebar menu

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#214]
![image](https://cloud.githubusercontent.com/assets/2932687/8275587/e6cc7f34-18a8-11e5-8fbf-7cd6c2a1934e.png)

Probably a simple CSS tuning to be done ...

**Comment by maethor** [comment]
Yes, I saw that but I don't know how to fix it. I have the same problem on another website.

**Comment by mohierf** [comment]
I will have a look ... probably a bad z-index !
