### ISSUE TITLE
Element view - relooking ideas.

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#216]
First moke-up ...

Main ideas: 
- more compact interface
- remove vertical and horizontal tabs

![image](https://cloud.githubusercontent.com/assets/2932687/8299222/d40d81a4-1975-11e5-988b-335d1f4fe8d8.png)

**Comment by maethor** [comment]
This is *very* nice! Great idea!

**Comment by mohierf** [comment]
Host information : 

Hovering for check output / long output:
![image](https://cloud.githubusercontent.com/assets/2932687/8303961/3d0490ae-19a2-11e5-85ef-1dfdfdf322a2.png)



Hovering for check period (date/time sorted ...) :
![image](https://cloud.githubusercontent.com/assets/2932687/8303951/1fc76250-19a2-11e5-9aa5-9da842842ba7.png)

**Comment by mohierf** [comment]
Element overview: 
![image](https://cloud.githubusercontent.com/assets/2932687/8303997/7abdaf8e-19a2-11e5-98fa-dd4b4b0c7ac2.png)

**Comment by maethor** [comment]
Hm… What's the difference between output and long output?

**Comment by mohierf** [comment]
Not visible on my screen capture, but some checks output are formatted as is (from Nagios plugin specification):
``` 
A plugin optionally return multiple lines of both text output and perfdata, like such:

DISK OK - free space: / 3326 MB (56%); | /=2643MB;5948;5958;0;5968
/ 15272 MB (77%);
/boot 68 MB (69%);
/home 69357 MB (27%);
/var/log 819 MB (84%); | /boot=68MB;88;93;0;98
/home=69357MB;253404;253409;0;253414 
/var/log=818MB;970;975;0;980

If this plugin was used to perform a service check, the red portion of first line of output (left of the pipe separator) will be stored in the $SERVICEOUTPUT$ macro. The orange portions of the first and subsequent lines are concatenated (with spaces) are stored in the $SERVICEPERFDATA$ macro. The blue portions of the 2nd - 5th lines of output will be concatenated (with escaped newlines) and stored in $LONGSERVICEOUTPUT$ the macro.
```

**Comment by maethor** [comment]
OK, I didn't knew that. I mostly use NRPE, the output length is really limited.

**Comment by maethor** [comment]
I don't see this new view in BS3. Are you working in a dedicated branch?

**Comment by mohierf** [comment]
I did not yet commited anything on this new view ... it is still quite unstable and buggy :/P

I am currently trying to improve tab management to avoid the scrolling effect and to keep staying on the same tab when refreshing the page.

**Comment by maethor** [comment]
OK :)
