### ISSUE TITLE
Host/service maintenance_period : what to do with it ?

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#217]
Shinken allows to define a maintenance period for an host/service : http://shinken.readthedocs.org/en/latest/08_configobjects/host.html

Currently, the WebUI displays this maintenance period (if it exists ...) near the check period.

**Comment by maethor** [comment]
Is anybody using this feature?

How does it work? Does it really schedule a downtime period?

**Comment by mohierf** [comment]
I opened this issue for discussing about it ... if someone is using this feature, he will comment :-)

Indeed this feature allows to configure a specific period of time that is known as an exclusion for he check period ... as far as I understand. Perharps that @naparuba may explain more about it ? 

 Is there an interest to schedule such a period from the WebUI ? Not sure about that ...

**Comment by mohierf** [comment]
Currently, WebUI displays this timeperiod if it is defined for an host/service ... and that is enough for the moment.
