### ISSUE TITLE
History tab not showing any logs.

### ISSUE THREAD

**Issue by tarak666** [shinken-monitoring/mod-webui#223]
We are using shinken2.2 with BS3 webui, But I am unable to see History in History tab,

Error: Sorry, I cannot load the service history!

Thanks,
HTR

**Comment by mohierf** [comment]
Same as #73 ... did you try all we already discussed in #73 ? I suppose so ...

**Comment by mohierf** [comment]
I propose to you to make a test to provide some more information.

If you are easy with development mode in your browser ... hit F12 and then try to catch a network URL that is formatted as is : *'http://shinken:7767/logs/inner/host/service'* where host and service are the host/service for which you want to get the history.

 Once catched, please copy the request response ...

**Comment by tarak666** [comment]
Yes i have tried all as we dicussed in#73.
This is the output when i use F12 .

<li class="history_pane active"><a class="link_to_tab active" href="#history" data-toggle="tab" id="tab_to_history" aria-expanded="true">History</a></li>

**Comment by mohierf** [comment]
You copied a capture of an HTML element, it is not a capture of network traffic ... 

 Indeed, the content of the history tab is requested using an Ajax request : *'http://shinken:7767/logs/inner/host/service'* where host and service are the host/service for which you want to get the history.

It is the response of this ajax request that I am interested in ... with F12, with Chrome, you have a *network* tab and you will see the requests in this tab:

![image](https://cloud.githubusercontent.com/assets/2932687/8335844/6d855aa2-1aa0-11e5-88e0-684db30220ec.png)

Then you click on the request (here it is Application) and you will see the response content : 
![image](https://cloud.githubusercontent.com/assets/2932687/8335856/87e55e38-1aa0-11e5-8e95-0a2333b49893.png)

**Comment by tarak666** [comment]
Yes, I can see url as you said, but it showing 404 error.

![1](https://cloud.githubusercontent.com/assets/3509727/8351237/69d78160-1b49-11e5-98fc-74ae740d9d43.PNG)

**Comment by mohierf** [comment]
Ok. I suppose that it may be because of the long service name you are using : **Check Mysql Count : No_...**. To confirm, should make the same test with a shorter and simple service name ?

**Comment by tarak666** [comment]
I tried with short service and host name, But no Luck.

http://10.0.0.2:7767/logs/inner/c01/Admin
Same 404 error.

**Comment by mohierf** [comment]
Ok, so is your mongodb really available on localhost:27017
