### ISSUE TITLE
Change custom variable do not change variable ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#224]
When changing a custom variable thanks to Web UI, an external command is sent to Shinken (`CHANGE_CUSTOM_HOST_VAR;sim-0001;_ENTITIESID;3`) but the value of the custom variable is not really changed!

When fetching the customs variables of the host, the value did not changed ! 

Probably a problem in Shinken that do not refresh the values after receiving the external command !

**Comment by maethor** [comment]
I believe this functionality has been removed. I'm closing this issue.
