### ISSUE TITLE
Hostgroups view, relooking ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#228]
New hostgroups view  : 

![image](https://cloud.githubusercontent.com/assets/2932687/8374706/f9a1b80c-1bf7-11e5-9ce6-b3cfcbd1a5d1.png)

Left side: 
- synthesis about hosts states
- group title includes business impact information
- group title navigates to the /all view filtered for the hostgroup
- detail state icon navigates to the /all view filtered for the hostgroup and for the host state

Right side:
- navigate to minemap filtered for the hostgroup 
- navigate up/down in the groups hierarchy if available
- badge information about number of hosts
- badge information about number of sub-groups

**Comment by maethor** [comment]
We are loosing the "dashboard" aspect of the previous view? I know some users like to have this view on a monitoring screen.

**Comment by mohierf** [comment]
You are right, but we there are a lot of groups (mine are > 1000) the "dashboard" view does not make any sense ...

I am moking-up a more synthetic view based on group level to view all the groups on one page :-)

**Comment by maethor** [comment]
For hostgroups it may not be relevant, but it may be for service groups, hosts tags, services tags, etc. Everyone have a different configuration. I only have ~30 groups, and I think the last view was great to have on overview.

I don't know how to find the right balance, so I'm open to your ideas :)

**Comment by mohierf** [comment]
I kept the last view on my testing environment and I am using as a basis for my moke-up :-)

**Comment by mohierf** [comment]
More synthetic groups view

![image](https://cloud.githubusercontent.com/assets/2932687/8381445/f3cbe054-1c2b-11e5-9e81-5ab835005b23.png)

Progress bar of all hosts

Synthesis view of all hosts 

For each hosts group:
- background color depending upon worst member hosts state
- hostgroup level information, navigates to a level filtered view ... should navigate to the parent group ?
- displays hosts member count and detail
- hosts group name and BI, navigates to a filtered hosts view

![image](https://cloud.githubusercontent.com/assets/2932687/8381430/e1ae1e46-1c2b-11e5-9ad1-c738244e6689.png)

**Comment by mohierf** [comment]
This dashboard view is available on : http://shinken:7767/hosts-groups-dashboard
