### ISSUE TITLE
Element view, graphs tab, loading indicator ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#233]
When graphs tab is selected there is a message indicating that graphs are not available, and then, once they are loaded they replace the alert message. 

It will be cleaner to replace this alert message by a loading indicator, and then display the alert message only if graphs are not available.

Moreover, each graph should have its loading indicator while loading ...

**Comment by maethor** [comment]
I have already done this in my company information system. I can make it work here.

**Comment by mohierf** [comment]
Up to you ...
