### ISSUE TITLE
Generic and configurable custom view

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#234]
When an host has a *custom_views* property, extra tab(s) is(are) added in the host element view. 
```
   custom_views                 host
```

Custom views are intended to be delivered by installed packs (linux-ssh, ...) but the WebUI may provide a generic and configurable custom view, as of it :

![image](https://cloud.githubusercontent.com/assets/2932687/8468024/697a4eec-2066-11e5-89a8-cd731c43b5de.png)

**Comment by mohierf** [comment]
Last improvements : 
- load indication
- several configuration for same host view

![image](https://cloud.githubusercontent.com/assets/2932687/8513632/8d976e94-2373-11e5-8011-5431c3e65129.png)


![image](https://cloud.githubusercontent.com/assets/2932687/8513623/857c3f46-2373-11e5-8e4f-f4334f791084.png)

**Comment by mohierf** [comment]
How-to:
- add the *custom_views* property to an host to activate the host custom view
- the required views are a comma separated list
- each element in the list may contain a */config* part to specify the configuration file to use

In this example:
```
   custom_views                 host,host/default2
```
two views are built:
- the first one uses the *default.cfg* configuration file 
- the second one uses the *default2.cfg* configuration file 

The configuration files are located in the *plugin/cv_host* directory.

**Comment by maethor** [comment]
I don't like the new service tree, because we are loosing too much vertical space so I have to scroll to see a tree that I was seeing in one sight before. I think the last view was really more readable.

**Comment by mohierf** [comment]
You are right ... it is a "standard" Bootstrap list and we may customize the CSS for this view ... I open an issue for his

**Comment by mohierf** [comment]
Added state icon near graphs:

![image](https://cloud.githubusercontent.com/assets/2932687/8545000/9ba830bc-24aa-11e5-85de-c8aa4d58d721.png)

Rotate X-axis label if more than 5 bars in the barchart: 

![image](https://cloud.githubusercontent.com/assets/2932687/8545009/b50dac94-24aa-11e5-908a-ff53c9602afa.png)

**Comment by maethor** [comment]
Nice. May I ask what memory and network plugins are you using?

**Comment by mohierf** [comment]
My *wheezy* host is a virtual box Debian Wheezy and I am using the linux-ssh Shinken pack ... I simply did `shinken install linux-ssh` and added a tag `linux-ssh`on my host

**Comment by maethor** [comment]
OK. I don't use this pack, I'll take a look.

**Comment by mohierf** [comment]
This pack is not complete ... I simply use it on my test VM. Else, I am using NRPE for my servers and specific checks for passive checking ...
