### ISSUE TITLE
Dashboard hosts/services groups view

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#237]
As proposed in #228:

![image](https://cloud.githubusercontent.com/assets/2932687/8482063/5a148108-20e7-11e5-8fd5-df124774bb03.png)

**Comment by maethor** [comment]
This seems very nice.

**Comment by mohierf** [comment]
Still some improvements needed (tested on my production env): 
- [ ] sort by impact ... worst state first
- [ ] nicer layout

**Comment by mohierf** [comment]
As of #636, switch is possible between this view and the normal group sview
