### ISSUE TITLE
Filtering - include contacts

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#238]
Should be able to filter with contacts: 
- [ ] **ctag** to filter with contacts tags (`use` property)
- [ ] **cg** to filter with contacts groups

**Comment by maethor** [comment]
There are many methods missing in Shinken core to do this properly. I can insist, it's quite fun, but it will be ugly. Is it an important feature for you?

**Comment by mohierf** [comment]
No, it is not important. Feel free to leave this ...

It is much more important to build a consistent data manager as discussed in #178 ... and then it will probably be easier to manage contacts.
