### ISSUE TITLE
Problems view : action buttons bar on top of view

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#241]
When selecting a problem in problems view, the action buttons bar appears on top of the problems view even if the selected problem is far from page top ...

![image](https://cloud.githubusercontent.com/assets/2932687/8483144/f77db192-20ee-11e5-9b49-36aa3c712295.png)

**... two pages down ...**

![image](https://cloud.githubusercontent.com/assets/2932687/8483151/0d412d7e-20ef-11e5-9633-3190cd8f4d53.png)

The user does not even see that this buttons bar appeared on the page !

**Comment by mohierf** [comment]
Build an action bar in a fixed bar built inside the layout ...

**Comment by mohierf** [comment]
Actions bar when on problems view:

![image](https://cloud.githubusercontent.com/assets/2932687/8511180/4a384568-230c-11e5-8b13-df902f884fe6.png)


Actions bar when on element view: 
![image](https://cloud.githubusercontent.com/assets/2932687/8511181/60577684-230c-11e5-9ae9-d74737cd8763.png)

**Comment by maethor** [comment]
This is awesome. Thanks.

**Comment by mohierf** [comment]
You are welcome ...

I used it all day and it is really comfortable !
