### ISSUE TITLE
Problems view - sort problems by duration

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#243]
Currently, problems are sorted and grouped by **business priority** and then by **hostname**, **service description** ... may be interesting to sort by problems duration ?

**Comment by maethor** [comment]
After *business priority* and before *hostname* and *service description*, they are sorted by status (critical, warning, etc.).

It's a good idea. Ideally, the user should be able to sort by any column. But it's not simple.

**Comment by mohierf** [comment]
Abandoned

**Comment by jesseorr** [comment]
Is this still a complicated addition? Our company is moving away from multiple Nagios installations to Shinken, and has been working towards the migration slowly over the last year and the biggest pain point we've seen thus far is the ability for technicians to sort by duration of the alert.

**Comment by mohierf** [comment]
I will try to have a look at this feature in the next weeks ...

**Comment by jesseorr** [comment]
Thank you, I was amazed by how many of our technicians noted this ability as a problem once Shinken was starting to be rolled out as an open-beta within our company.

**Comment by adiospeds** [comment]
Shinken was a very helpful tool until we figured it was not possible to sort alerts based on duration. Is there a plan to include this feature anytime soon - if not we may have to move on for now

**Comment by mohierf** [comment]
Sorry but please read this: https://github.com/shinken-monitoring/mod-webui#important-information
