### ISSUE TITLE
Documenting cv_host

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#246]
@mohierf I'm testing the cv_host plugin. What is the best way to configure it ? I can't modify default.cfg because it will be modify at the next commit. Can I make a "config.cfg" to overwrite the configuration ?

Thanks.

**Comment by david-guenault** [comment]
what about branching and merge when you are ready ?

**Comment by maethor** [comment]
The idea of this plugin is to be configurable by every user. I don't intend to push my configuration ;)

**Comment by mohierf** [comment]
@maethor : you are right, the default configuration file is *default.cfg* ... we should first try to get this file in the share directory of WebUI and then, if not found, in the cv_host plugin directory ? More interesting, we may use the first host tag (if exists ...) as the configuration file name ?

**Comment by mohierf** [comment]
@david-guenault : we defined a milestone to merge BS3 branch in the master branch and publish a new WebUI version

**Comment by maethor** [comment]
I don't know @mohierf. In fact I can't make the plugin works. I don't know how to configure the default.cfg.

**Comment by mohierf** [comment]
The plugin tries to find some services for the host : cpu, memory, disks, ...

The rule to find a service/metrics is that the service description must match the regexp defined in the plugin.cfg file and the metrics name must match the regexp defined with the right unit of measure (uom). This is for cpu, memory, disks and network ...

With the following configuration, we try to find a service description that contains *cpu* or *CPU* in its description. Then we extract the metrics that contains *cpu_all_idle* or *cpu_all_iowait* or ... and for which uom is *%* (leave empty if you do not care.

```
svc_cpu_name=cpu|CPU
svc_cpu_used=^cpu_all_idle|cpu_all_iowait|cpu_all_usr|cpu_all_nice
svc_cpu_uom=^%$
```

**Comment by mohierf** [comment]
@maethor: More info in #234 ...
