### ISSUE TITLE
Service tree should be collapsed in by defaut

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#247]
In the service tree, I think the "branches" that are completely OK should be collapsed to let the user see directly what is important. This is obvious when we see a database (oracle, postgres, mysql…).

**Comment by mohierf** [comment]
In the host custom view, all the tree branches are expanded ... the idea was to have a quick look at all the services. In the impacts tab, the OK branches are collapsed to focus on problems.

**Comment by maethor** [comment]
Ok, I understand. In theory I agree, but it's a problem when the host inherit the mysql, postgres or oracle packs, because they contain *many* hosts.

Maybe we could collapse the branch if it matches "mysql", "postgres" or "oracle" ?

**Comment by mohierf** [comment]
These packs contain many hosts ? You mean many services, no ?

You are right, we should collapse if the branch contains many services ...

**Comment by maethor** [comment]
Many services, yes.

**Comment by mohierf** [comment]
Last commit proposes a behavior based on two parameters: 
- **expanded** (True/False)
- **max_sons** (integer)

If tree branch state is not Ok, the branch will be expanded.

If tree branch state is not Ok, the branch will be collapsed if **expanded** is False or if the number of elements in the branch is >= **max_sons**
