### ISSUE TITLE
Sidebar menu activation mark

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#248]
When on system parameters page, the sidebar menu activation marks are not properly displayed because configuration and status are activated.

![image](https://cloud.githubusercontent.com/assets/2932687/8510799/7d17ecc4-22fb-11e5-8f6f-ecd40b6cd3f1.png)

**Comment by maethor** [comment]
We have the same problem in the element page.

**Comment by mohierf** [comment]
A screen capture to illustrate ? I do not see any problem ...

**Comment by mohierf** [comment]
I got it !

It is because of the refresh strategy that we modified recently ... it is realy complicated up to now to define what is loaded on document load and what is to be loaded on page refresh ... as of it some events are no more bound to HTML elements !!!

I think we need to refactor page refresh ... I will have a look on it.

I reopen to keep tracking about this problem ...

**Comment by maethor** [comment]
@mohierf this is the last issue remaining to close the 2.0 milestone ;)

**Comment by maethor** [comment]
I can't reproduce it anymore. @mohierf is it fixed for you too ?

**Comment by mohierf** [comment]
Seems to be fixed ...
