### ISSUE TITLE
Impacts view: relooking

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#249]
![image](https://cloud.githubusercontent.com/assets/2932687/8512944/73694544-2358-11e5-8bcf-7261e022324f.png)

**Comment by maethor** [comment]
This is so nice. I can't wait to tomorrow to try it :)

**Comment by maethor** [comment]
Ok, I still don't like this view, but at least it doesn't take 5 seconds and half of my RAM to load. Thank you @mohierf :)
