### ISSUE TITLE
Fallback to cv_host when a declared custom view does not exist

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#252]
When installing some packs, and tagging hosts, the configuration inherits from custom views that should be available ... what a wonderful world!

In fact, some packs do forget to install the declared custom views (eg. linux-ssh declares 3 custom views that do not exist anywhere ...).

The Web UI should try to call the new generic host custom view with a configuration named from the original failing view. When the **linux-ssh** view fails with 404 error, we may try to call the host view as if we declared **host/linux-ssh** in the host configuration

**Comment by mohierf** [comment]
This host has two known custom views (*host* and *host/default2*) and a missing *test* custom view ... instead of the missing view the WebUI builds an *host/replace* view and tries to make something with the metrics collected by the standard checks (cpu, memory, ...).

 Result is not that bad :-)

![image](https://cloud.githubusercontent.com/assets/2932687/8531891/bf7ae3ac-242a-11e5-8347-2ae7597d5c99.png)

**Comment by maethor** [comment]
I agree, this is great.

**Comment by mohierf** [comment]
Implemented
