### ISSUE TITLE
Element view - commands tab should be removed ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#253]
... because it now contains only toggle commands. These toggles should be dispatched near their own properties ...

**Comment by mohierf** [comment]
Toggle commands are integrated near their attached parameters: 
![image](https://cloud.githubusercontent.com/assets/2932687/8533035/7ec1556e-2432-11e5-92a7-7b966c267720.png)

**Comment by maethor** [comment]
I completely agree.
