### ISSUE TITLE
Actions panel doesn't show up after refresh

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#259]
In the problem view, after a refresh the actions panel doesn't show up when we select elements.

**Comment by maethor** [comment]
After refresh, the action buttons on each host doesn't seems to work neither. This was working after I implemented the new refresh.

**Comment by mohierf** [comment]
As I explained in another issue, the whole page refresh system is a bit messy ... because some events are not anymore bound after page refresh ... I am currently looking at it and it is not that easy to cope with:/P

**Comment by maethor** [comment]
I don't think it is so hard to solve. Each page should bring it's JS at the end of the page, or at least an `on_page_refresh()` command like at the bottom of problems.tpl. This JS is called by the brower when the page is reloaded.  All the event must be bound in this function.

**Comment by mohierf** [comment]
It is not that easy ... :-)

On first load, the events bound in *on_page_refresh* are not all bound correctly because all the elements are not yet created in the DOM ... so you must also call *on_page_refresh* when the document is ready and it may create several bindings on the same element!

This is what I am testing at the moment ...

**Comment by mohierf** [comment]
Forget the previous comment ... I confused my brain with too many concurrent tests!

**Comment by mohierf** [comment]
As a conclusion:
- all the plugins template concerned with refresh must propose an *on_page_refresh* function
- this function must be called in a script included in the template
- all events must be bound in this function
- this function must **never** be called on document load!
