### ISSUE TITLE
Host availability tab in element view

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#260]
The availability tab displays daily host/service availability information computed from data gathered from an *availability* collection stored in a mongodb.

The module *mongo-logs*, in its most recent version, computes and stores daily availability data for all hosts in the Shinken configuration ... see https://github.com/shinken-monitoring/mod-mongo-logs/issues/1.

![image](https://cloud.githubusercontent.com/assets/2932687/8586564/5741964c-25f0-11e5-916f-a3fcdec363d4.png)

**Comment by mohierf** [comment]
Availability information for all hosts on one page in the *system/availability* menu.

![image](https://cloud.githubusercontent.com/assets/2932687/8587038/f40f4cd4-25f6-11e5-97a7-359ac26cac3a.png)

**Comment by maethor** [comment]
This is *so* awesome. Thank you @mohierf. I can't wait to try it.

**Comment by maethor** [comment]
@mohierf What do the first and second bars represent ?

**Comment by maethor** [comment]
Hm… I suppose the first bar is based on the day. And the second bar is the same as the first but minus the "unchecked" ?

So now it's 11:34, I have the first bar 47%UP / 53% UNCHECKED, and the second bar 100%UP.

Am I right ?

**Comment by mohierf** [comment]
You are right !

The first bar is a 24 hours bar

The second bar is only considering the CHECKED period in the day.

I should have cross referenced this : https://github.com/shinken-monitoring/mod-mongo-logs/issues/1

**Comment by maethor** [comment]
Ok, I'm starting to see the whole picture.

UI speaking, I think there are some improvements to do to make it more clear. For instance, we don't care so much about the uncheck time. The second bar is enought, we just need to display somewhere "based on X% of the day", or something like that.

Also, we could simply aggregate theses informations to display monthly and yearly availability.

I'll work on this today. There is so much thing we can to with this information.

**Comment by mohierf** [comment]
You are right ... I simply made a moke-up to validate !
