### ISSUE TITLE
Filtering should search in check output

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#261]
It will allow to search in problems view on: 
- host name
- service description
- check output

**Comment by maethor** [comment]
This is a good idea. But I think if we find some results on the host names and service description, we should'nt be looking in check outputs. What do you think?

I have performance issues in mind. I'm not sure about that, but I think regexp are quite time consuming, so making a full text search on all the elements, twice, may not be a good idea when most of the time we just want to get a host by it's name.
