### ISSUE TITLE
Some sidebar items are inaccessible on small screens

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#263]
On small screens, the sidebar can't be displayed completely. Most of the time it's not a problem because we can scroll to display the last elements. But when the content is not high enought, we can't scroll enougth to display the last elements of the sidebar.

**Comment by mohierf** [comment]
Perharps a screen capture may help to understand ...

**Comment by maethor** [comment]
I have to admit that it's a tricky case. It only happen when the action menu is displayed.

![2015-07-14-195943_1600x900_scrot](https://cloud.githubusercontent.com/assets/2410576/8680667/27598d14-2a63-11e5-8ff3-39c81204c1ae.png)

**Comment by mohierf** [comment]
We should reduce height of the menu elements depending upon viewport height ?

**Comment by maethor** [comment]
I don't know.
