### ISSUE TITLE
Popovers are not always user friendly ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#265]
On Firefox it seems that the popover do not _pop over_ ... :/P

Moreover, on mobile devices it may be quite difficult to hover an element to display an information box ... should be more interesting to activate the popover boxes when the element is clicked rather then hovered.

**Comment by maethor** [comment]
Which popover are you talking about ? The perfdata ? It works well on my Firefox (I don't use chrome, I only test in FF).

On mobile we don't display the perfdata, the screen is too small.

**Comment by maethor** [comment]
Moreover, clicking is less intuitive. The user can miss to discover the functionality.

**Comment by mohierf** [comment]
The popover in the element view .... for the element notes. Should you make a test with FF ?

**Comment by maethor** [comment]
We don't have notes on our hosts and services…

**Comment by mohierf** [comment]
Pop over may be refactored because they are not "mobile device friendly" ...

**Comment by maethor** [comment]
Instead of refactoring, I think we should just disable the popovers on small screens…

**Comment by mohierf** [comment]
Or replace popover with simple popup ...

**Comment by maethor** [comment]
Or not :D

First because popover opens on the side of the element, and not on the middle of the page. It's easy to see which element is the source of the popover.

Secondly because popover can be closed more easily than popups. They are more fit to display only a complement of information (like a graph).

**Comment by mohierf** [comment]
Whatever their name, popover or popup, we should keep the same feature but not only available when hovering an element ...
