### ISSUE TITLE
Availability logs should be filtered related to currently logged in user

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#273]
... as in the title !

Actually, displayed logs are not filtered ... as of it, the logged in user may see logs that do not concern him!

**Comment by mohierf** [comment]
@maethor : should you take care of this?

**Comment by maethor** [comment]
OK.

**Comment by maethor** [comment]
In fact, logs should'nt be displayed to common users, only to admin. I just fixed it (will be pushed soon).

But availability should be filtered, of course.
