### ISSUE TITLE
Shinken 1.* with new WebUI - please vote!

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#276]
I have tested the new WebUI on Shinken 1.2. As expected, it doesn't work. I didn't try to push it.

@mohierf do you think it would be a huge work to make it compatible? I don't know if this is useful, let me know what you think about it.

**Comment by mohierf** [comment]
Currently, I do not really know if it would be a huge work ... and I do not know if there are still many Shinken 1.* users ?

**If somebody still uses this Shinken version, please comment this issue**

**Comment by maethor** [comment]
I do, that's why I'm asking the question :D

**Comment by Simage** [comment]
@maethor is there any particular reason for you not to upgrade? I thought I had upgraded late 6 weeks or so ago :)

I'm not aware of any "missing" or dropped features in 2 and other than a couple gotchas it was a fairly painless migration for my install

**Comment by maethor** [comment]
The upgrade takes some time to adjust the configuration, and I don't have this time for this project.

**Comment by Simage** [comment]
Fair enough @maethor, I put mine off for quite a while for that reason as well

**Comment by maethor** [comment]
So I think the response is "no". Closing.
