### ISSUE TITLE
Color themes ?

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-webui#286]
Your work is very great... and the the new features are very useful.
But... 
I have a little problem with the colors of the actual theme,  it's too bright for me.
How to modify it by myself ? Or do you plan to add color themes ?

thanks!

**Comment by maethor** [comment]
Thank's for your comment!

We don't plan to add color themes. We prefer focusing on one theme and do it great :)

If it is too bright for you, so is github too bright also? And google? Wikipedia? etc. What would you change? Only the sidebar and topbar? Or even the main section background?

You can modify the theme by loading a custom css in `module/views/layout.tpl`. But if you are not used to git merges it could be erased at the next update. Sadly, this is the only solution I see for now.

Thanks again for your comment, don't hesitate to post more ;)

**Comment by b-keller** [comment]
Thanks for the answer, yes I would only change the top and side bar... 
With your guidance I will try to change the CSS...

You can close if you want.

Thanks

**Comment by maethor** [comment]
OK, thanks. I'll keep your idea in mind.
