### ISSUE TITLE
Empty history leads to error 500

### ISSUE THREAD

**Issue by rdoursenaud** [shinken-monitoring/mod-webui#288]
When the history is empty, the history tab displays a 500 HTTP error.
I think we're trying to use an uninitialized list.
![capture d ecran de 2015-08-04 20-20-12](https://cloud.githubusercontent.com/assets/1210367/9068878/40da6842-3ae6-11e5-9be0-f6ad2399e49f.png)

**Comment by maethor** [comment]
Mongo-logs is actually a module in active development that may not be usable in production. It is also very very slow. But you are right, thanks for this issue. I'll fix it.

**Comment by fhoubart** [comment]
Hi,
I got this same issue, and had a very simple workaround in the template. Instead of getting an empty list, the template work on a no iterable object. Checking it the object is iterable in the template fix the issue.
I've just posted a pull request for that: #291

**Comment by maethor** [comment]
@rdoursenaud can you confirm this bug is closed?

**Comment by rdoursenaud** [comment]
@maethor fix confirmed

**Comment by rdoursenaud** [comment]
Thanks @fhoubart
