### ISSUE TITLE
Graph Widget - Change fontsize in the graph

### ISSUE THREAD

**Issue by monito-git** [shinken-monitoring/mod-webui#295]
Hello,

I try to improve the Graph Widget but I don't know how. 
There is a display bug because of a font size witch is always at 18. Sometimes is good but other times it's not relevant (with 365d mode): 
![image](https://cloud.githubusercontent.com/assets/13745844/9274084/bec659f6-4292-11e5-9047-3efad72f9604.png)

This is the Url of the graph : 
```
/graph?url=http%3A//192.168.1.40%3A8080/render/%3Fwidth%3D586%26height%3D308%26lineMode%3Dconnected%26from%3D14%3A40_20140814%26until%3D14%3A40_20150814%26yMin%3D0%26yMax%3D100%26target%3Ddhcp.Dhcp_pool.Scope_Usage_192_168_1.0%26target%3Ddhcp.Dhcp_pool.Scope_Usage_192_168_1.0%3F%3F%3F%3F%3F%26fontSize%3D18
```

How modify the args generate by the webui ?
Exemple : remove or reduce fontSize

**Comment by maethor** [comment]
It's more a graphite-ui bug than a graph widget one. I use PNP4Nagios and I don't have this problem.

Maybe @mohierf will be able to help, but the problem is not on the webui side.

**Comment by monito-git** [comment]
Yes you are right @maethor ! I searched in the ui-graphite code and I found this : 
```
    def get_graph_uris(self, elt, graphstart, graphend, source = 'detail'):
        # Ugly to hard-code such values. But where else should I put them ?
        fontsize={ 'detail': '8', 'dashboard': '18'}
```

Instead of 18 I put 14.
I think graphite-ui is not disigned for the last webui versions.

You can close this issue (I don't know how close my issue )

**Comment by mohierf** [comment]
@monito-git : you should try to use the ui-graphite module that is in the `refactored` branch (https://github.com/shinken-monitoring/mod-ui-graphite/tree/refactored). 

 With this version, you will have a better integration with the WebUI and you can even change some parameters in the cfg file of the module ...

**Comment by monito-git** [comment]
Ok, thanks you for your advice @mohierf !
