### ISSUE TITLE
services and hosts tags overview are empty

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-webui#297]
Hi,

I don't understand why these overview are empty whereas the host config file use : generic-host,windows...
I miss some thing ?

thanks

**Comment by maethor** [comment]
`generic-host` is not a tag, it's a template. I suppose windows is also a template…

**Comment by b-keller** [comment]
ok , can you explain how to use the tags (example)? I've searched but found nothing in the doc... 

thanks

**Comment by maethor** [comment]
As a matter of fact I can't… because I don't use them and I can't see how they could be useful. Maybe @mohierf will be able to help you.

**Comment by mohierf** [comment]
Indeed, @b-keller you are right. There has been a bug introduced in the tags management ... I will push a fix for this soon (in testing currently ...).
