### ISSUE TITLE
Availability overview HS

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-webui#298]
With the last commits, Availlability overview not working anymore.

Error: 404 Not Found
Sorry, the requested URL 'http://XXX.XXX.XXX.XXX:7767/availability' caused an error:
Not found: '/availability'

**Comment by maethor** [comment]
Works fine for me. Did you install all the python packages listed in `requirements.txt`? I added `arrow` a couple of days ago.

Can you try https://XXX.XXX.XXX.XXX:7767/host/hostname#availability? (replacing "hostname" by a real host name)

**Comment by b-keller** [comment]
Yes, I install arrow and now it's working perfectly

Sorry et thanks
