### ISSUE TITLE
Problem with user login - too many redirections

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#299]
Sometimes, when returning in the Web browser, the Web UI do not load the page and displays an error page indicating that there are too many redfirections : 

![image](https://cloud.githubusercontent.com/assets/2932687/9438989/1c0ab468-4a63-11e5-887a-38c0b1bd5ea8.png)

**Fix**: This problem disappears after clearing the user cookie stored in the Web browser.

**Comment by maethor** [comment]
I never had this problem.

The only time when I see this error is after restarting the broker, when the objects are not loaded yet. So I think it could be an authentication problem. Finding why there is a redirection loop may allow us to see the true error… ?

**Comment by mohierf** [comment]
I will try to make some more tests because I had this problem several times ... and it is always on a virtual machine ... I opened this issue if someone else also met the same problem.

**Comment by mohierf** [comment]
Problem occured because my test VM IP address changed :/P
