### ISSUE TITLE
custom view

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-webui#304]
Hi,
I have this message on the host overview when I use linux snmp or linux ssh pack : 
 ``` Sorry, I cannot load the linux/default view! ```
```Sorry, I cannot load the linux_ssh_memory/default view!```
and for these hosts I have no  : Graphs, Impact graph, History, Availability.
But for hosts that not use a custom view, all overviews are ok (graphs, logs...)

**Comment by mohierf** [comment]
I just saw this issue and I will have a look at it today ... keep in touch!

**Comment by mohierf** [comment]
@b-keller : as you may know, each installed pack may provide its own WebUI custom view for an element. The host template in the pack contains a `custom_views`property declaring which views are to be displayed byt the WebUI (eg. `custom_views                 +linux_ssh,linux_ssh_memory,linux_ssh_processes` for linux-ssh).

Unfortunately, the `linux-ssh` (or `linux-snmp`) packs do not provide any custom view (I already asked to the maintainer but those views do not exist ...). 

As of it, the WebUI do not find the required view when it tries to display the `linux-ssh` (or `linux_ssh_memory`, or `linux_ssh_processes`) custom view. It then briefly displays a message as the one you mentioned, and then it should use the default custom view to try and display something like this : 
![image](https://cloud.githubusercontent.com/assets/2932687/9604020/00c3e92e-50b5-11e5-8289-e5a1565ff825.png)

As I understand your problem, you do not have anything displayed in the custom views tabs and some more tabs are not functioning properly? 

I am suspecting a Javascript problem ... 

1/ should you have a look in your Web browser console when you are loading your element view page and copy the content in this issue.

2/ the `eltdetail.js`and `custom_views.js`files located in *plugins/eltdetail/htdocs/js* directory allow to activate some debug logs in the browser console. At the very beginning of the file you will find a line like: 
```
var eltdetail_logs=false;
```` 
Please replace false with true, reload the page and copy the content of the console in this issue.

Thanks

**Comment by b-keller** [comment]
I retest just now, and I don't have the problem anymore... cache problem ?

now I see the message ```Sorry, I cannot load the linux/default view!``` 1 second and the default view is loading.

This is the js trace
 ```
    Request for loading custom view:  linux  for  GLPI , configuration:  default custom_views.js:32:21
    GET XHR http://XXX.XXX.XXX.XXX:7767/cv/linux/GLPI/default [HTTP/1.1 404 Not Found 67ms]
    Required view is not available. Trying default view ... custom_views.js:50:24
    Loaded custom view:  linux_default custom_views.js:78:27
 ```

**Comment by mohierf** [comment]
Ok. So everything is ok. Certainly a browser cache problem ...
