### ISSUE TITLE
bookmarks

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-webui#305]
Hi,

I have no luck with the bookmarks...I can't use it : the screen is greyed out when i want to add or to manage. I can't do anything. I test it with sqlitedb and mogodb : same problem.

![bookmark0](https://cloud.githubusercontent.com/assets/12746104/9590353/52dedd9e-5034-11e5-836f-cc850616d85f.PNG)

![bookmark1](https://cloud.githubusercontent.com/assets/12746104/9590358/5d57c952-5034-11e5-88bf-3ffa79858d78.PNG)

![bookmark2](https://cloud.githubusercontent.com/assets/12746104/9590373/6e2c5afe-5034-11e5-867d-6ee623f4972f.PNG)

**Comment by maethor** [comment]
I confirm the bug, thank's for reporting it. I will fix it soon.

**Comment by maethor** [comment]
@mohierf we have to fix this before releasing.

**Comment by mohierf** [comment]
I do confirm! And yes we must fix before releasing ...

**Comment by maethor** [comment]
I fix the modal problem. But Manage Bookmarks is still empty. This is a completely different but, and I don't know how to debug this. I think at some point we have accidently remove the code which populates the `bookmarks` and `bookmarksro` divs.

@mohierf do you have some time to take a look?

**Comment by mohierf** [comment]
I will have a look today ...

**Comment by mohierf** [comment]
New manage bookmarks modal: 
![image](https://cloud.githubusercontent.com/assets/2932687/9638363/a956d398-51a6-11e5-83ab-9b6dcfbcabe1.png)


Commit coming soon ...

**Comment by maethor** [comment]
I love your teasers @mohierf :D

**Comment by mohierf** [comment]
;-)
