### ISSUE TITLE
service graph widgets

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-webui#306]
Hi, 
Is there a way to add a service graph in a widget on the dashboard  ?

thanks

**Comment by maethor** [comment]
Yes it is. The WebUI will not assist you, but if you put the right element name you will get the graph. The element name is formed as this: `host_name/service_description`

For instance: `test-www01/Swap`

If `https://monitoring.domain.tld/service/test-www01/Swap#graphs` is showing the service's graph, the graph widget should be able to show it two.

Can you confirm it is working for you?

**Comment by mohierf** [comment]
I confirm that it works. We should open an issue to improve this widget to help selecting a specific service as it helps selecting an host ...

**Comment by b-keller** [comment]
Yes, it's working for me.

But some time I had a little display bug, when I have more than 1 graph widget, all graph is diplay in the same widget (service graph or host graph). And if I quit the dashboard and then return to it, all graph are show correctly...

**Comment by mohierf** [comment]
Concerning this display bug, I will try to have a look at it as I did this morning for the worldmap widget (#308) ...

**Comment by b-keller** [comment]
OK , thanks...

**Comment by mohierf** [comment]
Commit to come soon ...

![image](https://cloud.githubusercontent.com/assets/2932687/9600201/f289c6fa-5099-11e5-8d62-1f66f2d92618.png)

**Comment by mohierf** [comment]
@b-keller : you may have a look at: https://github.com/shinken-monitoring/mod-webui/commit/9a878f53f5732f46b115013000e809c0fb75f166
