### ISSUE TITLE
Dashboard tab on host view

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#307]
It could be nice to have a customizable dashboard (like the current dashboard) in each host view, or even service view… Or maybe just a way to have multiple dashboards. Kind of like what we can do with Grafana.

I'm not going to develop this right now, it's just an idea for a future milestone.

**Comment by mohierf** [comment]
+1 for me

**Comment by maethor** [comment]
Because we need to focus on other stuff, and this doesn't not seem important, I am closing this issue.
