### ISSUE TITLE
Worldmap widgets, sometimes map loading fails ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#309]
Noticed that after many dashboard, I sometimes got a javascript error : 
```
Uncaught TypeError: m[md].maps.Load is not a function
```

This error occurs in the *main.js* file, line 70

Seems to be due to several parallel Google maps loading ...

**Comment by mohierf** [comment]
This issue remains opened to keep tracking such problems with Google maps ...

**Comment by maethor** [comment]
Maybe we should use OSM instead of GMaps? It fits better our free software philosophy…

I never did such things, so I don't know if it would be a huge rewrite or not.

**Comment by mohierf** [comment]
I made some tests with OSM and you can actually use the OSM layout in the worldmap plugin. I did not investigate much on OSM markers and scripting but the idea is very interesting ... we may open an issue for a future milestone

**Comment by mohierf** [comment]
No more problem with most recent version 2.4.2
