### ISSUE TITLE
Graphite graphs size seems corrupted when proxying ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#310]
Please note the size of the graphs: 

![image](https://cloud.githubusercontent.com/assets/2932687/9600216/0cc1493a-509a-11e5-9758-0523e2ca6a1c.png)

After reloading the page, graphs are smaller : 
![image](https://cloud.githubusercontent.com/assets/2932687/9600227/23b65c8e-509a-11e5-99cf-c7aa96e3f251.png)

Probably a side effect of proxying graphs .... because the widget tries to adapt dynamcally the size of the graphs requested to Graphite :/P

**Comment by maethor** [comment]
I don't understand the link with proxying graphs.

**Comment by mohierf** [comment]
I never noticed this problem before you made this modification ... so I suppose it may be linked. Not sure about it, I am investigating what's happening ...

**Comment by maethor** [comment]
I don't know how ui-graphite is working. Can you give me the url of the image?

Proxy was not the only modification. If I remember correctly, I also added some with to limit the size of the image in the plugins.

**Comment by mohierf** [comment]
I found the problem! My bad ... you are clean @maethor ... sorry!

The graphs widget was faulty when resizing the images. 

I just commited a fix.

**Comment by mohierf** [comment]
One of the most recent modification war to use encoded URL ... where as `width=` became `width%3D`. As of it, no more matches for the regexp `/(width=).*?(&)/`used to find/replace size :/P
