### ISSUE TITLE
Improve services tab in element view

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#312]
It should be interesting to enrich the information in the *Services* tab of an host view: 
![image](https://cloud.githubusercontent.com/assets/2932687/9625073/24f0ce18-5153-11e5-882d-a68170c3180e.png)

For instance, adding information about the last check of each service

**Comment by maethor** [comment]
Keep it simple. If you want information, go to the problems view, or to the eltview of the service.
