### ISSUE TITLE
color metrics values

### ISSUE THREAD

**Issue by rom1701** [shinken-monitoring/mod-webui#313]
If a check give a lot of metric, and for each metric, i give min and max and warning value, it's possible, in the metrics view, to color only the metric if is not in the good rang? because, if the check return just warning, all metrics is on orange. i think is more simple to see why the check return a warning or critical alert.

**Comment by mohierf** [comment]
Nice idea :+1:

**Comment by maethor** [comment]
@mohierf do you think this is possible?

**Comment by mohierf** [comment]
@maethor : quite easy ... I will have a look ;-)

**Comment by mohierf** [comment]
I did not made any modification in current version and I got this: 
![image](https://cloud.githubusercontent.com/assets/2932687/9634762/7c695b3e-5193-11e5-9d68-a0e860560a9c.png)

Looking at the source code made me improve this feature (commit to come soon): 
![image](https://cloud.githubusercontent.com/assets/2932687/9635787/4f815680-5198-11e5-9fad-255bd2160bc6.png)


- limit text length in the progress bar
- display partial progress bar when UOM is %

**Comment by maethor** [comment]
When I developed this part, I remember having try this… but I can't remember why I didn't choose this option.

It's really nice. Thanks.

**Comment by mohierf** [comment]
I found and fixed several small bugs ... that made having always green state and 100% :/P

**Comment by rom1701** [comment]
very nice, but, it's possible to have the same in service view? for example, i have a check return a lot of values like toto1_edge=716Req/S;1983;;650;3420 toto2_edge=616Req/S;1883;;450;2420 .... so if my check return 1 or other, all metrics of metrics view in service view is orange or other color. it's maybe complicated but is not possible if the metric is not in the range min/max, colorize only this metric?

**Comment by mohierf** [comment]
Currently it is not possible. Host and service element views are using the same code ...

**Comment by maethor** [comment]
I will take a look

**Comment by mohierf** [comment]
Color used in the progress bar is set depending upon the service state (https://github.com/shinken-monitoring/mod-webui/blob/bs3/module/perfdata_guess.py#L203).
