### ISSUE TITLE
auth-htpasswd

### ISSUE THREAD

**Issue by rom1701** [shinken-monitoring/mod-webui#314]
I have with my apache configuration, in my root I have AuthType Basic, when I want to connect to shinken, i need enter my login and password for my apache authentification and for shinken. it's possible to shinken use the apache authentification to access?

**Comment by maethor** [comment]
Yes. You can use the auth-htpasswd module as documented here: https://github.com/shinken-monitoring/mod-webui/wiki/Installing-WebUI-authentication-modules

**Comment by rom1701** [comment]
Thank but if I use auth-htpasswd module, I need authenticate me in the shinken page. But if I have before a authentification with my apache serveur, is not possible to skip the shinken authentification? I don't know if it's possible, or it's already available with this module.

**Comment by mohierf** [comment]
You may have a look in the *modules/webui.cfg* file ... especially this section where you should uncomment `remote_user_variable`and one of the `remote_user_enable`: 
```
   #remote_user_enable        1
                              ; If WebUI is behind a web server which
                              ; has already authentified user, enable.

   #remote_user_enable        2
                              ; Look for remote user in the WSGI environment
                              ; instead of the HTTP header. This allows
                              ; for fastcgi (flup) and scgi (flupscgi)
                              ; integration, eg. with the apache modules.

   #remote_user_variable      X_Remote_User
                              ; Set to the HTTP header containing
                              ; the authentificated user s name, which
                              ; must be a Shinken contact.
```

I never used this feature for the WebUI but I suppose it will allow to bypass WebUI login process if you already authenticated an user and that his username is provided to the Shinken Web UI server.

**Comment by mohierf** [comment]
I just commited a `login.py`modification that adds some more logs if remote user authentication is used and logins failed. See https://github.com/shinken-monitoring/mod-webui/commit/0aae8e63f8eda53c9c0948312421a4fe2bdb9507

**Comment by rom1701** [comment]
OK thank, i need to investigate, because in apache HTTP header, I dont see the X_Remote_User. After, I dont know if it's normal but, if i uncomment the remote_user_enable and remote_user_variable, i dont see in the log the warning  remote user enabled but no user or other error. maybe if shinken dont see the X_Remote_User don't try to login. i dont know.

**Comment by mohierf** [comment]
In think that remote user configuration and embedded authentication modules do the job ... closing this issue. @rom1701 you may reopen if you still have problems ...
