### ISSUE TITLE
Impact graph

### ISSUE THREAD

**Issue by rom1701** [shinken-monitoring/mod-webui#315]
if you have a lot servers, and for example, all server depend of 1 machine, the impact graph is very big, you can not read any information and the browser (like firefox) become slow, and occasionally, can crash. it's possible to limit that?

**Comment by mohierf** [comment]
Currently, the impact graph is limited to a tree with a deepness of 3 levels from root. I will try a refactoring of this feature for the next version of WebUI

**Comment by maethor** [comment]
It is not just a deepness problem. The impact graph is the only thing that we don't touch when developing bs3 (because it's quite a complicated JS stuff). We should really plan to remake it entirely, maybe using recent JS libraries.

**Comment by rom1701** [comment]
yes i have 200 machines under my root branch, so it's just complicated to see the impact graph.

**Comment by mohierf** [comment]
Both of you are right ... it is not only a deepness problem nor a hosts number problem! 

I also noticed many other refinable stuff: 
- each node in the graph is an image
- very old and not optimized JS
- no filtering in Json built by Python
- ...

 I had a quick search to find a more modern libray than the one used (https://philogb.github.io/jit/docs.html) but did not yet found ... so, improvements are postponed to the next WebUI milestone.

**Comment by maethor** [comment]
The impact graph has been removed from the webui.
