### ISSUE TITLE
metrics values duplicated

### ISSUE THREAD

**Issue by rom1701** [shinken-monitoring/mod-webui#316]
the gauge is duplicated if i give Warning, Min, and Max value in the metric view.

**Comment by mohierf** [comment]
A screen copy will help understanding your problem ...

**Comment by rom1701** [comment]
![picture-metrics-duplicated](https://cloud.githubusercontent.com/assets/12527760/9657021/9563dc40-523d-11e5-9f89-82763b1030b4.png)

**Comment by mohierf** [comment]
Strange! I do not have this behaviour wether there is Min, Max, ...

Is it systematic for all the checks ? It seems not, because `bou2_middle`is not duplicated ...

**Comment by rom1701** [comment]
i was check, bdx1_edge is not duplicated in the print result of my check. i don't have this problem with thruk. I noticed, i have 2 diffenrent case, xxx_edge, and xxx_middle, only xxx_edge is duplicated

**Comment by mohierf** [comment]
Should you copy your full check output here ?

**Comment by rom1701** [comment]
Warning | bdx1_edge=1005.59333333333Req/S;2672.7378431347;;650;3420; reference_bdx1_edge=1069.09513725388Req/S;;;0; mrs1_edge=1000.47333333333Req/S;1050;;400;1050; reference_mrs1_edge=1032.12214763501Req/S;;;0; cbv4_edge=6044.05333333333Req/S;5240;;2200;5240; reference_cbv4_edge=6250.33841615455Req/S;;;0; sbg1_edge=744.123333333333Req/S;2063.63856883104;;350;2480; reference_sbg1_edge=825.455427532417Req/S;;;0; ren1_edge=578.656666666667Req/S;1270;;440;1270; reference_ren1_edge=625.606750734356Req/S;;;0; tls1_edge=965.48Req/S;1300;;550;1300; reference_tls1_edge=968.921335695412Req/S;;;0; par1_edge=5903.62666666667Req/S;4900;;2700;4900; reference_par1_edge=6118.34780270053Req/S;;;0; bou2_edge=6516.14333333333Req/S;5600;;2775;5600; reference_bou2_edge=6819.18995712407Req/S;;;0; lil1_edge=539.203333333333Req/S;850;;375;850; reference_lil1_edge=574.734936525936Req/S;;;0; bdx1_middle=235.936666666667Req/S;583;;66;583; reference_bdx1_middle=235.139977617742Req/S;;;0; cbv4_middle=437.4Req/S;373;;50;373; reference_cbv4_middle=457.181644606984Req/S;;;0; par1_middle=473.05Req/S;1000;;100;1000; reference_par1_middle=486.31497686944Req/S;;;0; bou2_middle=367.573333333333Req/S;948;;100;948; reference_bou2_middle=384.729599375661Req/S;;;0;

**Comment by mohierf** [comment]
26 metrics in the perfdata and do you have all the metrics in the metrics view ? I do not see any `reference_...`in the metrics view screen capture upper ... Should you copy your complete metrics view ?

I suspect Shinken perfdata analysis function to filter some of them :/P

**Comment by rom1701** [comment]
it's complicated to show you the full view, but i confirm, i have in the metrics view or other like graph, all metrics.

**Comment by mohierf** [comment]
I made a test right now with your perfdata ... and I get all the metrics with only one gauge per metric: 

![image](https://cloud.githubusercontent.com/assets/2932687/9683447/7d8e523e-5310-11e5-897b-5854539e3746.png)

**Comment by rom1701** [comment]
i dont know, but i have always this problem. Can i do something to help you or i close?

**Comment by mohierf** [comment]
This problem and the authentication problem make me think about a corrupted installation ... quite strange :/P

Which Shinken version are you using ? On which distribution ?

Is it possible to you to make a fresh install ?

**Comment by rom1701** [comment]
i think the same, i check my package. debian 7, last version of shinken.

**Comment by mohierf** [comment]
Debian 7, same as mine.
Last Shinken version: 2.4.1 or 2.4.0 ?

**Comment by rom1701** [comment]
2.4.1 with some patch for service description problem.

**Comment by rom1701** [comment]
i have this message:
Unknown command PROCESS_SVC_CHECK_RESULT

Sorry :(

**Comment by mohierf** [comment]
In your configuration parameters (menu Configuration / Parameters), do you have `check_external_commands` as True, and `passive_host_checks_enabled`and `passive_service_checks_enabled` ?

**Comment by rom1701** [comment]
all is True

**Comment by mohierf** [comment]
Ok. I see the problem ... it needs a fix in the WebUI. You may try with an host instead of a service ?

**Comment by rom1701** [comment]
do you want i try with your commit 286734d2e6a36bf0a7a9f513c588cf66368e3489, or is not important?

**Comment by mohierf** [comment]
If you install this commit you will be able to send a service check result ... if not, try an host check. As you prefer ...

**Comment by rom1701** [comment]
without your commit, in the host, it works, but i have nothing in the metrics view

**Comment by mohierf** [comment]
On my configuration, I have some metrics in the host element view ... are you sure you did not receive another host check result in the meantime ? Because it will erase the results you just posted with the submit check result UI ...

**Comment by rom1701** [comment]
i retry, i see the values in Information => Performance data, but in metrics view nothing.

**Comment by mohierf** [comment]
If your host is checked actively you will not have the information for a very long time ... you'd better disable active checks temporarily with the button in information page and then make the test again. I did it this morning on my testing conf and I had the perfdata in information tab and the metrics in metrics tab

**Comment by rom1701** [comment]
I have disable active checks with the button, but if in the host i add the check result, i have nothing in Performance data, and in service, it's the same. For information, i have integrate  286734d2e6a36bf0a7a9f513c588cf66368e3489

**Comment by rom1701** [comment]
i have disable active checks for an other service, and it's works
![picture-metrics-duplicated3](https://cloud.githubusercontent.com/assets/12527760/9712320/2c3b155c-554a-11e5-98a6-74a723b07d59.png)

**Comment by mohierf** [comment]
And your initial problem is still present ?

**Comment by rom1701** [comment]
in this screen , i don't have gauges, max, min values. And in my service where i have this metric automatically, i have always the duplicated gauges, only for the xxxx_edge metrics.

**Comment by rom1701** [comment]
after check webui, i see i don't have a good version of bottle, i have integer the version 0.12.8 and now i don't see the gauge for this service. I don't if the bad version of bottle can generate this problem but i have now a good version :)

**Comment by mohierf** [comment]
I do not think that Bottle may be involved in this ... :/P

I made a test this morning and I saw that if no graphs module is available in the WebUI the gauges are not displayed ... are you sure you configured such a module in `webui2.cfg` ?

On my testing environment (fresh Shinken 2.4.1, brand new Webui2, Graphite and UI-Graphite modules from refactored branch), I got this: 
![image](https://cloud.githubusercontent.com/assets/2932687/9782917/0c10b0d0-57a1-11e5-9162-136da966b7c6.png)


> Please note that host check lines are very new and will be published soon ...

**Comment by rom1701** [comment]
you are right, i have UI-graphite and graphite from refactored branch, but I didn't see my ui-graphite don't work's, i don't know why but i have this error in brokerd.log when i want see graph:

[1441875836] ERROR: [broker-shinken00] Error while generating graph uris 
Traceback (most recent call last): 
  File "/usr/share/pyshared/shinken/modules/ui-graphite/util.py", line 126, in get_graph_uris 
    return self._generate_graph_uris() 
  File "/usr/share/pyshared/shinken/modules/ui-graphite/util.py", line 163, in _generate_graph_uris 
    link=graph.url('composer'), 
  File "/usr/share/pyshared/shinken/modules/ui-graphite/graphite_utils.py", line 261, in url 
    if self.target_string: 
  File "/usr/share/pyshared/shinken/modules/ui-graphite/graphite_utils.py", line 194, in target_string 
    self._targets = '&'.join(['target=%s' % t for t in self.targets]) 
  File "/usr/share/pyshared/shinken/modules/ui-graphite/graphite_utils.py", line 87, in __str__ 
    s = str(self.target) 
  File "/usr/share/pyshared/shinken/modules/ui-graphite/graphite_utils.py", line 290, in __str__ 
    string = GraphiteMetric.join(*self.parts) 
  File "/usr/share/pyshared/shinken/modules/ui-graphite/graphite_utils.py", line 297, in join 
    return '.'.join([str(a) for a in args if a]) 
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 26: ordinal not in range(128) 

but in other check i have gauges.

**Comment by rom1701** [comment]
it work's, the problem of ui-graphite is in my service_description of this service, i had "ê" 
Thanks for your help

**Comment by mohierf** [comment]
Ouf!

**Comment by rom1701** [comment]
I think I know why the gauge is duplicated, I have a graphite template with multiples url. For the "edge" metrics, I have a graph with all "edge" metrics together and one graph per "edge" value. I see in eltdetail. tpl, they are a "for" loop that match the value name in all url graph, so this value is match 2 times

**Comment by mohierf** [comment]
Ok
