### ISSUE TITLE
User's preferences edition

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#318]
![image](https://cloud.githubusercontent.com/assets/2932687/9780937/1626a7bc-578f-11e5-975a-f2c1603c3e64.png)

Make this page editable to allow user's preferences to be changed by the logged in user.

Make some `webui2.cfg` configuration properties: 
- user login message
- sound playing for new alerts, 
- company logo
  
  stored and editable in user's preferences.

**Comment by maethor** [comment]
Because we need to focus on other stuff, and this doesn't not seem important, I am closing this issue.
