### ISSUE TITLE
Searching from element view => 404

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#319]
When a search is launched from the element view, it leads to a 404 because the search URL is bad formed: */host/all* instead of */all*

![image](https://cloud.githubusercontent.com/assets/2932687/9677819/d6121b5c-52de-11e5-85e8-6374c1641ba6.png)

@maethor : before this commit (https://github.com/shinken-monitoring/mod-webui/commit/61ee229eb7cc6a3ffc9628b6e19434bcf385ddd6) it was ok

**Comment by maethor** [comment]
I can't reproduce this bug. When I search something in the element view, it gets me to `/all?search=***`.

**Comment by maethor** [comment]
Some pre-defined filters are buggy thought (impacts…). But the main search is working for me.
