### ISSUE TITLE
Allow searching on current page

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#322]
When on minemap or worldmap page (as an example ...), using the search input field navigates to the problems page ... it may be interesting to refine the current view, displaying a filtered worlmap or minemap ...

@maethor: may not be that difficult I suppose ...

**Comment by maethor** [comment]
I already think about this. It is not difficult on the developer point of view. But I really don't know how to make this feature available in the interface. For me, the search field in the top bar must be used only to search for hosts in the "all" view. So this feature would need a second search field? I don't know.

I will look at various web interfaces to find the best solution to do this.

**Comment by mohierf** [comment]
We may include a specific search field on top of the Worldmap or Minemap for filtering ... perharps with the same system we used for the pagination list.

**Comment by maethor** [comment]
Nope :)

But let's discuss this in some weeks, after the 2.0 release.

**Comment by mohierf** [comment]
An idea about this feature ... I built a moke-up on the worldmap page : 
![image](https://cloud.githubusercontent.com/assets/2932687/9794348/e99b464c-57ea-11e5-987f-cfcfd95ebe1f.png)

> Note the options button ... and click on this button to open a side panel : 

![image](https://cloud.githubusercontent.com/assets/2932687/9794366/fef9c252-57ea-11e5-9652-ce7ff968c244.png)


Each WebUI plugin should declare its own options panel and its own options as we store the user's preferences. Same model as we do for widgets ...

We may include this side panel in a page when needed as we include the pagination element.

**Comment by maethor** [comment]
Hum. I really don't like it.

I think it would be better to have a popup for each module, using the current popup and forms system. We could indeed define a "preferences_form" in each plugin.

An other solution is simply to have a "preferences" page which aggregates all plugins preferences forms, one per tab (kind of what we did in eltview).

**Comment by mohierf** [comment]
1/ a slide panel or a popup ... ... why not a popup.

2/ we already have a preferences page ...simply click on user's name in header bar and then on the pencil icon to go to the preferences page. It will be quite easy to change this page and make it have some tabs ...

**Comment by maethor** [comment]
To complete my previous argument, I don't like it because it's not a base Bootstrap object, and I think we should limit us to BS objects to avoid bugs in inconsistency in the display.

Moreover, I really think this button is too visible (once we have set the preferences we don't need to use it anymore… ever) and could be overlapping key information in some pages (like /all).

**Comment by maethor** [comment]
I know we already have a preferences page, and I really think it's the better way to do it :)

We just have to make it "dynamic" (with tabs loading one form per plugin).

Also I'm worried about code duplication here. We should really make this more "generic" than the old preferences system (with huge code duplication copy/pasted in each plugin). I don't know how to do it yet, but it is something to keep in mind.

**Comment by maethor** [comment]
How sh*t, I completely misunderstood what you where proposing @mohierf. I was thinking about plugin preferences, not filtering. Sorry about this… (also we can copy my responses to another ticket about preferences, they make good arguments :D).

To answer on the filter mecanism. I'm more thinking of adding a dropdown in the topbar allowing to select the view in which we want to search. It should be possible with a generic mecanism where each plugin have (or not) the same "search" fonction, registered by the webui. And when we are on a plugin, the wright "context" is automatically selected (but can be change…).

I don't have too much work this morning, I'll try this.
