### ISSUE TITLE
Libs

### ISSUE THREAD

**Issue by ddurieux** [shinken-monitoring/mod-webui#324]
I have read a little sources today and I'm surprising to see lib in folder modules/lib/ instead use these modules installed with pip / manually / packaging system.

Perhaps you have a good reason for that but seems not a good idea :p

**Comment by mohierf** [comment]
Indeed you are right ... and not.

We decided to embed the Bottle version used by the WebUI to make it independent from the Bottle version used by Shinken and to avoid some conflicts if another Bottle version is installed on the system ...

I did the same with the `md5crypt` used for user's authentication that was previously in the `misc` directory of Shiken ... and for which I did not found any pip installable version ...

**Comment by ddurieux** [comment]
For bottle it's normal, version bottle in shinken is a dev version and very old version with some patches, so use the bottle package is good idea, so use bottle version installed on system will be ok.

For md5crypt, if not in pip, it's normal to have it in the repository ;)

**Comment by maethor** [comment]
Bottle is in lib/ for historical reasons. When we start to make the new webui, we didn't know the changes would be that huge, and we thought we could make the upgrade transparent. Know that we have added dependencies in a requirements.txt, we could do the same for Bottle, you are right.
