### ISSUE TITLE
Clean logs plugin ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#328]
... some parameters from the `plugin.cfg`file are not used anymore:
```
# Mongo DB server connection
mongo_host=localhost
mongo_port=27017

# Database name
database=shinken

# Collection name
collection=availability

...

# Filter for these hosts (leave empty for no filtering)
#logs_hosts=

# Filter for these services (leave empty for no filtering)
#logs_services=
```

**Comment by maethor** [comment]
You should pull the last version because I just cleaned up this file this afternoon ;)

**Comment by mohierf** [comment]
I pulled the last version ... indeed I spent my afternoon pulling ;-)

I simply opened this issue to keep tracking some cleaning in the configuration file and mainly in the source code :-)

**Comment by maethor** [comment]
Allow me to insist :) Look at 741edc307dc643dd0c27303449aee7ff53832244

**Comment by mohierf** [comment]
You are allowed :-)

Current plugin.cfg is yours ... but the last lines are unuseful and some source code still needs to be cleaned up ...
