### ISSUE TITLE
Documentation : update the Installation page

### ISSUE THREAD

**Issue by dooblem** [shinken-monitoring/mod-webui#332]
I just installed shinken and the webui2 module.

webui was responding, but very slow (1minute to display a page).

After installing mongodb, everything was fine. Can you update the doc, in the Installation page ?

**Comment by mohierf** [comment]
Thanks for reporting.

What you mean is that without mongodb, the WebUI response time is very slow ?

**Comment by maethor** [comment]
No, because `requirements.txt` lists python dependencies (to be installed via pip).

But the webui should not be that slow without mongodb. I'll take a look.

**Comment by mohierf** [comment]
I am  currently testing ... and if Mongo is not installed it is very slow ... because of the pymongo driver connection mode. I prepare a fix for his ...

**Comment by mohierf** [comment]
I fixed the problem. Moreover, I published a very new 2.0.1 version that allows the WebUI to run without any mongodb installation ...
