### ISSUE TITLE
Allow several Web UI instances on the same backend

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#336]
Allow several instances of the Web UI to run on the same server with different configuration.

To be discussed ...

**Comment by Dual-Boot** [comment]
nice :+1:

**Comment by mohierf** [comment]
Recent version 2.0.1 (https://github.com/shinken-monitoring/mod-webui/releases/tag/2.0.1) allows to keep two versions of webui on the same installation ...

Version 1 is installed in */var/lib/shinken/modules/webui* with configuration in `/etc/shinken/modules/webui.cfg`

Version 2 is installed in */var/lib/shinken/modules/webui2* with configuration in `/etc/shinken/modules/webui2.cfg`

Switching from one version to the other is made as simple as changing `webui` to `webui2` module in the broker configuration file ...

**Comment by Dual-Boot** [comment]
Great job, it works.
Thank you.

**Comment by Dual-Boot** [comment]
Hi,

 I found a little bug with authentication : 
- log into webui on port 7767 with my credentials
- log into webui2 on port 17767 with my credentials too
- return to my first webui on 7767 and navigate, and I do need to log again
I can not share my authentication with the same browser on 2 different instances of WebUi

  Regards,

**Comment by maethor** [comment]
We are limited by our web framework (bottlepy) here. I'm not sure we can find a solution to fix this… @mohierf what do you think ?

@Dual-Boot did you try with two different domains ? You can keep the ports, but I suspect this is mixed up because of the domain. To confirm.

**Comment by mohierf** [comment]
@maethor: I do not think it is possible ... due to what I observed with Bottle during my tests ... 

@Dual-Boot : the authentication is using a cookie which name is the same whatever the WebUI instance is ... do you have the same `auth_secret` property in the WebUI configuration file ?

**Comment by Dual-Boot** [comment]
Hi,

 I think the authentication problem is linked to the hostname too and maybe to the auth_secret propery which is the same.

 I will test that soon.
Thank again for the feature.

**Comment by Dual-Boot** [comment]
Hi,

 I confirm : 
2 differents URL for the same hostname on 2 differents ports work with the same credentials.

 Regards,

**Comment by mohierf** [comment]
Thanks for your tests which confirm what I supposed ... the way we are managing the user's credentials across the pages  forbids to have several instances of WebUI on different ports. We should change this management if we decide to implement this feature ...

@maethor: as you wrote : `This hack is crazy, but I don't know how to do it properly` ...

**Comment by maethor** [comment]
I'm not sure that's my hack which forbids to have several instances. Did you try with 2 different hostnames?

Anyway, I don't see the point of having two instances of the webui, so I don't intent to work on fixing this. @Dual-Boot just uninstall the old webui, you don't need it anymore.

**Comment by mohierf** [comment]
With the tests I made, I am quite sure that the hack to store the user in the bottle template impeachs to have two users with different credentials on the same server, even if two Bottle instances are running on different ports and two users with their own cookie are logged in ... anyway, I agree that it is not a must have feature.

**Comment by Dual-Boot** [comment]
@maethor just uninstalling the old webui on a test server => OK , but with a production server, it is safer to have the possibility to use the old one at the same time with the new one. Transition is softer and no need to have a rollback solution in my own opinion.

**Comment by maethor** [comment]
I'm not telling you to uninstall the old webui. Just disable it in the broker. I don't know about your production, but I'm sure that if you were using the old webui, your usage of the webui must not be that critical. Test the new one and just rollback by replacing "webui2" by "webui" in the broker config.

Also, "safety" speaking, the old webui is full of critical issues. The new one is a lot more safer.

**Comment by mohierf** [comment]
Definitely not to implement
