### ISSUE TITLE
Play sound alarm only on HARD states

### ISSUE THREAD

**Issue by vizvayu** [shinken-monitoring/mod-webui#340]
Ok this is just a wanted feature.... it'd be really nice if the sound alarm went off only with hard type states (same as notifications, right?). Or maybe even better, a configuration value to be able to choose.

**Comment by mohierf** [comment]
Nice idea!

We started a work on user's preferences management but currently one can only display the stored parameters (click on the gear icon in the user's pane ...). The idea is, at end, to allow editing the user's parameters ...

**Comment by mohierf** [comment]
@vizvayu : what about this in the last version 2.3.2 (or 2.4)
