### ISSUE TITLE
If there is no graph module, the gauges are not displayed

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#342]
This follow a comment of @mohierf in #316 

> I made a test this morning and I saw that if no graphs module is available in the WebUI the gauges are not displayed ...

I don't see what could justify this.

**Comment by mohierf** [comment]
Justification is simply an `%if ... %end`in the template view :angry: ... the gauge is displayed only if we got graphs from the graphs module.

I will fix this today.

**Comment by maethor** [comment]
OK, thanks.

**Comment by mohierf** [comment]
PR: https://github.com/shinken-monitoring/mod-webui/pull/343

**Comment by maethor** [comment]
Closed by #343
