### ISSUE TITLE
Element view enhancements (grouping requests)

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#344]
This issue to track element (host/service) view enhancements : 
- [x] element status Since information, allow to view absolute date (#345)
- [x] remove commands tab because commands may be launched from information tab (https://github.com/shinken-monitoring/mod-webui/commit/cd3ee559f8afad6725a07d2b91f7b9a34a16d53c)

- [x] remove impacts tab in host/service when no impacts exist
- [x] allow filtering in host element history: view hosts only or host+services logs

**Comment by maethor** [comment]
I don't think we should remove the impact tab when no impact exist. It's still OK to see the dependencies. With that said, we could name it dependency graph.

**Comment by mohierf** [comment]
But we already have a dependencies graph ... and when there is no impacts related to current element this tab is empty :/P

**Comment by mohierf** [comment]
No more actual ...
