### ISSUE TITLE
Duration : tooltip with exact date

### ISSUE THREAD

**Issue by Issif** [shinken-monitoring/mod-webui#345]
Hi,

Duration information for status check is nice but with a simple "2w 3d" this is not really easy to correlate with a known event (deployment, backup, etc).

I thought we could have a kind of mouse hover which displays a tooltip with exact Date (2015/09/12 12:59).

Thanks

**Comment by maethor** [comment]
This was already in my todo. But thanks for this ticket, I'll do it :)

**Comment by mohierf** [comment]
@maethor : I self assigned this issue ... I change assignment ;-)

**Comment by maethor** [comment]
@mohierf I complete what you did by adding a title in the problems view.

**Comment by mohierf** [comment]
:+1:
