### ISSUE TITLE
Errors on JS console

### ISSUE THREAD

**Issue by vizvayu** [shinken-monitoring/mod-webui#347]
When viewing the details of a service I'm getting these errors in the javascript console of my browser:

http://shinken.mydomain/static/availability/js/justgage.js Failed to load resource: the server responded with a status of 404 (Not Found)

http://shinken.mydomain/static/availability/js/raphael.2.1.0.min.js Failed to load resource: the server responded with a status of 404 (Not Found)

I checked the file permissions in webui2/plugins/availability/htdocs/js/ and they look OK.

**Comment by mohierf** [comment]
I cannot reproduce the problem on my configuration ...

Do you have the two JS files in the *webui2/plugins/availability/htdocs/js* directory ?

Do you have the same problem of JS file loading when you are on any other tab in the element view ?

**Comment by vizvayu** [comment]
It happens only in hosts or services views.
I do have those files:
ls -l webui2/plugins/availability/htdocs/js 
total 124
-rw-r--r-- 1 shinken shinken 34432 Sep  7 14:56 justgage.js
-rw-r--r-- 1 shinken shinken 90046 Sep  7 14:56 raphael.2.1.0.min.js

Changing tabs inside a host or service view doesn't change the error. It just stays there. There are no new errors when clicking tabs if that's what you needed to know.

**Comment by mohierf** [comment]
Is *http://shinken.mydomain/static/availability/js/justgage.js* the exact URL of the files that are not found ? Is it possible to have a look in the developer tools of your browser to find it ...

On my configuration, I got : *http://webui:7767/static/availability/js/justgage.js* ... it is the same URL except for the port number that is not present in yours ... should you explain your configuration ?

**Comment by vizvayu** [comment]
I have a varnish cache in front, that's why my URIs didn't show the 7767 port, but if I connect directly I get exactly the same errors. Here are the errors directly from the dev tools Chrome console:
GET http://shinken:7767/static/availability/js/justgage.js 
GET http://shinken:7767/static/availability/js/raphael.2.1.0.min.js 

And if I go directly to any of those URIs I get a page saying:

Error: 404 Not Found
Sorry, the requested URL 'http://shinken:7767/static/availability/js/justgage.js' caused an error:
File does not exist.

**Comment by mohierf** [comment]
Strange ! Very strange !

What about the ownership and rights of these files ? If you compare with some other JS files, eg. files like *http://shinken:7767/static/cv_host/js/flot/jquery.flot.min.js* ?

Except for this kind of errors, I do not see any differences ...

**Comment by vizvayu** [comment]
As far as I can tell there are no difference between those files and any other similar file. Here's an example:
root@blinker:/var/lib/shinken/modules# l webui2/plugins/cv_host/htdocs/js/flot/jquery.flot.min.js webui2/plugins/availability/htdocs/js/*
-rw-r--r-- 1 shinken shinken 34K Sep  9 07:07 webui2/plugins/availability/htdocs/js/justgage.js
-rw-r--r-- 1 shinken shinken 88K Sep  9 07:07 webui2/plugins/availability/htdocs/js/raphael.2.1.0.min.js
-rw-r--r-- 1 shinken shinken 52K Sep  9 07:07 webui2/plugins/cv_host/htdocs/js/flot/jquery.flot.min.js

One thing I noticed is that in webui2 pre-release version I saw a "Availability" tab in elements view (which failed with a 404 when I clicked it) but now using 2.0.1 freshly installed I don't see that tab anymore. Maybe I'm missing some module activation or something like that?

**Comment by mohierf** [comment]
I think we got it ! At least, something related with it ... because the two 404 JS files are related to the availability tab.

If you do not have any History or Availability tabs in the element view, it means that the Web UI Logs/Availability sub module is not activated, this because you do not have any MongoDB running or correctly configured ...

Did you installed the `mongo-logs` module in your broker? If so, do you have a specific configuration for it (other than default)? If so, did you made the same configuration in `webui2.cfg`?

**Comment by vizvayu** [comment]
I don't have mongodb installed on this server and the ```mongo-logs``` module is not activated in the broker service either. All sections regarding mongodb are still commented in the ```webui2.cfg``` file. Maybe webui is trying to read files from that inactive module?

**Comment by mohierf** [comment]
I made a test yesterday with  the Logs/Availability module disactivated and I did not have any problem to get the two JS files ... that are loaded even if module is not activated!

I really do not understand what is the problem with these files :astonished: 

Maybe a new fresh install will solve the problem: `shinken install webui2` ... sorry I do not see another solution!

**Comment by vizvayu** [comment]
Earlier today I tested this using a freshly downloaded webui 2.0.1 and the problem was still there. But I'll test it using ```shinken install webui2``` on Tuesday when I get back to work.
I'll let you know if I find anything new.
Thanks!

**Comment by vizvayu** [comment]
I tried with a new version installed using the shinken command, but the issue it's still there. I really don't know what could be the problem... but anyway, it's really not that important. I reported it because I thought it could be an easy fix.

**Comment by mohierf** [comment]
Thanks for your feedback for line endings ...

**Comment by mohierf** [comment]
As explained in https://github.com/shinken-monitoring/mod-webui/issues/383 it seems that the solution is to install required python modules ...
