### ISSUE TITLE
Impacts displayed 2 times in problems view

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#355]
Sometimes (all the times ?), impacts are displayed 2 times in the problems view.

For instance, when a host is down, all of it's services are correctly regrouped in a table under the host check, but they are also displayed in the main table.

**Comment by mohierf** [comment]
You are right ... we should only display problems if they are not impacts. It is enough to change the default filter to `isnot:UP isnot:OK isnot:PENDING isnot:ACK isnot:DOWNTIME bp:>0 isnot:impact` instead of `isnot:UP isnot:OK isnot:PENDING isnot:ACK isnot:DOWNTIME bp:>0`

**Comment by maethor** [comment]
Hm… indeed. But I think in that in the `all` view we should always "mask" impacts under their root cause, without having to specify `isnot:impact`.

**Comment by mohierf** [comment]
It seems that the initial problem is fixed: @maethor ?
