### ISSUE TITLE
How to get log from Webui itself

### ISSUE THREAD

**Issue by Dual-Boot** [shinken-monitoring/mod-webui#357]
Hello,

 Except in the brokerd log (where there is nothing about webui running) , where can I find the webui log ?

 Regards,

**Comment by mohierf** [comment]
The WebUI makes its log in the `brokerd.log` as any broker module ... there is no other log file available.

Default log level is the one defined in your `brokerd.ini` file, you may change it if needed.

WebUI does not make many logs to avoid making the log file grow too much, but if you start your broker in debug mode, you will have many logs about WebUI activity ...

**Comment by maethor** [comment]
In the broker log | grep webui :)

The webui doesn't have its own log file.

**Comment by mohierf** [comment]
brokerd.log | grep '[WebUI]'

**Comment by Dual-Boot** [comment]
May I ask for an enhancement for having webui log into a separated file or/and have an option in the webui configuration file to enable debug mode only for the webui ?

 Thank you.
PS: I prefer this command line tailf /var/log/shinken/brokerd.log | grep '\[WebUI\]' ;-)

**Comment by Dual-Boot** [comment]
Hello,

 I tried to enable DEBUG mode into brokerd but without any success.
I pushed log_level=DEBUG into the arbiterd.cfg and the brokerd.cfg but it does not change anything into the brokerd.log file.
 Did I miss anything ?

Regards,

**Comment by Dual-Boot** [comment]
OK, I was missing something : 
/etc/shinken/daemons/brokerd.ini
Just a missanderstood from my part.

 Good night ;-)

**Comment by maethor** [comment]
I don't think it's possible to have the log in a separate file :(

It may be a daemon, the webui is only a module of the broker. So it is using the broker logs (and the broker log_level, as you have seen).

What do you think @mohierf ?

**Comment by mohierf** [comment]
As far as I know of Shinken logging system, the WebUI, as a broker module, inherits from the logger of the broker daemon ... and it is not possible to change the log file that will be used.

Having our own logs should be possible but we will have to make some modifications to use our own logger ... this feature seems interesting to me for the next version.

**Comment by Dual-Boot** [comment]
Maybe the first step should be the availability to set the debug mode for the webui2 into its own configuration file webui2.cfg .

**Comment by mohierf** [comment]
Not enough time on my side for this feature.

**Comment by Dual-Boot** [comment]
No problemo. I understand.

**Comment by mohierf** [comment]
With the most recent developments (see ), it is possible to declare this configuration:
```

   # Declare the log file for the Shinken Web UI log (default is a null value)
   # If not set, then the WebUI will make its log in the broker log file
   # Else the WebUI will log in the broker log file and in its own log file
   #log_file       /var/log/shinken/shinken-webui.log
   # WebUI log level (DEBUG, INFO, WARNING, ERROR)
   # DEBUG is very very verbose because we get all the log from the Shinken broker!
   log_level      INFO
   # Set log_human_date=1 to have a human readable date for the log
   log_human_date 1
   # Set log_backup_count to the number of days to keep log files (default is 7 days)
   log_backup_count 7
```
