### ISSUE TITLE
What is the purpose of `manage_acl`?

### ISSUE THREAD

**Issue by quantonganh** [shinken-monitoring/mod-webui#363]
I'm going to add an "read-only" user who cannot submit a command and only see the hosts that they are contacts of. The first one is ok: there is no Commands tab when logging as that user but he still see the other hosts that he is not specified in the contacts/contact_groups.

Searching through Google, I found [this](http://shinkenlab.io/online-course-2-webui/) that said:

> manage_acl : should user only see elements that they are contacts of? :)

but in the source code, I saw it's something different:

```
   # Manage contacts ACL
   # 0 allows actions for all contacts
   # 1 allows actions only for contacts whose property 'is_admin' equals to 1
   # Default is 1
   manage_acl                 1
```

So, please let me know what is the purpose of this parameter? Can I create an "read-only" user that cannot submit commands and only see the hosts/servers that he is contacts of? If so, how?

**Comment by mohierf** [comment]
`manage_acl` as it is said in the webui2.cfg file is to allow any user to send commands on the system. Should you point out where you found anything else on Internet ?

 What you are looking for is the defaut behaviour: 
 - a contact who is not an admin can only see the elements he is related to
 - a contact who is not aan admin and has `can_submit_commands 1` property can submit commands

**Comment by quantonganh** [comment]
> Should you point out where you found anything else on Internet ?

The link is in the my question: http://shinkenlab.io/online-course-2-webui/

> What you are looking for is the defaut behaviour:

As I tested, it's not.

```
define contact {
    name salt-contact
    can_submit_commands 1
    is_admin 1
    host_notification_period 24x7
    host_notification_options d,u,r,f,s
    host_notification_commands notify-host-by-email
    host_notifications_enabled 1
    service_notification_period 24x7
    service_notification_options c,w,r,u
    service_notification_commands notify-service-by-email
    service_notifications_enabled 1
    register 0
}

define contact {
    name read-only-contact
    use salt-contact
    can_submit_commands 0
    is_admin 0
}

define contact {
    contact_name r1
    email r1@local
    password pass
    use read-only-contact
}

define host {
    name salt-host
    contact_groups admins
    notification_interval 0
    first_notification_delay 0
    notification_options d,r
    notification_period 24x7
    notifications_enabled 1
    active_checks_enabled 1
    check_period 24x7
    check_interval 2
    retry_interval 1
    max_check_attempts 2
    check_command check_ping
    event_handler_enabled 0
    flap_detection_enabled 1
    process_perf_data 1
    retain_status_information 1
    retain_nonstatus_information 1
    business_impact 5
    register 0
    poller_tag all
}

define host {
    use salt-host
    host_name p
    address 10.0.2.15
    alias p
    contacts r1
}
```

but login as `r1`, I still see the p2 host and all its services:

```
define host {
    use salt-host
    host_name p2
    address 192.168.23.112
    alias p2
}
```

Did I miss something?

**Comment by mohierf** [comment]
I did not really tested the new webui with the version 2.0.3 of Shinken ...  

Any other contacts groups or hostgroups in your configuration ?

`manage_acl` is still 1, I suppose ...

**Comment by maethor** [comment]
- What version of the webui are you using?
- Do you have `manage_acl 1`?

**Comment by quantonganh** [comment]
> What version of the webui are you using?

WebUI version 1.

> Do you have manage_acl 1?

Sure:

```
define module {
    module_name webui
    module_type webui
    host 127.0.0.1
    port 7767
    auth_secret xxx
    manage_acl 1
    login_text Monitoring
    modules SQLitedb, auth-cfg-password, ui-graphite
}
```

**Comment by quantonganh** [comment]
> Any other contacts groups or hostgroups in your configuration ?

Sorry. Let me clarify:
- there are some hostgroups in p
- p2 does not belong to any hostgroups

Actually, when I login to the web UI, then go to the Dashboard, Impacts or Wall, I just see a list of hosts that r1 is the contact of. But if I go to the Hosts groups, I can see all the hostgroups here. Why?

**Comment by maethor** [comment]
OK, I understand now.

WebUI 1 is not supported anymore. Please use WebUI2 which fixes this problem (and many many others).
