### ISSUE TITLE
Worldmap - Hosts with GPS coordinates in template

### ISSUE THREAD

**Issue by rhblind** [shinken-monitoring/mod-webui#365]
Hi,

I'm trying to display my different EC2 hosts on the worldmap plugin and have created a few host templates like this.

```
define host {
    name                eu-central-1a
    alias               eu-central-1a
    _LOC_LAT            51.739402
    _LOC_LNG            9.514163
    register            0
}
```

Next in my host definition, I'll use the template like this:
```
define host {
    host_name                  localhost
    use                        generic-host,eu-west-1a
    hostgroups                 linux
    contact_groups             admins
    ...
```
But the map plugin does not seem to pick up the `_LOC_LAT`and `_LOC_LNG` from the host template. Is this expected behaviour, or have I missed something?

(I tried adding the `_LOC_LAT` and `_LOC_LNG` directly in the host, but couldn't get it to load there either).

Thanks

**Comment by mohierf** [comment]
Normally, the `_LOC_LAT` and `_LOC_LNG` custom variables in the host are enough for the worldmap plugin ... you should confirm that your hosts do have these variables in the host element view. The custom variables are displayed in the configuration tab ...

**Note:** your configuration is not correct .. .you are defining a template `eu-central-1a` and using `eu-west-1a`

**Comment by rhblind** [comment]
Alright, thanks.
Ah, sorry just a typo from my side. I've got a host template for each of the availability zones, I just copied the one I had open in my editor ;)

It seems like the custom variables are not picked up correctly. I'll dig some more.
Thanks

**Comment by mohierf** [comment]
I just made a test with an host template as yours and tagged my host as `eu-central-1a` and here is it: 
![image](https://cloud.githubusercontent.com/assets/2932687/10073109/f4ca5792-62c6-11e5-993e-c7f46080539c.png)

**Comment by rhblind** [comment]
Alright, thank you.
Then I probably have some other issues as well..

**Comment by rhblind** [comment]
Ops, FYI I just didn't rebuild my docker container properly. It works as it should now ;)
