### ISSUE TITLE
WEBUI2 - Worldmap Plugin - OSM

### ISSUE THREAD

**Issue by Dual-Boot** [shinken-monitoring/mod-webui#366]
Hello,

 I tried to use OSM as a backend for the WorldMap plugin but I always have Google Maps.
I changed the configuration file /var/lib/shinken/modules/webui2/plugins/worldmap/plugin.cfg
and set 
```
map_layer=OSM
```
And restart/reload Shinken.
So I put TOTO as a value instead of OSM to generate an error and nothing changed too.

 Any suggestions ?

 Regards,

**Comment by b-keller** [comment]
Hi,

+1
same test, same problem...

**Comment by mohierf** [comment]
I had a look on this feature and I must say that it is really not functional ...please consider as if it did not exist :/P

**Comment by Dual-Boot** [comment]
Do you mean the OSM feature is abandoned ?

**Comment by mohierf** [comment]
No, I propose to tag this issue as a future enhancement for the application, but as I explained in a previous issue comment, I simply investigated on OSM but never used any of their API about map markers and information ... neither am I sure that it will be possible to have the same features as with Google Map API : spiderify, clusters, ... :/P

**Comment by mohierf** [comment]
Anyway, I will try to find some time in the next days to have a look ...

**Comment by Dual-Boot** [comment]
OK. So I stay tune to test and help.
Need to put my head into Python dev. ;-)

**Comment by mohierf** [comment]
For OSM, it will be javascript dev :-)

**Comment by Dual-Boot** [comment]
lol

**Comment by mohierf** [comment]
Postponed ...

**Comment by mohierf** [comment]
Thanks to @RoPP this feature is now availabe in the WebUI
