### ISSUE TITLE
Be able to configure the web UI to serve in a subdirectory

### ISSUE THREAD

**Issue by arthurlogilab** [shinken-monitoring/mod-webui#369]
Instead of serving http://host:7767/ we'd want to be able to configure it to serve http://host:7767/shinken/ so that it can be put behind an http proxy.

**Comment by mohierf** [comment]
Not 100% sure about this proposal ... because I never tested :/P

WebUI is based upon a Python Bottle Web server that can be used as an WSGI application with a Web Server ... as of it, it mat be possible to relocate the Web UI URL thanks to this configuration.

I had this link in my favorites: https://community.runabove.com/kb/en/development/how-to-run-bottle-uwsgi-nginx.html

**Comment by maethor** [comment]
Yes, that's an interesting request. But it may not be easy to implement.

**Comment by mohierf** [comment]
@arthurlogilab : did you made a trial with the link I provided?

**Comment by arthurlogilab** [comment]
@mohierf yes I read the article, but I'm lacking time to try out this type of solution. When I report a bug it's usually not just for me, it's a feature I think could be useful to others. If I have a problem that only concerns me then I'm fine with doing a work around like suggested by the article. 

On the other hand, I fully understand that this is open source and that you may not consider this important or have other issues to address first.

**Comment by mohierf** [comment]
The problem is not that this open source or anything else ... the problem is finding time to test :-) And I prefered asking if you did some more tests to have some feedback.

I made some tests recently and I did not have any problem to proxy the Shinken Web UI behind nginx ... next step is the URL rewriting because it is necessary, and it is not a mess :/P

 It seems that Bottle Web applications are not easily URL agnostic. I will make a test today and keep you informed about this ...

**Comment by mohierf** [comment]
I made a test to make the WebUI served from `http://localhost:7767/shinken` or any other subdirectory ... and it is a real mess! 

 Clearly, a huge application refactoring would be necessary to make this possible ... I give up for the moment.

**Comment by mohierf** [comment]
If you need to serve Web UI pages from a sub folder, you should try with an nginx frontend server as explained here: https://github.com/shinken-monitoring/mod-webui/wiki/Frontend-Web-server#nginx-http-configuration-relocate-in-sub-folder

**Comment by arthurlogilab** [comment]
@mohierf thanks for the documentation, will give it a try ASAP

**Comment by mohierf** [comment]
I made some tests with this configuration but I am also interested in your feedback.

**Comment by arthurlogilab** [comment]
Implemented your doc. Add to pull nginx-full from jessie-backports to get multiple sub_filter lines working. 

Other thing : s/webui/webui2/

All seems to work. Can't get the ```remote_user_enable 1``` and  ```remote_user_variable      X-Remote-User``` to work, but I'll file another issue. 

Thanks.

**Comment by mohierf** [comment]
You are right, I forgot to mention that the multiple `sub_filter` require a recent version of nginx ... I will update my doc.

Why `s/webui/webui2/`?

**Comment by arthurlogilab** [comment]
because ```shinken install webui2``` no ?

**Comment by mohierf** [comment]
My examples are using a */webui* url ...

**Comment by arthurlogilab** [comment]
```
-        root /var/lib/shinken/modules/webui/
+       root /var/lib/shinken/modules/webui2/;
```

**Comment by mohierf** [comment]
Thanks! I should change my glasses :-)

**Comment by arthurlogilab** [comment]
@mohierf I think we're missing a rule for /action/. Test by going to /problems and doing ACK or recheck on a number of elements (red error boxes). 

Tried to tweak the rules in nginx but with no success.

**Comment by UweSauter** [comment]
Hi.
I'm also interested in running webui2 in a sub folder behind Nginx. The problem I have is that this Nginx instance is already running as a rev proxy for an OpenStack Horizon dashboard. It already has a location rule for /dashboard and I cannot follow the config instructions in https://github.com/shinken-monitoring/mod-webui/wiki/Frontend-Web-server#nginx-http-configuration-relocate-in-sub-folder .

Can you think of an alternative approach to implement this? I'd like to have:
http://my.example.com/dashboard -> gives me access to OpenStack
http://my.example.com/monitor -> gives me access to Shinken

I could provide my current nginx config if you need a look.

Thanks.
