### ISSUE TITLE
Be able to configure the web UI to serve only from a whitelist of IPs

### ISSUE THREAD

**Issue by arthurlogilab** [shinken-monitoring/mod-webui#370]
It would be nice to add ACL to the webui so that one can allow an IP or a range of IPs to access it. 

This is useful when putting shinken webui behind a frontal that takes care of the authentication and sends a trusted X-Remote-User header (that mechanism is already available).

Falling back to firewall rules to implement this while awaiting this functionality.

**Comment by maethor** [comment]
What is the point of doing this on the WebUI ? The access can already be restricted on the proxy or by firewall, which is *way* better.

**Comment by mohierf** [comment]
I do agree with you @maethor ... this feature will be quite complicated to manage in the WebUI and will not be as powerful as what other tools may provide.
