### ISSUE TITLE
Error module installation on Ubuntu 15.04

### ISSUE THREAD

**Issue by bbcorp** [shinken-monitoring/mod-webui#377]
Hi guys,
I'm trying to install webui2 for Shinken on Ubuntu 15.04.
I followed the guide on the wiki for installating but when I restart Shinken I got this error from pollerd.log : 
Warning : Importing module webui2: cannot import name User

Does User.py need some king of extras packages to run ?
I'm using Python 2.7.9 and pip requirements are ok.

Thanks in advance

**Comment by mohierf** [comment]
I made a test today on a fresh Ubuntu 14.04 and I did not have any problem ... I copy my installation procedure. Could you see any differences? Make a new trial?

Shinken installation:
```
   # Logged in as root

   # Create a Shinken user account
   adduser shinken

   # Python setup tools
   apt-get install python-setuptools python-pip

   # Python utilities
   apt-get install python-pycurl
   apt-get install python-setproctitle

   # Shinken dependencies
   pip install CherryPy importlib pbr html

   # Shinken installation
   pip install shinken
```

WebUI installation:
```
   # Logged in as shinken user
   su - shinken

   # Initialize Shinken CLI
   shinken --init

   # Install module: webui2, Web User Interface
   shinken install webui2
   # Update broker configuration
   vi /etc/shinken/brokers/broker-master.cfg
   => modules webui2

   # Logged in as root
   su -
   pip install pymongo>=3.0.3 requests arrow bottle==0.12.8

   # Restart Shinken
   service shinken restart
```

**Comment by mohierf** [comment]
No news ... closing
