### ISSUE TITLE
Graphs are not working

### ISSUE THREAD

**Issue by agapoff** [shinken-monitoring/mod-webui#381]
Hi,

I have been using ui-graphite module with webui with no problems. But now webui2 generates img as follows:

```
<img src="/graph?url=http%3A//some-urlencoded-url" class="jcropelt">
```

But the request (/graph?url=...) just gets 404 Not Found.

I have found this route in webui2/plugins/graphs/graphs.py:
```
proxy_graph: {'routes': ['/graph'], 'view': 'graph', 'static': True},
```
but there is no view named "graph"

**Comment by agapoff** [comment]
The workaround to get graphs working is deleting

```
        for uri in uris:
            uri['img_src'] = '/graph?url=' + urllib.quote(uri['img_src'])
```
from webui2/submodules/graphs.py

**Comment by csakoda** [comment]
Seeing the same after installing webui2 out of shinken.io

**Comment by mohierf** [comment]
This problem must be fixed with the most recent version and the `graphite2` and `ui-graphite2` modules.
