### ISSUE TITLE
History tabs: no logs found

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#382]
Hi,

I don't understand, in History tabs i have a message say: No logs found.
I use Shinken 2.4 and WebUI 2. I install Mongodb and pymongo on the same machine.

Do you how i can generate logs ?

![erreur](https://cloud.githubusercontent.com/assets/15362041/10879868/0ed83812-8157-11e5-80d9-68633fa1089b.PNG)

**Comment by mohierf** [comment]
You need to install the Shinken module `mod-mongo-logs` (https://github.com/shinken-monitoring/mod-mongo-logs). It is this module that store logs in a mongodb database used by the WebUI ... did you installed?

**Comment by Azef1** [comment]
Thx, I did not install mod-mongo-logs. 
So now it's works ! 

Thx you
