### ISSUE TITLE
Availability tabs: 404 Not Found

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#383]
Hi,

On Availability tabs i have a error: "Sorry but there was an error: 404 Not Found"
![err404](https://cloud.githubusercontent.com/assets/15362041/10882557/0d8081bc-816c-11e5-94cd-0a140f5619de.PNG)

My mongodb is OK
Module mongologs is OK

Also, with "firebug (Firefox) module" i have this:
![err404_2](https://cloud.githubusercontent.com/assets/15362041/10882618/90e0727e-816c-11e5-8d67-e0f54eaf4cf2.PNG)

I have these files on  /var/lib/shinken/modules/webui2/plugins/availability/htdoc/js

Do you know how to fix 404 not found ?
I use WebUI2.

Thx

**Comment by mohierf** [comment]
I remember having had this problem ... and I think that I fixed with a browser cache refresh and a Shinken WebUI restart ... but not sure. Please confirm ...

**Comment by Azef1** [comment]
I confirm, i have the same problem after a browser cache refresh.
I tested with Firefox, Firefox in private browsing and Internet Explorer.
Do you think, justgage.js and raphael.2.1.0.min.js aren't in the correct folder ?

**Comment by mohierf** [comment]
I don't have the problem on my current configuration ... should you fetch the develop branch of the webui repo ?

**Comment by mohierf** [comment]
Same problem as #347

**Comment by Azef1** [comment]
Hi,
About #347 i check windows line endings on these two files, but there aren't windows line endings.
I checked with command vi :set list;  file raphael.2.1.0.min.js and dos2unix to convert.
So, I copied these two files in 
/var/lib/shinken/modules/webui2/htdocs/availability/js
(original: /var/lib/shinken/modules/webui2/plugins/availability/htdoc/js)
So, now i haven't Error 404 on these two files, but the tabs "Availability" doesn't work again because i have one error 404 :
![err4042](https://cloud.githubusercontent.com/assets/15362041/10912561/6922e0bc-824a-11e5-8268-5c709280ea39.PNG)

What is the inner folder ?

**Comment by Azef1** [comment]
Now it's works!!!
Soluce: Install module python requests and arrow
