### ISSUE TITLE
Error: 500 Internal Server Error on System->Logs menu

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#385]
Hi,
I installed Shinken 2.4, webUI2 and mod-mongo-log.
When i would like to access page : System->Logs, i have this message:
Error: 500 Internal Server Error
![err_logs](https://cloud.githubusercontent.com/assets/15362041/10906092/11368a64-821f-11e5-9cf6-d4de3889ab9f.PNG)
![err500](https://cloud.githubusercontent.com/assets/15362041/10906095/14ed4daa-821f-11e5-8e80-26f867c30a8e.png)

I have been bottle.py and logs.tpl

Thx

**Comment by mohierf** [comment]
Fixed in the current develop branch ... merge in master is coming soon!
