### ISSUE TITLE
Storage module error

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#389]
Hi,

I installed a fresh shinken with mongo and webui2 module.
On the Dashbord i have this message: 
![errdash](https://cloud.githubusercontent.com/assets/15362041/10942130/e9a8915e-830e-11e5-9f6f-d06d9ae61f7d.PNG)

On my mongo i noticed i haven't a "shinken" database created.
All shinken services are start and mongo too
All config are default

**Comment by mohierf** [comment]
I recently (few days ago) installed as you did and there was not any problem.

Please copy your brokerd.log with the broker starting ...

**Comment by Azef1** [comment]
I rebooted my server, and now it's works. 
Thx for your quick reply
