### ISSUE TITLE
Create a hostgroup inside a hostgroup ?

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#396]
Hi,

What is possible to create multi level hosts groups ? (a hostgroup inside a hostgroup)
Because with `hostgroup{ ... }` we can only created one level group.

example :
-Group Prod
----group server BDD prod
---------server_BDD1
---------server_BDD2
---------server_BDD3
----group server Web prod
---------server_Web1
---------server_Web2

-Group Dev
----group server BDD dev
---------server_BDD1
---------server_BDD2
---------server_BDD3
----group server Web dev
---------server_Web1
---------server_Web2
```
define hostgroup{
    hostgroup_name      group_bdd_prod
    alias               group_bdd_prod
    members             server_BDD1,server_BDD2,server_BDD3
}
define hostgroup{
    hostgroup_name      group_web_prod
    alias               group_web_prod
    members             server_Web1,server_Web2
}
```
I would like to create something like that:
```
define hostgroup{
    hostgroup_name      group_prod
    alias               group_prod
    members             group_bdd_prod,group_web_prod
}
```

**Comment by mohierf** [comment]
You can define multiple level hostgroups with the `hostgroup_members` propery of an hostgroup ... but it is not a WebUI feature ... simply a Nagios/Shinken configuration file one: 

```
define hostgroup{
    hostgroup_name      group_prod
    alias               group_prod
    members             host1, host2
    hostgroup_members group_bdd_prod,group_web_prod
}
```

The WebUI will manage this hostgroup hierarchy.

**Comment by Azef1** [comment]
Hi,
Doen't works :(
In webui2 i have 3 groups display instead of one:
![group](https://cloud.githubusercontent.com/assets/15362041/11060713/48c4e7fe-87a2-11e5-8c67-6744ad903d09.PNG)
I would like only "group_prod" display and if one clik on "group_prod" display "group_bdd_prod and group_web_prod"

My host.cfg
````
define host{
       host_name                      server_bdd1
       alias                          BDD 1
       address                        localhost
       check_interval                 5
       retry_interval                 1
       max_check_attempts             5
       check_period                   24x7
       contact_groups                 admins
       notification_interval          30
       notification_period            24x7
       notification_options           d,u,r
       icon_set                       server
}
define host{
       host_name                      server_bdd2
       alias                          BDD 2
       address                        localhost
       check_interval                 5
       retry_interval                 1
       max_check_attempts             5
       check_period                   24x7
       contact_groups                 admins
       notification_interval          30
       notification_period            24x7
       notification_options           d,u,r
       icon_set                       server
}
define host{
       host_name                      server_bdd3
       alias                          BDD 3
       address                        localhost
       check_interval                 5
       retry_interval                 1
       max_check_attempts             5
       check_period                   24x7
       contact_groups                 admins
       notification_interval          30
       notification_period            24x7
       notification_options           d,u,r
       icon_set                       server
}
define host{
       host_name                      server_web1
       alias                          Web 1
       address                        localhost
       check_interval                 5
       retry_interval                 1
       max_check_attempts             5
       check_period                   24x7
       contact_groups                 admins
       notification_interval          30
       notification_period            24x7
       notification_options           d,u,r
       icon_set                       server
}
define host{
       host_name                      server_web2
       alias                          Web 2
       address                        localhost
       check_interval                 5
       retry_interval                 1
       max_check_attempts             5
       check_period                   24x7
       contact_groups                 admins
       notification_interval          30
       notification_period            24x7
       notification_options           d,u,r
       icon_set                       server
}
````

My hostgroup.cfg
````
`define hostgroup{
    hostgroup_name      group_prod
    alias               group_prod
    hostgroup_members   group_bdd_prod, group_web_prod
}
define hostgroup{
    hostgroup_name      group_bdd_prod
    alias               group_bdd_prod
    members             server_bdd1, server_bdd2, server_bdd3
}
define hostgroup{
    hostgroup_name      group_web_prod
    alias               group_web_prod
    members             server_web1, server_web2
}

````
If i click on "group_prod" i have:
![servera](https://cloud.githubusercontent.com/assets/15362041/11060872/38e2a26c-87a3-11e5-8db7-9ca7d196b486.PNG)
So, here i would like to diplay "group_web_prod" and "group_bdd_prod"

group_prod is a parent
group_bdd_prod is a child
group_web_prod is a child
So, `hostgroup_members` it's to include a child in parent ? because on this site http://christian.weblog.heimdaheim.de/2008/08/08/nagios-3-and-hostgroup-inheritance/ it's the opposite.
i don't understand.

**Comment by mohierf** [comment]
Indeed, you have two problems ...

 1/ the most simple one is that you do not read all the articles :-) Joke :-) 

 Last paragraph is: *I quickly found out, that the relation is in fact defined within the parent hostgroup. So if you simply put hostgroup_members within the parent hostgroup and define all child hostgroups which should inherit from the parent one, you should be just fine.*

 So you should have defined: 
```
define hostgroup{
    hostgroup_name      group_prod
    alias               group_prod
    hostgroup_members   group_bdd_prod, group_web_prod
}
define hostgroup{
    hostgroup_name      group_bdd_prod
    alias               group_bdd_prod
    members             Shinken, shinkenpoller
}
define hostgroup{
    hostgroup_name      group_web_prod
    alias               group_web_prod
    members             sim-vm, sim-vm2, sim-vm3
}
```
 2/ The second problem is due to a Shinken bug: https://github.com/naparuba/shinken/issues/1652 ... and this bug make that whatever you definition of hostgroup is, you do not have any parent/child relation between the hosts groups! I proposed a fix but it has not yet been merged :/P

 You should edit the file: `/usr/local/lib/python2.7/dist-packages/shinken/objects/hostgroup.py`, and add this line between lines 40 and 41: 
```
        'hostgroup_members':    StringProp(fill_brok=['full_status']),
```

**Comment by Azef1** [comment]
Hi,
Thank you very much ! It's works
I hope that feature will be available in next release.

I suggest an improvement: To have same view with link "Down" and with link title group "group_prod".
(i think the view with "Down" link" is better than "title group")

**Today**
URL on "Down" button: `http://@IP_server:7767/hosts-groups?level=1&parent=group_prod`
URL on blue Title "Group_ prod: `http://@IP_server:7767/all?search=type:host%20hg:group_prod`

**Improvement:**
URL on "Down" button: `http://@IP_server:7767/hosts-groups?level=1&parent=group_prod`
URL on blue Title "Group_ prod: `http://@IP_server:7767/all?level=1&parent=group_prod` (if there is a hostgroup inside a hostgroup)

thx

**Comment by mohierf** [comment]
The idea of the links was to have:
 - a link to the groups inside the group (Down link)
 - a link to the hosts that are members of the group (Title link)

With your suggestion, we will not have this second link anymore ...

**Comment by Azef1** [comment]
Yes, you're right. I think to h

**Comment by Azef1** [comment]
Yes, you're right. i think to have two differents views are justified (Down link and Title link).
What do you think if these two links are positioned differently ?
![proposition](https://cloud.githubusercontent.com/assets/15362041/11116129/befb24bc-8930-11e5-8fe6-058f9566ee6b.PNG)

**On the general link** (Group_prod): link to see other groups inside. If it's a "child" group, display hosts that are members of this group (same that current title link a for child group)
**On the hosts link**: view all hosts that are members of the group

It's just an idea.

**Comment by mohierf** [comment]
Nice idea ... and why not. I will propose something in a next release ...

**Comment by mohierf** [comment]
See this commit before the new release: https://github.com/shinken-monitoring/mod-webui/commit/f34aae5981a8e40703fc2a6506e20afca652061c
