### ISSUE TITLE
Error 404:History tabs on service only 

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#398]
Hi, 

When i go to history tabs or Availability tabs on a **host**, i can see data and graphs. All ok.
But when i go to history tabs or Availability tabs on a **service**, i have error 404 not found.
![hostok](https://cloud.githubusercontent.com/assets/15362041/11058679/b9ad2e4e-8794-11e5-8308-b548694b6935.PNG)

![serviceko](https://cloud.githubusercontent.com/assets/15362041/11058637/7a93952c-8794-11e5-9bc7-d5f80218a78d.PNG)

Am I missing anything ? , Installed a module, python, ...

**Comment by mohierf** [comment]
Which version of the `mongo-logs` module did you installed? I published a version mid-september which stores services availability information in the database ... before this date the services availability was not stored.

You should try to:
- save your mongo-logs.cfg file
- shinken install mongo-logs
- restore your mongo-logs.cfg file

I will also make some tests on my testing environment ...

**Comment by mohierf** [comment]
Please take care of the module configuration file because the module behavior is to store only availability for hosts and services which business impact is greater than 4 ... this can also explain why you do not have anything in the availability tab for the services.

I configured as is: 
```
   services_filter bi:>0
```

**Comment by mohierf** [comment]
Concerning history tab, for an host or a service, this tab contains only the main logs for the host/service. Mainly it is SERVICE ALERT, HOST ALERT, SERVICE NOTIFICATION, ... if nothing special happened for the host/service, the history tab will remain empty!

**Comment by Azef1** [comment]
Hi,
I confirm you : It's works !!!
Soluce: Update webui2.0 to webui2.2 and update mod-mongo-logs1.0.2 to 1.2.0
And configure in mongo-logs.cfg `services_filter bi:>0`

Thank you very much for your quick reply.
