### ISSUE TITLE
remote_user_variable not working

### ISSUE THREAD

**Issue by arthurlogilab** [shinken-monitoring/mod-webui#406]
Am serving webui behind a nginx that has the following rule 

```
        proxy_set_header X-Remote-User "admin"; #will use $remote_user once it works
```
then modified my webui2.cfg
```   
   #commented line below
   #   #htpasswd_file              /etc/shinken/htpasswd.users
   remote_user_enable        1 
   remote_user_variable      X-Remote-User
```

Restarted shinken and nginx and it doesn't log in me automatically as expected.  

How do I debug this ? 

By the way, can I add contacts without passwords in /etc/shinken/contacts/*.cfg ?

**Comment by mohierf** [comment]
I did the same and it was ok for me ... I will have a look and give you some feedback.

By the way, when it is ok you can remove the password field in your Shinken contacts definitions.

**Comment by mohierf** [comment]
@arthurlogilab : I commited some modifications in the login process of the WebUI to add some logs. Please see this commit: https://github.com/mohierf/mod-webui/commit/b3a5ee6551543fbe7c387eee14b5c7131c332d29 and feel free to use it for more testings ... you may replace the `logger.debug` by `logger.warning` to get only those logs in your `brokerd.log` file.

**Comment by mohierf** [comment]
@arthurlogilab : any news about this ?

**Comment by bittrance** [comment]
FWIW I have a setup (Doorman+Shinken) where x-remote-user is working fine. Shinken 2.4.2, mod-webui 2.2.0.

**Comment by mohierf** [comment]
Thanks, I am closing this issue. If needed, please reopen ...
