### ISSUE TITLE
Error 404 on dashboard/currently

### ISSUE THREAD

**Issue by skyline42sh** [shinken-monitoring/mod-webui#407]
Hello,

I've install WebUI2 on my Shinken Server but I have this problem when I go on view dashboard/currently:

Error: 404 Not Found

Sorry, the requested URL 'http://<webui2-IP>:7767/dashboard/currently' caused an error:

Not found: '/dashboard/currently'

Thanks for your help !
Skyline42sh

**Comment by mohierf** [comment]
Which version did you installed? You can get the application manifest when you click on the top left logo ...

**Comment by skyline42sh** [comment]
Web User Interface Version

Shinken Web UI, version: 2.2.1

Shinken Framework Version

Shinken Framework, version: 2.4.2

**Comment by mohierf** [comment]
I confirm ... I also got the problem ... I will publish a fix rapidly for this.

**Comment by skyline42sh** [comment]
Nice ! Thank you for your speed !

**Comment by mohierf** [comment]
You can pick this commit to fix: https://github.com/shinken-monitoring/mod-webui/commit/ec1bec63f015350aef96f9ef8251ebc980320a4c
