### ISSUE TITLE
Changing the default graph size

### ISSUE THREAD

**Issue by vatese** [shinken-monitoring/mod-webui#408]
This question may be a little simple and dumb, but is there a way to change the size of the graphs under the 'graphs' tab for each host?

I have changed most of the settings for them through the graphite gaphTemplates.conf, but the size is just sticking to the default 586x308.

Many thanks

**Comment by mohierf** [comment]
You should have a look to the `ui-graphite` module configuration file ... as far as I remember you can configure width and height for the graphs. If you installed the last version you should have an `ui-graphite2.cfg` file in */etc/shinken/modules* ...

**Comment by vatese** [comment]
Thank you. I had the previous version of the graphite ui. Installed the new one and it worked!

**Comment by vatese** [comment]
Do you think it is better to remove the old ui-graphite module directory? For some reason even with ui-graphite2 installed, the old ui-graphite is being used (I changed webui2.cfg to point at ui-graphite2, but it didn't take effect)

**Comment by mohierf** [comment]
Yes, it is better to remove the previous one ... because Shinken loads everything it found in the modules directory.
