### ISSUE TITLE
All impacts in the Impacts View

### ISSUE THREAD

**Issue by ayaloulameche** [shinken-monitoring/mod-webui#409]
Hello,

Is it possible, with the webui2 module, to display all impacts in the Impacts View ?
Indeed, with the webui module, It works :
![shinken_webui](https://cloud.githubusercontent.com/assets/16012726/11394798/9b4b6b1c-9367-11e5-9088-8cf795cba5f3.PNG)

And with the webui2 module, I have only impacts with alerts :
![shinken_webui2](https://cloud.githubusercontent.com/assets/16012726/11394808/aaf9aad8-9367-11e5-94e8-db542f04dea5.PNG)

I didn't find the information in the doc (Maybe I missed something). I try with the search tab in the Impacts View but with no results.

My configuration is :
Shinken 2.4.2
Webui2 2.2.1

Can you help me ?

Regards

**Comment by mohierf** [comment]
1/ You may use the `is:impact` or `isnot:impact` in the problems list to list the resources that are (or not) impacts. 

2/ The impacts view filters as is: `bi:>=0 type:all isnot:ACK isnot:DOWNTIME is:impact`. If Shinken has detected that a resource is an impact you have this resource in the view ... if you think some resources should be prenset but are not, it is probably a Shinken issue not a WebUI one ... please try to investigate.

**Comment by ayaloulameche** [comment]
Ok, thank you for your answer.

Regards.
