### ISSUE TITLE
Host groups overview

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#41]
Add an hostgroup overview page : 
![image](https://f.cloud.github.com/assets/2932687/2246295/663be3dc-9d61-11e3-897e-9dcf223ffbff.png)

**Comment by mohierf** [comment]
![image](https://cloud.githubusercontent.com/assets/2932687/7047608/dff58122-de0d-11e4-912c-09b99239b1e1.png)

**Comment by naparuba** [comment]
looks sexy ^^
