### ISSUE TITLE
Use new shinken logo

### ISSUE THREAD

**Issue by arthurlogilab** [shinken-monitoring/mod-webui#413]
https://github.com/shinken-monitoring/mod-webui/blob/master/module/htdocs/images/default_company.png

**Comment by mohierf** [comment]
The new shinken logo is used on the login page:
![image](https://cloud.githubusercontent.com/assets/2932687/11441299/16cc9bf4-950b-11e5-86d5-1c8a60418c99.png)

The default company logo is intended to be modified to use your own logo ... this is why I left the old Shinken logo. Please see the Web UI configuration file ...
