### ISSUE TITLE
Dashboard  host service perf graph(s) - widget

### ISSUE THREAD

**Issue by zoza1982** [shinken-monitoring/mod-webui#415]
It would be super cool if we could add in the dashboard (widget) for example any hosts check graph ..... e.g disk free /  or load average graph instead of just host element graphs.

Also it wold great to be able to link any custom e.g aggregated graph from graphite saved graphs  into a widgets on the dashboard. I have a case where I am monitoring elasticsearch cluster and I always have to stare at broker queue ( redis )  graph, memory graph and CPU graphs and logs/second agregate indexing graph.

This way dashboard can truly be one-stop shop for all preview.
Is there a way to do that know via backend quick hacking?

**Comment by mohierf** [comment]
1/ You can have service graphs in the dashboard graph widget, see https://github.com/shinken-monitoring/mod-webui/issues/394: In the dashboard widget box, you can type an host name and then complete with `/service-description': eg. `shinken/Cpu` ...

2/ As far as I understand, you would like to be able to use an existing graph URL in a widget, right?
  If so, this widget will connect to the Graphite backend and will be able to request for user saved graphs to display one of them ?

**Comment by zoza1982** [comment]
Hi,

1/  Works! Thanks a lot ...I was not able to find documentation about it,nor it would autocomplete like it does for host element check. ( maybe autocomplete feature for service would be cool ? ) 

2/   Yes, thats exactly what I mean! That feature to link to any custom user saved graphite graph would be  awesome ! No way to that now?

**Comment by zoza1982** [comment]
Here is an example of user custom ganglia graph which gives me one view on monitoring cpu load average on 16 hosts at the same time. Linking this to a dashboard instead of having 16 widgets ( each for one host )  would be a killer feature.
![screen shot 2015-12-02 at 1 11 05 pm](https://cloud.githubusercontent.com/assets/11164593/11544400/7e4ae800-98f6-11e5-9e6a-a0e0b754dd5d.png)

**Comment by mohierf** [comment]
1/ You are right ... autocomplete for services would be nice.

2/ I will submit some modifications in the develop branch ... stay tuned :smile:

**Comment by zoza1982** [comment]
Thank you very much. I am really enjoying webui2 . It's amazing product.

Looking forward for 2/  :+1:    ( I am very excited )

**Comment by mohierf** [comment]
You can pick the `develop` branch and give it a try ... I stay interested in your feedbakc about it!

**Comment by zoza1982** [comment]
Hi
1)  I got your newest dev release working. Looks great I verified autocomplete after hostname/ works and starts popping up services!

2) I see the new graph widget is changed when you edit it,  showing new filed for Graph URL: . However when I punch direct link for my saved graph which us ugly and long  http://10.203.50.170:8080/render?width=1000&from=-1hours&until=now&height=400&lineMode=connected&drawNullAsZero=false&connectedLimit=&hideLegend=false&_salt=1449090653.531&target=clbt2cld001.shinken.Load.load1&target=clbt2cld002.shinken.Load.load1&target=clbt2cld003.shinken.Load.load1&target=clbt2cld004.shinken.Load.load1&target=clbt2cld005.shinken.Load.load1&target=clbt2cld007.shinken.Load.load1&target=clbt2cld008.shinken.Load.load1&target=clbt2cld009.shinken.Load.load1&target=clbt2cld010.shinken.Load.load1&target=clbt2cld011.shinken.Load.load1&target=clbt2cld012.shinken.Load.load1&target=clbt2cld013.shinken.Load.load1&target=clbt2cld014.shinken.Load.load1&target=clbt2cld015.shinken.Load.load1&target=clbt2cld016.shinken.Load.load1&_uniq=0.8005384274292737

I got this URL from above by right clicking on the graph I posted your yesterday and doing selecting "copy image address"  ( in chrome ). This URL works fine by posting it into another tab or running it as iframe.

Results:
It takes it but  then shows white window widget with "No data" in it. So I edit it again and then I saw that widget chopped of my URL down to just " http://10.203.50.170:8080/render?width=1000 " seems like a input limit  for Graph URL field?

Here is screenshot of what I see when I edit widget in which I previously pasted above long and ugly URL.

![screen shot 2015-12-03 at 4 04 25 pm](https://cloud.githubusercontent.com/assets/11164593/11578139/94c3ee42-99d7-11e5-97e8-19e550ece3f9.png)

I also tried to form a link from ganglia dashboard which ended up being shorter  ( http://10.203.50.170:8080/dashboard/CLBT2%20data%20load )   ...but still same result.

**Comment by zoza1982** [comment]
Interesting finding I just got is when I post a link to google.com  main page image  https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png  which is also decently long link...but not as long as mine from above...result is :+1: 

![screen shot 2015-12-03 at 4 31 31 pm](https://cloud.githubusercontent.com/assets/11164593/11578554/8468b722-99db-11e5-912a-89f1fb56ee0f.png)

**Comment by zoza1982** [comment]
I tried switching ganglia to run from 8080 back to just 80 and updating widget URL...but no help. So its not port being in URL related.

**Comment by mohierf** [comment]
I am thinking about an encoding problem ... complex URL with many &(" characters which is managed in forms, then URL parameter, then Python, then template, then Javascript ... and something is lost in all those transformations! I will have a look ...

**Comment by mohierf** [comment]
I made some more tests with an URL such as: http://192.168.0.42/render/?width=320&height=240&fontSize=8&lineMode=connected&from=04:57_20151203&until=04:57_20151204&tz=Europe/Paris&title=Outlook_Web_Access/ - rta&target=alias(color(Outlook_Web_Access.rta,"green"),"rta")&target=alias(color(constantLine(1000),"orange"),"Warning")&target=alias(color(constantLine(3000),"red"),"Critical")

and it confirms some encoding problems! I commited some new modifications in my last PR: https://github.com/shinken-monitoring/mod-webui/commit/1d7a2f0cd4fd8ab969371bd5df3a230ee12b6f88

**Comment by zoza1982** [comment]
Amazing!  Thank you, thank you , thank you !

![screen shot 2015-12-04 at 11 49 25 am](https://cloud.githubusercontent.com/assets/11164593/11599699/31894bf0-9a7d-11e5-9d95-20fb2eadeaff.png)
