### ISSUE TITLE
Displays the value 0 in the Min field

### ISSUE THREAD

**Issue by medismail** [shinken-monitoring/mod-webui#417]
Hi, 

I noticed that the value 0 is not displayed in several fields and in the graph tab, This is done on purpose? because to correct that simply change the test in /var/lib/shinken/modules/webui2/plugins/eltdetail/views/eltdetail.tpl
<td>{{metric.min if metric.min else ''}}</td>" with "<td>{{metric.min if metric.min!=None else ''}}</td>"

**Comment by mohierf** [comment]
You are right ... this is not on purpose ... this is a bug :/P

I will fix in a next release, thanks!
