### ISSUE TITLE
Fixed headers in minemap

### ISSUE THREAD

**Issue by N-Mi** [shinken-monitoring/mod-webui#419]
Hi,

When displaying a long list of hosts in the minemap, it's very difficult to keep track of which column belongs to which service.

So I suggest fixing the headers so that they are always displayed on screen when scrolling through the hosts.

Alternatively, displaying the headers at regular intervals could also be a solution to improve readability.

N-Mi.

**Comment by mohierf** [comment]
Nice idea! I will implement a fixed table header in a next release ...

**Comment by N-Mi** [comment]
Thanks !
