### ISSUE TITLE
Multiple level servicegroup --- Help please

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#423]
Hi,
I would like to do a multiple level servicegroup. (group child in group parent).

I created a servicegroup.cfg
>define servicegroup{
>   servicegroup_name      dev
   alias                  dev
   servicegroup_members   dev_child
}
define servicegroup{
   servicegroup_name   dev_child
   alias               dev_child
   members             localhost,http
}

and a service.cfg
>define service{
   service_description  http
   use                  generic-service
 #register             0
   host_name            localhost
   check_command        check_ntp
#servicegroups        dev_child
}

and i edit this file: 
`/usr/local/lib/python2.7/dist-packages/shinken/objects/servicegroup.py` and add
`'servicegroup_members': StringProp(fill_brok=['full_status']),`

The result is: 
![child](https://cloud.githubusercontent.com/assets/15362041/12090294/df90153e-b2ed-11e5-9458-5ed6440b6c30.PNG)

So the problem is "dev_child" is not include in "dev" group. And dev group is empty.

Thx

**Comment by Azef1** [comment]
Do you need more informations ?
I work with:
Shinken version: 2.2.1
WebUI 2.4

My config servicegroup.cfg to declare a service group is correct ?
If you apply the config, have you same problem that me ?

Help me please this feature (multiple level servicegroup) is very important to finish my project.

Thank you in advance.

**Comment by mohierf** [comment]
I will try to have a look today or tomorrow ...

**Comment by mohierf** [comment]
Problem found ... I will commit a fix nearly
