### ISSUE TITLE
Error: 404 dashboard/currently

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#424]
Hi, 
When i click on "Dashboard currently" i have a error 404 not found. 
![top](https://cloud.githubusercontent.com/assets/15362041/12093538/d2053a96-b303-11e5-84a3-0b222911d951.PNG)
![aaaa](https://cloud.githubusercontent.com/assets/15362041/12093555/f088db76-b303-11e5-8f68-ac872b0aeb0d.PNG)

Thx

**Comment by mohierf** [comment]
Please see https://github.com/shinken-monitoring/mod-webui/issues/407

**Comment by Azef1** [comment]
thx
