### ISSUE TITLE
Enhancement :  add support for influxdb

### ISSUE THREAD

**Issue by Dual-Boot** [shinken-monitoring/mod-webui#425]
Hello,

 Is there a way that in a futur release of webui, influxdb will be support into webui like graphite ?

 Regards and Happy new year,

**Comment by mohierf** [comment]
As far as I know, InfluxDB is not able to provide graphs for the metrics that are stored in a DB ... if so, there is not interest to interface it to the WebUI, right?

It may be more interesting to interface WebUI with an InfluxDB capable Dashboard, like Grafana ...

**Comment by Dual-Boot** [comment]
Influxdb has now its own dashboard called Chronograf, and InfluxDB has change to influxdata.
So influxdata gathers 4 softwares : 
- influxdb = the database
- chronograf = the dashboard , not production ready
- Kapacitor = handle alerts
- telegraf = the collector

But Grafana is supported by influxdb and Grafana support influxdb ;-)
