### ISSUE TITLE
Can't add depgraph widget

### ISSUE THREAD

**Issue by zoneroot** [shinken-monitoring/mod-webui#429]
Hello i can't add depgraph widget on my dashboard. when i click on "add depgraph widget" chrome console tells me : "Uncaught SyntaxError: missing ) after argument list".
To add the widget I have edit button code and remove " '[ " and "  ]' "  from " javascript:AddNewWidget('['/widget/depgraph']', 'widget-place-1'); ".

I use chrome (same bug on edge) with shinken 2.4.2 and webui 2.2.1.

**Comment by mohierf** [comment]
Thanks for reporting. I will fix this soon ...

**Comment by jgwinner** [comment]
I have the same issue. Webui 2.2.1 and Shinken 2.4.2 as well.

Is there a fix for this? We have a complex network and seeing the graph would be fantastic.

**Comment by mohierf** [comment]
This fix is not yet released. But you can use this commit to fix: https://github.com/mohierf/mod-webui/commit/021eb4090ec3327d5adae9c4cfe1bf9d2ef8fbcb
