### ISSUE TITLE
No disk state_up image

### ISSUE THREAD

**Issue by zoneroot** [shinken-monitoring/mod-webui#430]
The state_up image of disk set is missing : "http://****/static/images/sets/disk/state_up.png 404 (Not Found)" on shinken webui 2.2.1 with shinken 2.4.2

**Comment by mohierf** [comment]
Hmm ... this image set is made for a service not for an host ... this is why there is no UP state image. States should be OK, WARNING, ... as for a Shinken service.

**Comment by zoneroot** [comment]
Ok thanks
