### ISSUE TITLE
News about improvement impact graph ?

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#433]
Hi,

In #315 you talk about to improve impact graph using https://philogb.github.io/jit/demos.html or other plugins, have you news ?
I'll be happy and a great improvement for webui if module "impact graph" could add new functionalities.
For example: the functionality to manipulate and to edit is impressive. https://philogb.github.io/jit/static/v20/Jit/Examples/ForceDirected/example2.html

Thx

**Comment by mohierf** [comment]
As explained in another issue, it will need a huge refactoring ... and I have not time currently to start this work :/P If someone is interested I may help ...

**Comment by maethor** [comment]
Closed as duplicate. Please respond in #315 if you want to comment on this issue.
