### ISSUE TITLE
Daemon status is sometimes empty

### ISSUE THREAD

**Issue by peterhoeg** [shinken-monitoring/mod-webui#434]
Using webui2 v2.2.1.

At times the System\Status simply shows the headers (pollers, scheduler, brokers, etc) but none of the actual daemons. Restarting the arbiter and broker sometimes solves it. Sometimes it takes severals restarts before anything happens. There are no errors in the logs to indicate anything odd going on.

How can I provide the relevant information to help troubleshoot this?

**Comment by mohierf** [comment]
A screen capture may help when the problem occurs.

I think that the problem may not be in the Web UI but in the internal Shinken data that are probably not up-to-date. After a restart it need some time for those data to be available ... please copy a screen capture when the problem occurs.

**Comment by peterhoeg** [comment]
I'll take a screenshot next time it happens - but it is basically just the normal status view without any data at all.
Oddly enough, when webui2 doesn't show anything, running this script for checking the status https://github.com/david-guenault/shinken-packs/blob/master/pack-arbiter2/libexec/check_shinken2.py still works as expected.

**Comment by peterhoeg** [comment]
And now it happened.

![screenshot_20160118_165914](https://cloud.githubusercontent.com/assets/722550/12387067/e415adfe-be04-11e5-877f-40ab7392a5a2.png)

Broker and arbiter have both been up for 14 minutes by now. I don't need to add additional checks right now, so I'm ready to try things out before having to restart shinken again.

**Comment by mohierf** [comment]
I had a look more deeply on this view data and, indeed, this view does not launch any checks by itself ... it simply displays the internal daemons state maintained by the Shinken regenerator. As of it, I confirm that the problem is not a WebUI problem ...
