### ISSUE TITLE
Enhancement: add support for Grafana

### ISSUE THREAD

**Issue by wiflye81** [shinken-monitoring/mod-webui#435]
Hello,

It would be great to support Grafana shared panel with url like this:

http://localhost:3000/dashboard/db/server?panelId=1&fullscreen&from=1450953332105&to=1450960532107

I think it can work by modifying Graphite template but with no success.

The main problem is with encoded url used for Graphite, Grafana can't handle this kind of url.

Regards and thanks for this great UI.

**Comment by mohierf** [comment]
I agree. This feature would be great ... some similar feature has been discussed in #425 

You can still make a test with the graph widget where you can copy your URL in the URL edition field.

But you should be aware that if your grafana requires a login, you will not be able to diasply a shared panel :/

**Comment by wiflye81** [comment]
I will test with the graph widget.

For the authentication part, a common SSO or disable Grafana auth.

**Comment by mohierf** [comment]
Did yout tested this?

**Comment by wiflye81** [comment]
Yes, sorry for the delay, but no luck, my last option is to use a php page to make the decoding and redirect to Grafana.
But I don't know when I can test it.

**Comment by mohierf** [comment]
Ok. I close this issue. Please feel free to reopen it for giving news.
