### ISSUE TITLE
WebUI https / ssl support

### ISSUE THREAD

**Issue by ClaudiuPID** [shinken-monitoring/mod-webui#436]
I looked through config and searched this but I did not find anything in regards to webui and ssl.
Is this planned or easy to implement?

**Comment by ClaudiuPID** [comment]
I found this wiki article which is even better than what I wanted: https://github.com/shinken-monitoring/mod-webui/wiki/Frontend-Web-server

Thanks :)

**Comment by maethor** [comment]
Yep, no point of implementing https where Nginx and Apache are doing it perfectly :)
