### ISSUE TITLE
Display multiple graphs in graph tab ?

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#437]
Hi,
I would like to know if it's possible to show/to add multiple graphs from graphite in graph tab ?
Something like that:
![multiple graph](https://cloud.githubusercontent.com/assets/15362041/12617546/6a5af268-c510-11e5-92db-c3258a34b34d.png)

Thx

**Comment by mohierf** [comment]
Not currently.

The graphs included in the graphs tab are selected automatically. The WebUI tries to build a graph for each metric of the current element (host or service). There is no possiblity to define which graph is to be displayed or not, and there is no possiblity to add an extra graph ... you can use the dashboard graph widget if you are interested in a specific graph.

Perharps it may be an interesting future enhancement for the WebUI to define a kind of graphs page template ... to be discussed.

**Comment by maethor** [comment]
On a service it seem's irrelevant, but on a host, like we do in the Information tab, we could autodetect some services and display their graphs (load, ram, etc…). Could be very nice.

**Comment by couloum** [comment]
Hi,

I would also be very interested by a feature like this.

Another goal would be to display the same metric (load average for exemple) of multiple servers of the same groupe (10 web servers in the same load balancing group). This way, it would be possible to identify an issue on a specific sever without performing multiple clics to view 1 graph for each server.

Centreon has a pretty good view for this where you can add any graph you want in a single page. I wouldn't go back to Centreon, but Shinken could pick good features like this one.

Thanks
