### ISSUE TITLE
Zoom under Graphs

### ISSUE THREAD

**Issue by arnaudboyer** [shinken-monitoring/mod-webui#438]
Hi,

Since i use the NewWebui i can't zoom on the graph. (was possible to zoom in the old webui)

Do you think add this feature ?

Thanks !

**Comment by mohierf** [comment]
Sorry. I removed this feature in the new Webui because it was quite buggy and complicated to implement ... I will have a look to reintroduce it in a next version.

**Comment by arnaudboyer** [comment]
Ok thanks you =)

It's really an important functionnality for my end users.

Regards,

**Comment by maethor** [comment]
I agree, it's really handy to zoom on the graphs and export only the part we want. But it's really hard to implement and to make this generic both for graphite and pnp4nagios.

**Comment by mohierf** [comment]
@maethor : I have an idea to re introduce this feature but I will not be able to test if it is suitable for pnp4nagios ... should you?

**Comment by maethor** [comment]
@mohierf I plan to work on this (and to rethink all the Graph tabs) in the following weeks. I will keep you posted when you can test with graphite. The API should be the same.

**Comment by maethor** [comment]
I did a first commit on this, to allow panning and zooming on the graphs. I am not entirely satisfied by the UI, but it is already superior to the last version, so I will merge in the next release, maybe tomorrow or in a few days.

![image](https://user-images.githubusercontent.com/2410576/69168256-aa15a800-0af6-11ea-959e-ea2732b1fecd.png)

It should work both with PNP4Nagios and for Graphite.
