### ISSUE TITLE
Dashboard design

### ISSUE THREAD

**Issue by edouard-lopez** [shinken-monitoring/mod-webui#440]
Keep in mind this is a review of the _dashboard_ screen not of the developer. I will ask stupid question but sometimes as developers we forget to step back or [keep going in a wrong direction (i.e. momentum-behavior).][momentum-behavior]

## What is the purpose of the screen?

This is one important question that should drive the design. Each time you add an item to this page, ask you the the question "is it dashboard role to cover <item-role>?". For instance,

  * is it to give time? _No_
  * is it to give day of the week? _No_
  * is it to provide a count of monitored host? _Not really_
  * is it to provide a count of monitored host in error? _Probably_, but asks yourself
    * **what users can do with this information?**
    * which information is more useful to know, that 4 hosts are down or 25% of hosts? (assuming it represent the same)

## Review

![shinken-dashboard](https://cloud.githubusercontent.com/assets/1212392/12777928/0722d77e-ca60-11e5-9ceb-a0c7d09b027e.png)

### ① Displaying time

**Review:**

  * it takes roughly 30% of the screen ;
    * do we really need to show the time? even the seconds? 
  * it is bigger than hosts status info! Are you sure you want that?

**Recommandations:**

This look like a huge waste of screen real state, consider **removing it if useless** or if you really need to display time try **a more discrete design**. For instance see how your desktop display time:
 
  * it's on demand information (in the taskbar) ;
  * it's small (it's metadata) ;
  * it's not super precise as we generally don't care about second.

### ② So many nuances

**Review:**

  * What are we talking about? Issues, hosts, services, states, ratio, absolute?
    * set a closed-vocabulary for your view ;
    * keep concepts to a low (~3-4) ;
  * How many states can have? 4, 6, more?
    * 4: OK, error, warning, info ;
    * 6: 4 above plus 2 I don't understand, they seems to be disabled/muted (that's the meaning or gray color).
    * more
  * Is it really useful to have so much nuances? Not really, a dashboard is here to:
    * give an overview, i.e. not every need to be shown ;
    * help you understand with a glance, so don't over-complexify ;
    * to help you decide **what's the next action**.
  * Be careful with [icons, quite often they are not as clear as you think][icons].
    * I'm still not clear what's the tick and ambulance mean.
    
**Recommandations:**

  * Display information only when needed
    * showing there is `0` warning is useless, so don't show it.
    * default state, _i.e._ without errors, should empower users with statement like:  
        > _"everything is running fine, go grab a coffee!"_
    * only **show errors if any**, otherwise keep silent ;
  * Reduce the number of information [so decision can be taken quickly][hick-s-law] (cf. Hick's law).
    * I'll go for only 2 states: 
        1. error → display ;
        2. OK → don't show it, it's the default behavior.
    * if you really need to keep them all, you should improve the lay
  * add a label to your icons, it will add meaning and reduce ambiguity.

### ③ Chartjunk and cognitive overload

**Review:**

  * too much precision, do we really need to know that `42.86%` are down isn't `43%` enough? 
  * too much interpretation possible (so many icons, so many colors and combinations) 
  * too much useless info (if it bring nothing to the table, don't show it)
  * not enough labels

**Recommandations:**

### ④ Group related items

**Review:**

* number of problems is on the opposite side of hosts count, yet they are related.
* use space between items when needed

**Recommandations:**

* following the [Gestalt principle of proximity][gestalt]
* put distance between parsimoniously:
  * label and icon should be close
  * different items should have greater distance than the one above.

[momentum-behavior]: https://www.nngroup.com/articles/lazy-users/
[hick-s-law]: https://en.wikipedia.org/wiki/Hick%27s_law?oldformat=true
[icons]: https://www.nngroup.com/articles/icon-usability/
[gestalt]: https://www.wikiwand.com/en/Gestalt_psychology#/Gestalt_laws_of_grouping

**Comment by mohierf** [comment]
Very nice comments! Is is always a great help to recevie so useful remarks. I will take care about them to design a new screen for a next version.

Many thanks about this effort.

**Comment by ddurieux** [comment]
It's a very nice enhancement of usage, so thanks for that, it's so rarely :)

**Comment by maethor** [comment]
WOW, awesome comment! And I agree with you, the dashboard is quite useless.

@edouard-lopez I would be very VERY happy to have your feedback on the main views of the app:  /problems and /host/<hostname>

Thank you, this is awesome :+1:

**Comment by david-guenault** [comment]
lgtm :+1:

**Comment by mohierf** [comment]
@maethor : I do not agree with you ... the dashboard and the currently view is **not** quite useless, because I use it every day ... but I really agree with the fact that it is over informative and not as simple as it might be!

We really need a huge work on this to make things simpler and more efficient.

**Comment by maethor** [comment]
At the top of `/all` you have all the information you have in the dashboard.

**Comment by ericpascual** [comment]
As a brand new user of Shinken (I should say "as a guy who just installed it and try to cope with its concepts and way of  use" ;-)) I was (and still am) very puzzled by the dashboard. So I warmly thank the OP comment for reassuring me about my IQ :-)

To add my $0.02, my expectation WRT a typical dashboard is to give an overall picture of the situation and if there is some emergency to deal with. It should do this in a single and quick glance, without requiring decryption efforts. For instance, a 8x4 (or less) grid view showing monitored nodes as cards with their status rendered with the conventional 3 colors (green/orange/red) and displaying a few key numbers (let's say 2 or 3 max.) is fine. This way you can check if something is wrong, even when viewing the screen from some distance. 

If you think that some more detailed information is useful to communicate, put it in a popup or accordion, or whatever widget, displayed only on demand. If a single grid is not enough, use a recursive hierarchical approach by letting the user create groups which will appear as cards, and lead to another identically shaped sub-dashboard for displaying their content (be they nodes or other sub-groups or a mix of both) when clicking on them.

As an illustration of what precedes, I'm presently working on a project for a monitoring system in a residence for aging people, using ambient instrumentation in the apartments for capturing behaviors (don't be afraid, no "Big Brother" inside :-)). The system includes a dashboard installed at the desk, showing the desk employee if something is wrong in one of the apartments (emergency situation detected, resident calling from help, suspicious absence of activity, technical issue,...). What has been retained by the client among our proposals is a 8x4 grid showing the status of the 32 apartments, using the 3 colors code, accompanied if necessary by a very short label identifying the event if any. For more detailed information, each card has a "hamburger" in the upper left corner, giving access to it and to the associated actions if any.

The idea here is to deal with levels of detail, considering that you can always aggregate items of complex structures using group and parenthood relations for keeping as low as possible the cardinality of each LOD. Keep in mind that a lot of studies have identified that the average human brain is not able to cope with 5 or 7 different tasks/problems/concerns/... at the same time. And I suspect that this number is a bit optimistic (at least as far as I'm concerned :) )

I'm sure that someone here will answer: "brilliant idea, please fork and propose an implementation". He/she would be right, and I wish I could. But, unfortunately, I have no time for this, and I'm not sure to be capable (for the moment and for a while) to cope with such a task. So just take my post as a source of inspiration ;-)

Best regards

**Comment by mohierf** [comment]
Many thanks for all the comments in this thread.

Currently, Shinken WebUI has two so-called dashboard views: 
- */dashboard* used by monitoring people for daily monitoring and analysis
- */currently", intended simply to keep an eye on the system

The */dashboard* view allows to use many widgets to provide amny details on what is happening on the monitored objects.

The */currently* view aims at being displayed on a wide screen to provide only the main information on the system. the idea behind this view is: *is my system under control?* I would say that it is a *Big Brother* :smile:  view for the monitoring system ... This view can even be used by anonymous users (do not need to be logged-in to display this view).

I copy screen captures below for better understanding ...

**/dashboard** view:
![image](https://cloud.githubusercontent.com/assets/2932687/13027117/0102de58-d243-11e5-9479-3d4e8f5f6ada.png)

**/currently** view: 
![image](https://cloud.githubusercontent.com/assets/2932687/13027119/1a19e8a0-d243-11e5-8061-5a3878feee33.png)

**Comment by ericpascual** [comment]
Thanks for replying so quickly ;)

What I was calling "dashboard" is the "currently" view. I planned to use it as the live information default display. 

Next point is not related with the initial topic, but while you are at mentioning the "currently" view, it is broken in the last install from pip. A 404 error is returned. I could see that the problem has been fixed in GitHub, but it does not seem to be the case in the version installed with pip. I tried to applied the fix, based on the version on GitHub, but I could not find the involved Python file in my installation (even using the Linux "find" command). I have used the path indicated when issuing : python -c "import shinken ; print(shinken)" as the root of the find command, but I'm obviously not looking at the right place. Any suggestion?

**Comment by mohierf** [comment]
I have not yet published a new release to fix last problems ... I am currently improving/fixing some other problems and I will release a new installable version soon. This version will include more features in the *currently* view ...

To get the last develop version that I updated this morning, you can follow this procedure: https://github.com/shinken-monitoring/mod-webui/wiki/Installation#expert-install-from-the-github-repository. Use this link: https://github.com/shinken-monitoring/mod-webui/archive/develop.tar.gz ... and you wil get the current develop branch version.

If you prefer editing your current files, on a Debian/Ubuntu Linux, the files are located in the */var/lib/shinken/modules/webui2*. You will find the dashboard plugin files in *plugins/dashboard*.

**Comment by ericpascual** [comment]
Thanks. I was not looking at the right place ;)

I'll apply your recommendation when back at work.

**Comment by ericpascual** [comment]
Dev version installed as indicated. It fixes the problem and seems to work ok.

**Comment by mohierf** [comment]
@edouard-lopez : once again many thanks for your time and your remarks. I published a new version 2.3 (soon 2.4) that proposes a new Dashboard currently page including may of your proposals and built with your remarks in mind ... if you have the opportunity to make some comments about it, it will be a pleasure to me :wink:
