### ISSUE TITLE
WebUI2 , MongoDB. You do not have any user's preferences storage module installed.

### ISSUE THREAD

**Issue by gh0stid** [shinken-monitoring/mod-webui#441]
Hello,

sorry for any disturbing, unfortunately I ran into a odd problem ...

ive installed shinken 2.4.2 with pip
su - shinken

installed the webui2 module with shinken install webui2
did the same with mongodb and, configured the .cfg file as intended. 

still... I continue to get that error on the dashboard ?
You do not have any user's preferences storage module installed.

I have absolutely nothing relevent in my log .. Any help would be apreciated please. ( brand new installation on centos7 )

**Comment by jgwinner** [comment]
I've done the same thing and get the same errors.

yum install mongodb
I verified the other requirements:

`[root@shinken1 etc]# pip install pymongo>=3.0.3
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
[root@shinken1 etc]# pip install requests
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.6/site-packages
[root@shinken1 etc]# pip install pymongo
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied (use --upgrade to upgrade): pymongo in /usr/lib64/python2.6/site-packages
[root@shinken1 etc]# pip install arrow
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied (use --upgrade to upgrade): arrow in /usr/lib/python2.6/site-packages
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.6/site-packages (from arrow)
[root@shinken1 etc]# pip install bottle
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied (use --upgrade to upgrade): bottle in /usr/lib/python2.6/site-packages
[root@shinken1 etc]# yum install mongodb
Loaded plugins: security, ulninfo
Setting up Install Process
Package mongodb-2.4.14-1.el6.x86_64 already installed and latest version
Nothing to do
[root@shinken1 etc]#
`
Help! We have a big demo tomorrow :)

== John ==

**Comment by mohierf** [comment]
Your mongodb module is to be configured in webui2.cfg file if you do not have a standard local installation ... did you do it ?

**Comment by gh0stid** [comment]
I did. but finaly the problem was related with centos7 , i believe

what i did, was remove mongodb and install mongodb-org

problem solved. now im strugglin with autodiscovery but it will be another
day, ( tomorrow ) now im off the office.

thank you for the fast reply and support, great to know theres an active
community behind the project.

2016-02-04 16:42 GMT-05:00 Frédéric MOHIER <notifications@github.com>:

**Comment by jgwinner** [comment]
I'm using Oracle Linux, which is more or less CentOS. I'll try that as well.

Didn't work for me:

'[root@shinken1 packs]# yum install mongodb-org
Loaded plugins: security, ulninfo
Setting up Install Process
No package mongodb-org available.'

Poking around further ... 

== John ==

**Comment by jgwinner** [comment]
Ok, I can confirm that on Oracle Linux (CentOS/RHEL), using the mongodb-org DOES work. I can now save user peferences!

installation instructions are here:
[https://docs.mongodb.org/getting-started/shell/tutorial/install-mongodb-on-red-hat/]

**Comment by jgwinner** [comment]
Please update the docs! Seems like a big hole :)

== John ==

**Comment by mohierf** [comment]
Thanks for reporting. 

The doc has been made mainly for Debian/Ubuntu distros, I will update the wiki with your information.

**Comment by mohierf** [comment]
I updated the Wiki page for installing mongodb: https://github.com/shinken-monitoring/mod-webui/wiki/Installing-WebUI-storage-modules

**Comment by jgwinner** [comment]
Thank you! Very nice.

== John ==
