### ISSUE TITLE
Idea function: Historic of criticals events with the duration of downtime

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#445]
Hi,

I noticed a functionality in WebUI that would be interested to implement:
It's to have an "historic of criticals events with the duration of downtime" for a web cluster or other. 

I represented idea with Excel:
![graph2](https://cloud.githubusercontent.com/assets/15362041/13027374/131de524-d24d-11e5-98ce-4b1ad0f4f8ab.PNG)

It's useful to: 
- Determine the service the most defaulting. here it's PHP service
- Have a report easily understandable for a not technician person.
- Compare with other historic and "see" if the cluster has improved or declined in the time.

Explanation: 
This represent a Web cluster with some services (php, Nginx, MySQL, ...). For each service, i have the date and the duration of downtime in hour.
With this graph i can easily determine the service "PHP" has lot of problems. So i need to improve PHP. 
My datas:
![data](https://cloud.githubusercontent.com/assets/15362041/13027387/dbfbbc00-d24d-11e5-9aae-27826489ba59.PNG)

In other monitoring tools (Icinga), there are implement a similar function, but i think it's not complete and not understandable :
![icinga](https://cloud.githubusercontent.com/assets/15362041/13027278/a15a260e-d248-11e5-9f03-661ba5218263.PNG)

Questions:
- What do you think about this functionnality? It's technically easy or hard to implement ? 
- In MongoDB, are there the datas for a service: date of downtime, the name of service, the duration of downtime for a critical event ? If yes, i think i can generate automatically a graph with graphite or grafana.

Do not hesitate to complete this idea.

Thx.

**Comment by mohierf** [comment]
I find this idea really interesting ... I made some tests some months ago with this implementation: https://github.com/shinken-monitoring/mod-webui/issues/53. what do you think about it ?

With the mongo-logs module, you will find many information in the database: service alert, service downtime, ... indeed, all "nagios" log events.

**Comment by Azef1** [comment]
I like the "timeline" plugin, it's interactive and useful but i think it's adapted for a detailed analysis, for example on 1 day, but no for a vast period (1 months or +) because an event is minute/hour long (it's too short). 
I think the stacked bar chart with the timeline together, are two tools complementary.
The advantage of bar chart is nice to do a report. 

Technicaly I did some research: 
For the timeline i doesn't find lot of scripts to do it. But the better is 
[VisJS timeline](http://visjs.org/timeline_examples.html ) I liked interactivity, scroll, zoom, Highly customizable.
![timeline](https://cloud.githubusercontent.com/assets/15362041/13034018/d0e5c04a-d329-11e5-87f1-a7d373df8257.png)

Do you think it's better to do:
- one timeline per one service in service view ? (ex: on PHP service view)
- one general timeline per several services ? (ex: as picture PHP+NGINX+MySQL...)
(i think both is better !)

For the bar chart, i think there are two solutions:
- The graph is generate by javascript (ex [d3.js](https://bl.ocks.org/mbostock/3886208)).
- The graph is generate by graphite/grafana.

I think the second solution is better because the user can cuztomize the graph to these needs. But i don't know if graphite can generate a bar chart and how to send metrics to graphite (the date and duration of downtime for a service). Grafana can generate a bar chart.
And same question: 
- one bar chart per one service ?
- one general bar chart per several services (stack bar chart ) ?
- both ?


Thx

**Comment by maethor** [comment]
Shinken WebUI should be completely independent of graphite and grafana.

I think the current history tab in service and host views contains all the information you need. It's just a matter of presentation.

**Comment by mohierf** [comment]
To be linked with History tab enhancements ... #457
