### ISSUE TITLE
add widget on the dashboard

### ISSUE THREAD

**Issue by ericpascual** [shinken-monitoring/mod-webui#447]
When selecting a widget in the "Add widget" list, the popup is displayed at a position above the top of the page, making its header and the validation button out of reach. The problem seems to occur with some of the widgets only (woldmap for instance)

Problem detected with Chrome/Linux (version: 48.0.2564.109). 
Works with Firefox/Linux

**Comment by mohierf** [comment]
I did not have this problem with FF on Windows ... I will have a look to fix this rapidly!

**Comment by ericpascual** [comment]
As commented, it works fine with FF on Linux too.
