### ISSUE TITLE
Need some special chars encoding on check results

### ISSUE THREAD

**Issue by David-** [shinken-monitoring/mod-webui#452]
Hello,

I check if the search engine work correctly on a website by searching the string "\<h3\>Le recherche " in the HTML response with check_http.
When the search engine is down, check_http return:
`Additional Info : HTTP CRITICAL: HTTP/1.1 200 OK - string '<h3>Le recherche ' not found on 'http://www.groupe-frayssinet.fr:80/content/search?SearchText=ornementaux' - 13268 bytes in 0.205 second response time`
And Webui2 show then:
![2016-02-19 09_02_43-webui](https://cloud.githubusercontent.com/assets/1950676/13170147/5048e4c0-d6ea-11e5-83a8-8f8167d42789.png)
I think HTML special chars should be encoded. Or is it a feature? Maybe some check use this to show HTML-formatted additional infos?

Best regards,
David.

**Comment by mohierf** [comment]
You may try to change the `allow_html_output` parameter in your `webui2.cfg` file ...

This parameter allows WebUI to interpret (or not ...) HTML chars in the checks output.

**Comment by mohierf** [comment]
I suppose it fixed the problem ... closing.
