### ISSUE TITLE
Broker/WebUI is no longer working after few hours (Critical?)

### ISSUE THREAD

**Issue by TomaszUrugOlszewski** [shinken-monitoring/mod-webui#453]
Hello,

Broker/WebUI (not sure which service) stopped working. Broker process is UP, I can login to WebUI, but status of monitored services wasn't updated for 3 hours (Last Check - 3h 24m ago).

I see that poller is still runing checks.

- No broker logs (only that I logged into WebUI)
- I see traffic on 7772 port (attached tcpflow dump)
- I clicked "refresh" from WebUI interface and got error message in logs (attached logs/strace)
- What can be interesting, is that normally I have 2 broker daemons, but now it's only one.

error message after clicking refresh in WebUI:

> [1455912389] INFO: [broker_major] [WebUI-actions] got command: SCHEDULE_FORCED_SVC_CHECK with args: ['XXX, 'Rsnapshot weekly - files_backup', '$NOW$'].
> [1455912389] INFO: [broker_major] [WebUI-actions] external command: [1455912389] SCHEDULE_FORCED_SVC_CHECK;XXX;Rsnapshot weekly - files_backup;1455912389.
> [1455912389] ERROR: [broker_major] [WebUI] External command push, exception: 

strace output after clicking "Refresh":

> 
> Process 15641 attached
> select(7, [6], [], [], {0, 423251}
> 
> )     = 0 (Timeout)
> select(7, [6], [], [], {0, 500000}
> 
> )     = 0 (Timeout)
> select(7, [6], [], [], {0, 500000})     = 0 (Timeout)
> select(7, [6], [], [], {0, 500000})     = 0 (Timeout)
> select(7, [6], [], [], {0, 500000})     = 0 (Timeout)
> select(7, [6], [], [], {0, 500000})     = 1 (in [6], left {0, 220462})
> accept(6, {sa_family=AF_INET, sin_port=htons(56631), sin_addr=inet_addr("127.0.0.1")}, [16]) = 8
> recvfrom(8, "GET /action/SCHEDULE_FORCED_SVC_"..., 8192, 0, NULL, NULL) = 1120
> write(5, "[1455912463] INFO: [broker_major"..., 173) = 173
> write(5, "[1455912463] INFO: [broker_major"..., 175) = 175
> write(11, "\0\0\0\325\200\2(U\f7f77752153b0q\1U\3putq\2(c"..., 217) = -1 EPIPE (Broken pipe)
> --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=15641, si_uid=1013} ---
> write(1, "\33[91m[1455912463] ERROR: [broker"..., 108) = 108
> write(1, "\n", 1)                       = 1
> write(5, "[1455912463] ERROR: [broker_majo"..., 100) = 100
> sendto(8, "HTTP/1.0 200 OK\r\n", 17, 0, NULL, 0) = 17
> sendto(8, "Date: Fri, 19 Feb 2016 20:07:43 "..., 37, 0, NULL, 0) = 37
> sendto(8, "Server: WSGIServer/0.1 Python/2."..., 37, 0, NULL, 0) = 37
> sendto(8, "Content-Length: 147\r\nContent-Typ"..., 55, 0, NULL, 0) = 55
> sendto(8, "jQuery111107984801373404403_1455"..., 147, 0, NULL, 0) = 147
> write(2, "127.0.0.1 - - [19/Feb/2016 21:07"..., 336) = 336
> shutdown(8, SHUT_WR)                    = 0
> close(8)                                = 0
> select(7, [6], [], [], {0, 500000})     = 0 (Timeout)
> select(7, [6], [], [], {0, 500000})     = 0 (Timeout)
> select(7, [6], [], [], {0, 500000})     = 0 (Timeout)
> select(7, [6], [], [], {0, 500000})     = 0 (Timeout)

Lsof output for this process (Especialy descriptor 11)

> COMMAND     PID    USER   FD   TYPE  DEVICE SIZE/OFF      NODE NAME
> python2.7 15641 shinken  cwd    DIR    0,15      200     17922 /run/shinken
> python2.7 15641 shinken  rtd    DIR   253,0     4096       128 /
> python2.7 15641 shinken  txt    REG   253,0  3785928    143254 /usr/bin/python2.7
> python2.7 15641 shinken  mem    REG   253,0    35176  68104967 /lib/x86_64-linux-gnu/libcrypt-2.19.so
> python2.7 15641 shinken  mem    REG   253,0     6664    144771 /usr/lib/python2.7/lib-dynload/crypt.x86_64-linux-gnu.so
> python2.7 15641 shinken  mem    REG   253,0    23232 102114119 /usr/lib/python2.7/dist-packages/pymongo/_cmessage.x86_64-linux-gnu.so
> python2.7 15641 shinken  mem    REG   253,0    43680  67391870 /usr/lib/python2.7/dist-packages/bson/_cbson.x86_64-linux-gnu.so
> python2.7 15641 shinken  mem    REG   253,0    18904  67236177 /lib/x86_64-linux-gnu/libuuid.so.1.3.0
> python2.7 15641 shinken  mem    REG   253,0   141184    144723 /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
> python2.7 15641 shinken  mem    REG   253,0    11248    144782 /usr/lib/python2.7/lib-dynload/resource.x86_64-linux-gnu.so
> python2.7 15641 shinken  mem    REG   253,0    47712  68105106 /lib/x86_64-linux-gnu/libnss_files-2.19.so
> python2.7 15641 shinken  mem    REG   253,0    43592  68105115 /lib/x86_64-linux-gnu/libnss_nis-2.19.so
> python2.7 15641 shinken  mem    REG   253,0    89104  68105069 /lib/x86_64-linux-gnu/libnsl-2.19.so
> python2.7 15641 shinken  mem    REG   253,0    31632  68105081 /lib/x86_64-linux-gnu/libnss_compat-2.19.so
> python2.7 15641 shinken  mem    REG   253,0    31784   1235727 /usr/lib/python2.7/dist-packages/Crypto/Cipher/_AES.x86_64-linux-gnu.so
> python2.7 15641 shinken  mem    REG   253,0    29464    144728 /usr/lib/python2.7/lib-dynload/_hashlib.x86_64-linux-gnu.so
> python2.7 15641 shinken  mem    REG   253,0  2062720  33554759 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
> python2.7 15641 shinken  mem    REG   253,0   392312  33554760 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
> python2.7 15641 shinken  mem    REG   253,0    97872    144735 /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so
> python2.7 15641 shinken  mem    REG   253,0    72136  67217659 /lib/x86_64-linux-gnu/libgpg-error.so.0.13.0
> python2.7 15641 shinken  mem    REG   253,0    31048  33687290 /usr/lib/x86_64-linux-gnu/libffi.so.6.0.2
> python2.7 15641 shinken  mem    REG   253,0   113520  33687360 /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
> python2.7 15641 shinken  mem    REG   253,0    84856  68210951 /lib/x86_64-linux-gnu/libresolv-2.19.so
> python2.7 15641 shinken  mem    REG   253,0    14256  67236130 /lib/x86_64-linux-gnu/libkeyutils.so.1.5
> python2.7 15641 shinken  mem    REG   253,0    48088  33686290 /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
> python2.7 15641 shinken  mem    REG   253,0   924096  67413115 /lib/x86_64-linux-gnu/libgcrypt.so.20.0.3
> python2.7 15641 shinken  mem    REG   253,0   537248  33687304 /usr/lib/x86_64-linux-gnu/libgmp.so.10.2.0
> python2.7 15641 shinken  mem    REG   253,0   191960  33687316 /usr/lib/x86_64-linux-gnu/libhogweed.so.2.5
> python2.7 15641 shinken  mem    REG   253,0    80384  33687368 /usr/lib/x86_64-linux-gnu/libtasn1.so.6.3.2
> python2.7 15641 shinken  mem    REG   253,0   285104  33687346 /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.0.0
> python2.7 15641 shinken  mem    REG   253,0   327088  33695743 /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.3
> python2.7 15641 shinken  mem    REG   253,0    59576  33815731 /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.3
> python2.7 15641 shinken  mem    REG   253,0    14640  67217644 /lib/x86_64-linux-gnu/libcom_err.so.2.1
> python2.7 15641 shinken  mem    REG   253,0   195400  33686719 /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
> python2.7 15641 shinken  mem    REG   253,0   867776  33686287 /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
> python2.7 15641 shinken  mem    REG   253,0   306072  33686264 /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
> python2.7 15641 shinken  mem    REG   253,0   203520  33687343 /usr/lib/x86_64-linux-gnu/libnettle.so.4.7
> python2.7 15641 shinken  mem    REG   253,0   167112  33687365 /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1
> python2.7 15641 shinken  mem    REG   253,0   122168  33687359 /usr/lib/x86_64-linux-gnu/librtmp.so.1
> python2.7 15641 shinken  mem    REG   253,0   211344  33687325 /usr/lib/x86_64-linux-gnu/libidn.so.11.6.12
> python2.7 15641 shinken  mem    REG   253,0  1173320  33687305 /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28.41.0
> python2.7 15641 shinken  mem    REG   253,0   444832  34290067 /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.3.0
> python2.7 15641 shinken  mem    REG   253,0    99560   1328531 /usr/lib/python2.7/dist-packages/pycurl.x86_64-linux-gnu.so
> python2.7 15641 shinken  mem    REG   253,0    54248    144730 /usr/lib/python2.7/lib-dynload/_json.x86_64-linux-gnu.so
> python2.7 15641 shinken  mem    REG   253,0    33736    144733 /usr/lib/python2.7/lib-dynload/_multiprocessing.x86_64-linux-gnu.so
> python2.7 15641 shinken  mem    REG   253,0  3345792    525239 /usr/lib/locale/locale-archive
> python2.7 15641 shinken  mem    REG   253,0  1738176  68104960 /lib/x86_64-linux-gnu/libc-2.19.so
> python2.7 15641 shinken  mem    REG   253,0  1051056  68104984 /lib/x86_64-linux-gnu/libm-2.19.so
> python2.7 15641 shinken  mem    REG   253,0   109144  67236179 /lib/x86_64-linux-gnu/libz.so.1.2.8
> python2.7 15641 shinken  mem    REG   253,0    10680  68210974 /lib/x86_64-linux-gnu/libutil-2.19.so
> python2.7 15641 shinken  mem    REG   253,0    14664  68104980 /lib/x86_64-linux-gnu/libdl-2.19.so
> python2.7 15641 shinken  mem    REG   253,0   137440  68104935 /lib/x86_64-linux-gnu/libpthread-2.19.so
> python2.7 15641 shinken  mem    REG   253,0   140928  68104953 /lib/x86_64-linux-gnu/ld-2.19.so
> python2.7 15641 shinken    0r   CHR     1,3      0t0      1028 /dev/null
> python2.7 15641 shinken    1u   CHR     1,3      0t0      1028 /dev/null
> python2.7 15641 shinken    2u   CHR     1,3      0t0      1028 /dev/null
> python2.7 15641 shinken    3r   CHR     1,9      0t0      1033 /dev/urandom
> python2.7 15641 shinken    4u  IPv4 9500146      0t0       TCP localhost:51518->localhost:27017 (ESTABLISHED)
> python2.7 15641 shinken    5w   REG   253,2     7288  67109011 /var/log/shinken/brokerd.log
> python2.7 15641 shinken    6u  IPv4 9504886      0t0       TCP *:7767 (LISTEN)
> python2.7 15641 shinken    7u   CHR     1,3      0t0      1028 /dev/null
> python2.7 15641 shinken   11u  sock     0,7      0t0   9516151 can't identify protocol

tcpflow output:

> 127.000.000.001.54845-127.000.000.001.07772: POST /push_broks HTTP/1.1
> User-Agent: shinken:2.4.2 pycurl:7.38.0
> Host: localhost:7772
> Accept: */*
> Keep-Alive: 300
> Connection: Keep-Alive
> Content-Length: 154
> Content-Type: multipart/form-data; boundary=------------------------0000000000000000
> 
> 
> 127.000.000.001.54845-127.000.000.001.07772: --------------------------0000000000000000
> Content-Disposition: form-data; name="broks"
> 
> x^H)0f
> --------------------------0000000000000000--
> 
> 127.000.000.001.07772-127.000.000.001.54845: HTTP/1.0 200 OK
> 
> 127.000.000.001.07772-127.000.000.001.54845: Date: Fri, 19 Feb 2016 20:03:29 GMT
> 
> 127.000.000.001.07772-127.000.000.001.54845: Server: WSGIServer/0.1 Python/2.7.9
> 
> 127.000.000.001.07772-127.000.000.001.54845: Content-Length: 4
> Content-Type: text/html; charset=UTF-8
> 
> 
> 127.000.000.001.07772-127.000.000.001.54845: null
> 127.000.000.001.54847-127.000.000.001.07772: GET /ping? HTTP/1.1
> User-Agent: shinken:2.4.2 pycurl:7.38.0
> Host: localhost:7772
> Accept: */*
> Keep-Alive: 300
> Connection: Keep-Alive
> 
> 
> 127.000.000.001.07772-127.000.000.001.54847: HTTP/1.0 200 OK
> 
> 127.000.000.001.07772-127.000.000.001.54847: Date: Fri, 19 Feb 2016 20:03:29 GMT
> 
> 127.000.000.001.07772-127.000.000.001.54847: Server: WSGIServer/0.1 Python/2.7.9
> 
> 127.000.000.001.07772-127.000.000.001.54847: Content-Length: 6
> Content-Type: text/html; charset=UTF-8
> 
> 
> 127.000.000.001.07772-127.000.000.001.54847: "pong"
> 127.000.000.001.54849-127.000.000.001.07772: GET /get_external_commands? HTTP/1.1
> User-Agent: shinken:2.4.2 pycurl:7.38.0
> Host: localhost:7772
> Accept: */*
> Keep-Alive: 300
> Connection: Keep-Alive

**Comment by mohierf** [comment]
I think the the WebUI is not faulty ...

The exception log when pushing an external command indicates to me that the receiving process for the command is dead. I suppose that it is your main broker that is dead ... this will also explain why the checks are still executing but there is no more data refresh for the WebUI, because there is no more broker to receive broks to update the data.

 You should have a look in all the logs if you find some more logs that may explain this behavior ?

**Comment by TomaszUrugOlszewski** [comment]
Problem no longer exists, after upgrading pycurl. Closing

*Solution*
If you use Debian Jessie, remove with apt-get python-pycurl, and install it using pip

**Comment by mohierf** [comment]
Thanks for reporting ... I will update to install pycurl with pip
