### ISSUE TITLE
Feature Request - If MongoDB is down during configuration propagation, try again later

### ISSUE THREAD

**Issue by TomaszUrugOlszewski** [shinken-monitoring/mod-webui#455]
Hi,

If MongoDB is run after Shinken, WebUI never retries connection, and MongoDB is not used. It needs to be reconfigured by arbiter reload.

Maybe it would be nice idea to retry MongoDB connection on each login? Of course with some small timeout.

**Comment by maethor** [comment]
Should be fixed by now.
