### ISSUE TITLE
Check interval in minute instead of second

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#456]
Hi,
I have a little bug:
![minute](https://cloud.githubusercontent.com/assets/15362041/13489656/8f1b0906-e128-11e5-9130-44a78002680f.png)

In my conf service `check_interval` is set to 30 and `retry_interval` to 10; in the documentation this number is second.
You can notice Last_check+Next active check =30, so  is correct.
Why, the WebUI displays the Check interval and Retry interval in minute ?

Thx

**Comment by mohierf** [comment]
It is simply a display bug in the WebUI ... that displays *minutes* instead of *seconds* :/

**Comment by mohierf** [comment]
Fixed in version 2.3
