### ISSUE TITLE
Improvement Availability tabs: 

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#458]
Hi,

I propose some ideas to improve availability tabs for hosts and services:
- Display the duration of downtime because the percentage is sometimes incomprehensible :
![minute](https://cloud.githubusercontent.com/assets/15362041/13566813/b67131ce-e457-11e5-87f9-af82fc51740a.png)
- Select date range to display availability between two dates (ex: display availability between 4 january and 8 feburary)
- Send availability metrics to graphite to generate a history graph. It's a matter presentation for availability but it's more easily to understand. For example, i can see day by day the duration of downtime.
`Metric format: <name of metric> <duration downtime> <date>`
See [this website](http://obfuscurity.com/2012/04/Unhelpful-Graphite-Tip-1) to do Staircase Line with graphite

Compilation ideas:
![illustration](https://cloud.githubusercontent.com/assets/15362041/13567469/c5f84250-e45b-11e5-80a3-9cc43d08c738.png)

-> In availability tabs, the "Schedule downtime" and SOFT check are include to calculate the availability ? 

What do you think  ? It's technically possible  ?

**Comment by maethor** [comment]
Hi,

Thanks for theses suggestions.

The idea of displaying the duration of downtime is nice, and should not be difficult to implement. So I completely agree.

About the graph, the webui should stay independant of graphite (because some of us are using pnp4nagios), so I don't think it would be possible to do it like you propose. But I think we could use some js library do display. It should be possible.

I'll let @mohierf answer your last question :)

**Comment by mohierf** [comment]
I must have a look to this but currently have not much time ... I let this issue opened to work on enhancements on this tab.

**Comment by Azef1** [comment]
Thx for having kept these enhancements. 
I have a question: I would like to calculate the duration of critical downtime for one service, so i have looked the availability log in mongodb. But i don't understand some attributes.

Little example of availability log : [http://pastebin.com/7xSed7hN](http://pastebin.com/7xSed7hN)

What is : 
- daily_0
- daily_1
- daily_2
- daily_3
- daily_4
- first_check_state // It's a number
- first_check_timestamp //It's a date in timestamp format
- is_downtime // Always 0 ?

What is the mathematical formula to calculate the duration of critical downtime ?

thx again

**Comment by mohierf** [comment]
As a brief and quick explanation (sorry, not much time currently ...):
- each document in the collection stores daily counters (*day*) for an host (*hostname*) or service (*service*) 
- the fields *daily_X* are containing a number of seconds in the X state for the current day
- 0, 1, 2 and 3 are UP, DOWN, UNREACHABLE, UNKNOWN for an host and OK, WARNING, CRITICAL, UNKNWON for a service
- 4 is for a the not checked seconds of the day (duration between 00:00:00: and the first check of the day
 - the *first_check_state* and *last_check_state* contain the state of the host/service when first/last check results got received 
 - the *first_check_timestamp* and *last_check_timestamp* contain the timestamp when the first/last check results got received 


 This algorithm is not very precise but is quite simple to implement and allows to avoir storing a lot of information to compute simple ratio 

 I hope it helps to understand ... alse do not hesitate to ask for more information

**Comment by Azef1** [comment]
Thank you very much.
I think i have find a mistake, but can you confirm that:
In [plugins/availability/views/_availability_graph.tpl](https://github.com/shinken-monitoring/mod-webui/blob/develop/module/plugins/availability/views/_availability_graph.tpl) the script is used for host AND service, it's the same. Currently, the availability is compute with value of **daily_1**   `%t_1=int(log['daily_1']) [...]  title="Down {{t_1}} seconds"`. It's correct for an host but not for a service because an availability for a service should use the value of **daily_2** (Critical value).
So, 
- host availabilty with  value of **daily_1** 
- host availabilty with  value of **daily_2** 

If you confirm me it's a bug, i can provide you a fix.

**Comment by Azef1** [comment]
Hi, 
In which script WebUI write an avaibility line in mongoDB ? 
My goal is to write avaibility line in Elasticsearch too, for a personal use (write availabiliy in mongoDB AND ElasticSearch). 
Thx again

**Comment by mohierf** [comment]
The WebUI does not write any availability log ... it is the job of this module: https://github.com/shinken-monitoring/mod-mongo-logs

Moreover, @descrepes developed an ES logs module that you will find here: https://github.com/descrepes/mod-elastic-logs. This module allows to store logs in an ES instance ...

**Comment by mohierf** [comment]
@Azef1 : what should we finally keep in this issue? As of it, only the duration indicated under the availability graph ... do you confirm?

**Comment by Azef1** [comment]
Thx for all, Yes i confirm:
- the duration under the availability graph should be nice,
- If possible, add a form "Select date range" to display availability between two dates chosen by the user.
Also, could you tell me if a bug or not about my message from 16 march [here](https://github.com/shinken-monitoring/mod-webui/issues/458#issuecomment-197402393) (_availability_graph.tpl currently compute with daily_1 for host ad service).

**Comment by mohierf** [comment]
Concerning your comment dated as March 16th, I just had a look and I think that there really is a problem ... but not the one you mention :/

 The availability duration stored is to be considered as:

- daily_0: duration of state UP (host) or OK (service)
- daily_1: duration of state DOWN (host) or WARNING (service)
- daily_2: duration of state UNREACHABLE (host) or CRITICAL (service)
- daily_3: duration of state UNKNOWN (host and service)
- daily_4 : 86400 seconds minus (daily_0 + daily_1 + daily_2 + daily_3)

 Currently, availability duration is computed using only `daily_1` ... which means that:
 - for an host, we only consider the DOWN state and not the UNREACHABLE one ...
 - for a service, we only consider the WARNING state and not the CRITICAL one ...

 @maethor : please should you confirm this analysis?

**Comment by mohierf** [comment]
To keep tracking about this:
- an element may have some custom variables to define Warning and Critical thresholds for availability
- _SLA_WARN (defaults to 99) is the threshold for a warning on availability
- _SLA_CRIT (defaults to 95) is the threshold for a critical on availability

Graph legend:
- if availability is more than _SLA_WARN, graph is coloured with green
- if availability is between _SLA_CRIT and _SLA_WARN, graph is coloured with orange
- if availability is lower than _SLA_CRIT, graph is coloured with red

**Comment by Azef1** [comment]
I close issue because there are a lot of improvements for availability in WebUI 2.4.1
