### ISSUE TITLE
Display name not used in all views

### ISSUE THREAD

**Issue by efficks** [shinken-monitoring/mod-webui#466]
Views problem and minemap does not use displayname for the hostname.

**Comment by pedrojimenez** [comment]
We are facing the same feature. 
All efforts in configure these display names, but not shown at any view in all the WebUI2.

+1

**Comment by mohierf** [comment]
Ok. The views in the WebUI use the Shinken get_name() function that do not always care about display_name property ... I will implement the following rules in the WebUI: 
 - If `display_name` is defined, it will be used
 - If not and `alias` is defined, it will be used,
 - If not, `host_name` / `service_description` will be used
