### ISSUE TITLE
Little CSS bug on business rule page

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#468]
Hi,
I inform you a little bug css: the red circle isn't center:
Currently:
![circle](https://cloud.githubusercontent.com/assets/15362041/14020753/d67d7156-f1d8-11e5-9bcb-f1cc0a93299f.PNG)
After changing two values in pulse.css:
![circle2](https://cloud.githubusercontent.com/assets/15362041/14020802/074fc0ea-f1d9-11e5-8b7d-d384b27dbef3.PNG)

> .pulse {
    [...]
    left: -8px; #before -3px
    top: -6px; #before -3px
}

**Comment by mohierf** [comment]
Thanks.

**Comment by Azef1** [comment]
Fixed in webUI2.3.2. I close issue
Thx
