### ISSUE TITLE
currently cause a 404

### ISSUE THREAD

**Issue by nicodmf** [shinken-monitoring/mod-webui#469]
Hello, 

I don't know why but currently cause a 404 on my fresh installation : 

Error: 404 Not Found  Sorry, the requested URL 'http://xxx:17667/dashboard/currently' caused an error

Is it an error in code or in my configuration ?

Best Regards,

Nicolas

**Comment by mohierf** [comment]
Are you sure about 17667 in your URL ? Default port is 7767 ...

**Comment by nicodmf** [comment]
i'm sure, i nat the port and specifiy it in case this is the problem

**Comment by mohierf** [comment]
Ok, I will have a look rapidly for this but I do not have this problem currently on my testing environment.

**Comment by lestercheung** [comment]
I've upgraded from webui to webui2 and have the same problem as well.

**Comment by lestercheung** [comment]
Hi @mohierf ,

I've replaced the /var/lib/shinken/modules/webui2 with the one in the repo and it started working again. Seems the package in shinken.io is broken somehow.

FWIW, the repo has the following extra files:

    [root@shinken tmp]# diff old new
    94a95
    > webui2/htdocs/images/shinken-sm.png
    332a334
    > webui2/plugins/helpdesk/htdocs/img/widget_helpdesk.png
    333a336
    > webui2/plugins/helpdesk/views/add_ticket_followup.tpl
    334a338
    > webui2/plugins/helpdesk/views/_helpdesk.tpl
    335a340
    > webui2/plugins/helpdesk/views/helpdesk_widget.tpl
    363a369
    > webui2/plugins/minemap/htdocs/js/jquery.floatThead.min.js
    370a377
    > webui2/plugins/problems/htdocs/img/widget_last_problems.png

Have a nice day!

**Comment by mohierf** [comment]
Thank you for the feedback :+1: 

I will publish a new release in some few days ...

**Comment by pedrojimenez** [comment]
404 in Currently view no longer appears in the 2.3.2 version

Also let me comment that i am enloved with this new vision of the Dashhboard. Very very clean and all the displayed info is really useful and accesible.

Just a question ... the older style of Currently is going to dissapear? 
I used to display it in a big TV but the new version does not fit in a fullhd resolution.

Thanks anyway for the great refactoring job ;)

**Comment by mohierf** [comment]
Thanaks for your comment.

I made this refactoring thanks to the comments of @edouard-lopez (issue #440).

To better understand your remarks:
1/ Which information is missing you in the former Currently view?
2/ This new interface is responsive. As of it, it should fit in your screen ... what is the problem? A screen capture should be helpful ...

**Comment by pedrojimenez** [comment]
Hi @mohierf ... the older style fitted all the info in the browser screen, with no scroll.

This is one of my "currently" views with the 2.3.2 version, where the bottom timeline graphs ("Hosts/Services states monitoring") dont fit in a simple screen. I mean a full compact view grouping all the info / graphs to be displayed in a big screen.
![seleccion_213](https://cloud.githubusercontent.com/assets/1044532/14601115/86f52034-0560-11e6-8812-78ce330162ca.png)

**Comment by mohierf** [comment]
Ok, I understand. 

Have you tried to collapse the panels in this view? Each panel is collapsible thanks to the top right +/- button ...

My idea, for a next version, is to make it possible to hide/show each panel in the view ...

**Comment by pedrojimenez** [comment]
Really love the collapse options ... I am addict to this new grouped information (favourite landing?) I think this view is perfect for a user/operator but not for a screen cast.

It might contain all the panels so everyone at distance could oversee the realm status

**Comment by mohierf** [comment]
**1/** I do not think that making this view become the favorite landing is the best idea ... I believe, rather, that I should use the same design and layout for the WebUI Dashoard view. And, why not, allow the user to define his own Dashboard views (*à la Kibana*).

**2/** Having such a view to fit perfectly with the screen height is not that easy ... but the idea is really interesting! 
 It raises some design problems. The first one is: which screen resolution is the best suitable? And what to do with the other heights? And what to do if all elements do not suit in the defined heights? 

 It is not really easy and the best solution I found was to make panels collapsible... as of it, anyone, can choose to display or not some information.

 I am listening to any idea that will make this view still better ... please do not hesitate to comment!

**Comment by pedrojimenez** [comment]
HI @mohierf i agree with you in both cases. 

**1** was just a comment, I also think the landing page is perfect with the current style, allowing each user to define the desired tabs/widgets for their needs.

**2** Sorry for the misunderstood, imho the new "currently" view is marvellous and the collapse options helps every user to keep in their screens the desired displayed information. All the work in the responsive view looks really great.

I was talking about adding an additional view (as idea), to fit fullscreen resolutions, like the old currently style, omitting the panels and showing just "date/time" + "text info" or maybe the Donuts

**Comment by mohierf** [comment]
Once again, thanks for the feedback.

I keep in mind this idea of fullscreen view as you suggest for a next version.
