### ISSUE TITLE
Downtime page error

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#471]
Hi,
When i schedule a downtime on few services, i can't to access on services page concerned:
![capture2](https://cloud.githubusercontent.com/assets/15362041/14148573/398a6030-f6a0-11e5-9423-38263eec4832.PNG)

In my service name, there are whitespace and "-" (eg: XXXX - XXXXX)
I using Shiken: 2.4 and WebUI 2.2.1

**Comment by mohierf** [comment]
Last version 2.3 should solve this, if not, please reopen this issue
