### ISSUE TITLE
WebUI2 version and Shinken.io

### ISSUE THREAD

**Issue by Dual-Boot** [shinken-monitoring/mod-webui#478]
Hello,

It seems that webui2 in version 2.3.1 is out but but on shinken.io site it is still the 2.2.0 available.
And the search shinken command also show 2.2.0.

 And the github documentation says 2.3.1 is available on shinken.io .

Maybe shinken.io site needs an update ?

 Regards,

**Comment by mohierf** [comment]
You are right ... I prepared a new version that is available in the `develop` branch but I am still testing this version vbefore publishing soon in the shinken.io

**Comment by Dual-Boot** [comment]
Thank you for the precision.

**Comment by mohierf** [comment]
Version 2.3.2 published on shinken.io

**Comment by Dual-Boot** [comment]
Just to say : it's OK now
Thank you
