### ISSUE TITLE
Always 404 error when Graphite image is not available

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#481]
See this previous issue in UI-Graphite module: https://github.com/shinken-monitoring/mod-ui-graphite/issues/17

**Edit**: copy of the initial issue

> If the module internally fails to load Graphite images with HTTP 401 "Unauthorized" error, then in pages like /host/$HOST or /service/$HOST/$SERVICE, requests for image resources underURLs like /graph?url=$GRAPHITEURL fail as expected. Unfortunately they raise a wrong and misleading errors -- Shinken webui return a 404 "Not found" error, providing the additional message "image not found".
> 
> I think the HTTP error or at least the explicating message should be set more appropriately.

**Comment by mohierf** [comment]
If the response status code is not 200, the WebUI graph proxy may return an HTTP response with the same code as the one provided by Graphite? The response content is `application/json` and contains an object such as:
```
{
   'status': 'ko',
   'message': **content of the Graphite HTTP response content**
}
``` 

This will allow to examine the Graphite reponse with any browser developer tools ...

**Comment by starouille** [comment]
hum i have the same issue.. since i upgrade to latest shinken web-ui + latest shinken last month + ubuntu 16.04.

i installed graphite2 / ui-graphite2 instead of graphite/ui-graphite but same issue..

/graph?url=     fail every time.. 404...
/render url from graphite base url works and graphite UI too.. and all data are here..

I don't understand :/ Are you sure it's not a proxy bug or something else?

**Comment by mohierf** [comment]
As you can see here: https://github.com/mohierf/mod-webui/commit/738e503d0982fb901e2b75889567f55ebdb31de0#diff-91c20c308ad9e05838f114807d2aad3cR46, there is now an ERROR log that will be raised if an error occurs. Please check you `brokerd.log` file and copy it here ...

**Comment by soujak** [comment]
That's very good! Thank you very much.

I guess this issue can now be closed.
