### ISSUE TITLE
Some dashboard counters are incorrects

### ISSUE THREAD

**Issue by achaussier** [shinken-monitoring/mod-webui#482]
Hello,

I use your last release (2.3.2) and I've incorrect values for some dashboard counters.
![webui_counter_problems](https://cloud.githubusercontent.com/assets/975453/14587010/4787f748-04aa-11e6-92a8-3e15016b5993.png)

I've 11 warning services but :
* bad 100% ok services counter
* on top, we see 0 for the service icons, we should see the non ok services count ?

**Comment by mohierf** [comment]
It may be quite disappointing but no ... you should see the count of the "problem" services that are not acknowledged or downtimed.

When you hover with your mouse, what are the displayed counters for the hosts and services?

**Comment by achaussier** [comment]
Hello,

I've no downtime or acknowledge these errors.
- when I click on the service link between hosts and problem links, I see my warnings on the top of page
- When I hover the top service icon, I can see these errors :
![webui_counter_problems_2](https://cloud.githubusercontent.com/assets/975453/14593947/11c6a71c-0531-11e6-9de3-db29a0a1f014.png)

**Comment by mohierf** [comment]
Ok, so you should not have 0 in the header bar counter ... I will have a look on my testing environment!

The WebUI simply displays the number of services seen as "problems" by Shinken ... aqs of it I hope that the Shinken behavior to detect a service as a problem has not changed :/ 

Which version of Shinken are you using ?

**Comment by achaussier** [comment]
I use the last Shinken version : 2.4.3

**Comment by mohierf** [comment]
I made a few more tests on a fresh configuration and it seems that a faulty service is not considered as a problem by Shinken as soon as it is detected as not OK ... 

 Indeed, the counters displayed in the header bar count the services with an `is_problem` flag and this internal object property is not set by Shinken even when the faulty service is in an HARD state. The WebUI problems page do not use this flag but searches for the services that are matching a filter (eg. `isnot:UP isnot:OK isnot:PENDING isnot:ACK isnot:DOWNTIME bp:>0`) ... and this is why the display is not consistent !

 I will change the counting strategy to make the UI more consistent ...

**Comment by mohierf** [comment]
I also noticed that when I `recheck` a faulty service through the WebUI, then the service is considered as a problem ... which means that external commands received by Shinken make the `is_problem` flag updated whereas the normal service scheduling does not  :/

**Comment by mohierf** [comment]
Fixed with version 2.4

**Comment by achaussier** [comment]
Thanks, I'll get it today.
