### ISSUE TITLE
Can't add all widgets

### ISSUE THREAD

**Issue by alexstaz** [shinken-monitoring/mod-webui#487]
![image](https://cloud.githubusercontent.com/assets/5681800/14612647/953d3a2c-0598-11e6-952b-cac6ef86ef69.png)

I can only see 8 of the 9 widgets.
The widget notification toggle is masked by the footer bar (Sinken 2.4.3 etc ...)
I have tested it with latest chrome & firefox.

![image](https://cloud.githubusercontent.com/assets/5681800/14614190/3e9c20b8-05a0-11e6-8384-d2584940d031.png)
It's not full displayed as you can see when I put the div in code analyzer.

**Comment by mohierf** [comment]
Ok ... understood! Thanks for reporting ... this should have been fixed in a previous version!

**Comment by alexstaz** [comment]
Thanks to you for your work and correct all problems ;)

**Comment by mohierf** [comment]
On dashboard page: 
![image](https://cloud.githubusercontent.com/assets/2932687/14624481/574594ce-05db-11e6-983a-b803aedd1570.png)

![image](https://cloud.githubusercontent.com/assets/2932687/14624486/63d914c2-05db-11e6-9d8c-b26592b36e48.png)

**Comment by mohierf** [comment]
Fixed with version 2.4
