### ISSUE TITLE
WebUI 2.4.0: Hosts Services groups empty

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#489]
Hi, 

The new version it's nice, but i have a strange problem: All my hostsgroup and servicesgroup are empty.
With 2.2.1 i haven't this problem.

How i could help you to find the source of problem

**Comment by mohierf** [comment]
@Azef1 : thanks for reporting and your proposal. 

Is is the same issue as #474 and I already managed to fix this regression. You will find a fix here:https://github.com/mohierf/mod-webui/commit/7371ec4f01898978131430e05939462cc1f6cabb
