### ISSUE TITLE
Some improvements in the "currently view"

### ISSUE THREAD

**Issue by pedrojimenez** [shinken-monitoring/mod-webui#491]
Hi, 
When operating in the new currently view, the second raw, responsible of showing the percents values for hosts/services in its own column/widget, is always displaying them in the same colour.

Also there are some minor responsive overlapping with big numbers.

![seleccion_217](https://cloud.githubusercontent.com/assets/1044532/14736962/0afe1c70-087a-11e6-8139-912407f24546.png)

**Comment by mohierf** [comment]
The icon color is based on the percentage value and is defined thanks to visual alerting threshold parameters defined in the *webui2.cfg* configuration file: `hosts_states_critical`, `hosts_states_warning`. (And `services_states_critical`, `services_states_warning` for the services icons).

 It is far from being the best strategy to display some kind of hosts/services SLA ... it is naively inherited from the previous currently view :/

 I moked-up a new hosts panel view:
![image](https://cloud.githubusercontent.com/assets/2932687/14738305/14ac9088-0881-11e6-8aad-73db02f9f141.png)

 The left icon is coloured depending upon the percentage and the SLA level defined in the configuration: 
 - green if percentage >= `hosts_states_warning`
 - else, orange if percentage >= `hosts_states_critical`
 - else, red

 Percentage is the percentage of non OK hosts (DOWN, UNREACHABLE, UNKNOWN) wether they are acknowledged/downtimed or not. Indeed, it is 100% minus percentage of hosts UP!

**Comment by mohierf** [comment]
Included in version 2.4.1
