### ISSUE TITLE
Error 500 on services-tags page (WebUI 2.4.1)

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#492]
Hi,

I inform you an error 500 on `/services-tags` page.

![error500](https://cloud.githubusercontent.com/assets/15362041/14742007/4136efea-089a-11e6-9ba7-c2d497f000f9.png)

Thx,

**Comment by mohierf** [comment]
I do not have this error ...

What is your Shinken version ? 
What are the tags you are using ?

**Comment by Azef1** [comment]
I using shinken 2.4.2.
I defined tags in templates.
For `hosts-tags` page no error but `services-tags` i have error 500.
Exemple of my service template "
```
 define service {
    name                  generic-service
    service_description   generic-service
    is_volatile           0
    max_check_attempts    2
    check_interval        300
    retry_interval        60
    active_checks_enabled 1
    passive_checks_enabled 1
    check_period          24x7
    obsess_over_service   1
    check_freshness       1
    freshness_threshold   3600
    flap_detection_enabled 0
    process_perf_data     1
    retain_status_information 1
    retain_nonstatus_information 1
    notification_interval 3600
    first_notification_delay 0
    notification_period   24x7
    notifications_enabled 1
    register              0
  }

```

**Comment by mohierf** [comment]
Ok. I am using Shinken 2.4.3 and I do not have any service tags at all !

I am suspecting a bug in the Shinken framework with services tags ... :angry:  ... like for the recent groups issue!

I will investigate

**Comment by mohierf** [comment]
I found the bug in Shinken and I also included a protection against this in Web UI ... I will commit soon.

**Comment by Azef1** [comment]
You are a genius!

**Comment by mohierf** [comment]
Thanks. I am only able to dive into the awfull mess of Shinken objects source code ... :angry:

**Comment by julienbenoist** [comment]
same error for me with shinken 2.4.3 and webui 2.4.1

**Comment by mohierf** [comment]
@julienbenoist : Give a try to https://github.com/mohierf/mod-webui/commit/cb6a6b585443fb5ded5089785817cf446c578b62

**Comment by julienbenoist** [comment]
oui c'est bon maintenant j'avais pas vu le fix avant merci

**Comment by Azef1** [comment]
Thx i installed your version and it's works !!!!
