### ISSUE TITLE
Minor errors navigating in WebUI2

### ISSUE THREAD

**Issue by pedrojimenez** [shinken-monitoring/mod-webui#494]
Hi again, 

Part I. ) 
I have found some link diffs navigating in the currently view. I think that the links in the _blue "unknown" part_ might match the same numeric value with the corresponding percent value. Also i want to propose a name changing: "known problems" by "unknown problems"
<pre>
Services:
http://10.x.x.x:7767/all?search=type:service%20is:unknown%20isnot:ack%20isnot:downtime
http://10.x.x.x:7767/all?search=type:service%20is:ack

Hosts:
http://10.x.x.x:7767/all?search=type:host%20is:unknown%20isnot:ack%20isnot:downtime
http://10.x.x.x:7767/all?search=type:host%20is:ack
</pre>

These are the captures:

![seleccion_220](https://cloud.githubusercontent.com/assets/1044532/14814478/c13c11fc-0ba6-11e6-9be9-3d150c96dbbb.png)

![seleccion_221](https://cloud.githubusercontent.com/assets/1044532/14814492/cd780ce6-0ba6-11e6-848c-4587222ba1a8.png)

Part II. ) 
In the bottom part all pages of the WebUI2 the footer is too large and overlaps the paging links. I think it has an undesired extra line.

![seleccion_219](https://cloud.githubusercontent.com/assets/1044532/14814701/b4a5a416-0ba7-11e6-90b6-7d9d3ce5d06a.png)

Part III. ) 
The PnP4nagios graphs for checking hosts (pings) are only displayed in the problematics hosts, but in the inner part of the host is correctly showed.

![seleccion_218](https://cloud.githubusercontent.com/assets/1044532/14814573/28bccd6c-0ba7-11e6-8e61-3a86ef58eb80.png)

Also with the some services with "0%" returned perfdata

![seleccion_222](https://cloud.githubusercontent.com/assets/1044532/14814654/7c375890-0ba7-11e6-8bd1-feec903cb870.png)

Regards ;)

**Comment by mohierf** [comment]
@pedrojimenez : you should have opened 3 issues ... much more simple to track responses :wink:

**Comment by mohierf** [comment]
**Part 1**: 
The *unknown* in the hosts / services panels is a counter of UNKNOWN state for hosts / services; whereas the known problems in the SLA is a counter of UNKNOWN + ACK + DOWNTIME . It seems interesting for an SLA to include downtimed and acknowledged elements ...

**Part 2**: 
Which browser? I do not have this behavior with my Chrome, nor Firefox ...

**Part 3**: 
It seems related to the module `ui-graphite` or to the base Shinken metrics library ... I will have a deeper look at this because I recently saw issues about those subjects.

**Comment by pedrojimenez** [comment]
Hi @mohierf 

**Part1**: 
Sorry but i was not understanding the meaning of Known Problems, under the point of view of SLA. I though that was corresponding the same values/links of **unknown** in the hosts / services panels.
Now it is really crystalline.

**Part2**:
Sorry for the noise, i tested it several times with private session on the browser ... I have rechecked it again with no cookies no cache and now it is been shown correctly

**Part3**:
We are using the npcd (on broker) + ui-pnp module for the graphs, and the current behaviour is not complete. In the _hosts checks_ only the hosts with DOWN states are being shown whereas in the services part,  some services with values over 0% or with a critical the pnp graph are not shown from the list. All of them inside the properties of the host/service --> *tab Graph* are there. 

My apologies again for my local cache problem.

**Comment by pedrojimenez** [comment]
Hi @mohierf, 
I think this issue must be stay closed, but what to do with the missing "ui-pnp" graphs ?
Could you open a new one with all the related info you received ?

Thanks and regards

**Comment by mohierf** [comment]
Hi @pedrojimenez 
Please open a new issue for the graphs part with your screen captures ... I will have a look soon

**Comment by pedrojimenez** [comment]
ok, thanks @mohierf
