### ISSUE TITLE
[Bug] Error 500 on contact groups 

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#495]
Hi,

When i click on the title of contact groups, i have an error 500:
![clicl](https://cloud.githubusercontent.com/assets/15362041/14886965/eb1dab9e-0d53-11e6-900e-cdf6d6590ad2.PNG)

![contactgroup](https://cloud.githubusercontent.com/assets/15362041/14886804/fabbccb2-0d52-11e6-8104-1752eb582b83.png)

Perhaps, my contacts conf are bad.

> define contactgroup {
   contactgroup_name    admins
   alias                Shinken Administrators
   members              shinken
  }

> define contact {
  contact_name                  shinken
  name                          shinken
  alias                         shinken
  use                           generic-contact
  contactgroups                 admins
  password                      toto
  email                         toto@toto.com
  can_submit_commands           1
  is_admin                      1
}

I using WebUI 2.4.1

**Comment by mohierf** [comment]
Still present ?

**Comment by Azef1** [comment]
Yes it's still present. I will try to give you more technicals information to find the bug.

**Comment by Azef1** [comment]
Hi,
The problem is little bit different: Now the problem is: AttributeError("'Contact' object has no attribute 'get_groupnames'",)
![aerror500](https://cloud.githubusercontent.com/assets/15362041/16727987/1b9858ba-4764-11e6-8890-837cd09c104a.png)

Before: User object has no attribute 'get_groupnames
Now: Contact object has no attribute 'get_groupnames

**Comment by mohierf** [comment]
Problem should be fixed on most recent version 2.4.2

**Comment by cornernote** [comment]
Web User Interface Version
Shinken Web UI, version: 2.4.2c

Shinken Framework Version
Shinken Framework, version: 2.4.3

Error: 500 Internal Server Error
Sorry, the requested URL 'http://example.com/all?search=cg:admins' caused an error:

Internal Server Error
Exception:
AttributeError("'User' object has no attribute 'get_groupnames'",)
Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 521, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3615, in wrapper
    result = func(*args, **kwargs)
  File "/var/lib/shinken/modules/webui2/plugins/problems/problems.py", line 65, in get_all
    items = app.datamgr.search_hosts_and_services(search, user)
  File "/var/lib/shinken/modules/webui2/datamanager.py", line 562, in search_hosts_and_services
    if group.get_name() in contact.get_groupnames().split(', '):
AttributeError: 'User' object has no attribute 'get_groupnames'

**Comment by ornoone** [comment]
hi, I don't reproduce with Shinken Web UI, version: 2.7.2. your 2.4.2c seem pretty old.

**Comment by cornernote** [comment]
tru dat!

Upgraded and it's all good now.
