### ISSUE TITLE
[Feature Request] Add indication on "Execute an action" for non admin

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#496]
Hi, 

I propose you an improvement:
Add an indication for non admin click on button "Execute an admin"

Currently (popup is empty),
![execute](https://cloud.githubusercontent.com/assets/15362041/14887809/bd61b188-0d57-11e6-8991-dd876f1b15b2.PNG)

My proposal:
![propsal](https://cloud.githubusercontent.com/assets/15362041/14887817/c8d7500e-0d57-11e6-803f-2e27e4c6ef8a.png)

**Comment by mohierf** [comment]
What is the matter of this feature?

User role is displayed in the user dropdown menu (User / Administrator). He can be a simple User or an Administrator.

 As a simple user he can use commands or not. An administrator can always submit commands.

 The menu *Execute an action* is only displayed if the user can submit commands (Power user or Administrator).

**Comment by Azef1** [comment]
In contact cfg when i specified:
```
 can_submit_commands            0
 is_admin                       0
```
the simple user see the button "Execute an action" and if the user click on the button he see a menu empty. the user think it's a bug... The button should be hide for simple user.

Is it with the command  `can_submit_commands 0` to disable submit commands ?

**Comment by mohierf** [comment]
I have the same behavior .... and I do agree with you! This menu should not be present if user is not allowed to submit commands ... :/

**Comment by Azef1** [comment]
Thx i installed your version and it's works !!!!
