### ISSUE TITLE
[Bug] Error 500 in browser console

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#497]
Hi,

Sometimes i see a blue popup on bottom right in shinken 
![backen](https://cloud.githubusercontent.com/assets/15362041/14918841/35f398c2-0e26-11e6-91a7-013d336f33a8.PNG)

And i see on console of my browser (firebug) an error 500:
![user500](https://cloud.githubusercontent.com/assets/15362041/14918715/a0eeb1da-0e25-11e6-96e0-3391e1fcd9ad.png)

In my contacts conf i checked the 'name' attribute and this field isn't empty.

**Comment by mohierf** [comment]
This blue popup is an alert for the Web backend check from the client ... I also had the same problem this afternoon ... but only once or twice ... I will try to reproduce this!

Are you logged-in with an admin user?

**Comment by Azef1** [comment]
no with a non admin user.
I will try to logged-in with an admin user and see if the blue pop to reproduce

**Comment by mohierf** [comment]
Any news about this @Azef1 ?

**Comment by Azef1** [comment]
I confirm the problem is present only with **non admin** user. 
The message error generated by the error 500 is `AttributeError("'User' object has no attribute 'name'",)` but i check my contact and i have an attribute name:

--> I will try to reproduce the problem with other conf

**Comment by Azef1** [comment]
I test with same contact config on two different WebUI version:
On WebUI 2.2.1: no problem
On WebUI 2.4.1: **Problem**

**My contact conf is:** 

> define contact{
>    contact_name                  guest
>    name                          guest
>    alias                         guest
>    use                           ro-contact
>    password                      shinken123
>    email                         guest@shinken.com
> }

**My contactgroup conf is:**

> define contactgroup {
>   contactgroup_name    readonly
>   alias                Shinken Users Non Admin
> }

**My template contact conf is:**

> define contact{
>   contact_name                  generic-contact
>   name                          generic-contact
>   alias                         generic-contact
>   host_notifications_enabled    0
>   service_notifications_enabled 0
>   host_notification_period      24x7
>   service_notification_period   24x7
>   host_notification_options     d,u,r,f,s
>   service_notification_options  w,u,c,r,f
>   host_notification_commands    notify-host-by-email
>   service_notification_commands notify-service-by-email
>   register                      0
> }
> 
> define contact{
>   contact_name                  ro-contact
>   name                          ro-contact
>   alias                         ro-contact
>   use                           generic-contact
>   contactgroups                 readonly
>   is_admin                     0
>   host_notifications_enabled    0
>   service_notifications_enabled 0
>   register                      0
> }

**Comment by mohierf** [comment]
Problem fixed with most recent version 2.4.2
