### ISSUE TITLE
REST API for searching WebUI data

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#498]
The WebUI, based on a WSGI Web Server, may open a REST API to allow external applications to request for monitoring objects.

To be discussed and defined ...

@david-guenault : following our chat :wink:

**Comment by mohierf** [comment]
Allow NagVis connection to the WebUI: https://github.com/NagVis/nagvis/blob/master/share/server/core/classes/GlobalBackendmklivestatus.php

**Comment by maethor** [comment]
@mohierf should we close this issue?
