### ISSUE TITLE
[Improvement] No authentification for guest user 

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#502]
Hi,

I propose an improvement:
Currently, **all** users need a login/password to access to Shinken. I think it's could be nice to haven't password for "guest" user. Guest user have a read-only access. Only the admin, need to enter a longin/password to do actions.

**Scenario:**
Go to Shinken WebUI.
All users can navigate in WebUI with read-only access (no action).
The admin need login/password to do some actions.

**Example:**
It's the same thing on Grafana: 
All users can navigate without authentification. (default all users are guest)
The admin need login/password to edit the graphs
![webuiwithoutauth](https://cloud.githubusercontent.com/assets/15362041/15466379/93454dac-20d9-11e6-828f-a7d5e2f9d705.png)

**Technically**
My idea is: In webui.cfg add option: `guest_mode: on` to enable this mode 

What do you thing ? Have you idea to improve this mode ?

**Comment by mohierf** [comment]
You should have a look to the `anonymous` parameter in the *webui2.cfg* configuration file ... as far as I remember, this will allow access to WebUI without any login.

**Comment by Azef1** [comment]
Thx, i found this [doc](https://github.com/shinken-monitoring/mod-webui/wiki/Configuration---Main-parameters#user-management) to enable anonymous mode. It"s works but the user can access only to the dashboard (one eye view). It's possible to extend this for all pages in WebUI (hosts/Service page and minemap) ?

**Comment by mohierf** [comment]
You are right. At the moment, the anonymous contact only allows access to the dashboard currently view. I am not sure whether it is a good idea to allow the access to all the WebUI for anonymous users.

This behavior can be achieved easily with a frontend server (eg. nginx) that will forward WSGI remote user authentication to the WebUI. Then you can configure `remote_user_enable=1` and `remote_user_variable=XXX` where XXX is the name of the variable forwarded by your server. As of it, you will not need any login on your nginx and it will simulate an authenticated user to the WebUI ...

**Comment by Azef1** [comment]
OK, i understand. I think it's pity because i haven't secret informations in my Shinken and if the users cannot do actions, there is no risk. In my case, i will create a generic login/password for my guest users. 
Thank you for your quick answers.
