### ISSUE TITLE
[Question] Embed widget on other page.

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#503]
Hi,

I have a question:
I would like to embed the widget "Impacts" on my Nagvis dashboard via an iframe.
I noticed i can access on widget by URL: http://myShinken:7767/widget/impacts but the CSS is not included. 
Is there a way to embed a widget in an iframe.

Thx

**Comment by mohierf** [comment]
Hum ... it is not that much easy but not too complicated.

The widgets are parts of the dashboard page which includes WebUI files and page specific javascript and Css files used by the widgets ...

The Impacts widget do not have any specific javascript or Css and uses only the *standard* widgets files: `js/jquery-ui-1.11.4.min.js`, `dashboard/js/widgets.js`, `dashboard/js/jquery.easywidgets.js'`.

Indeed, you will need an HTML page that includes those files and the specific widget HTML content ... all of this bound in an iframe ... I do not see any easy solution for this without modifying a lot of things in the WebUI :/P

**Comment by Azef1** [comment]
Thx, i will follow your advice. 
I inform you of my progress:

I created a quick HTML page: 
```
<script type="text/javascript" src="http://myShinken:7767/static/js/jquery-ui-1.11.4.min.js"></script>
<script type="text/javascript" src="http://myShinken:7767/static/dashboard/js/widgets.js"></script>
<script type="text/javascript" src="http://myShinken:7767/static/dashboard/js/jquery.easywidgets.js"></script>

<iframe name='iframe1' id="iframe1" src="http://myShinken:7767/widget/impacts" ></iframe>
```

But in my console, i have some errors about javascript (jQuery is not defined, widgets is not defined,....).

I continuous my research.

**Comment by mohierf** [comment]
You should also include almost all of the javascript files included in the main Web UI page ... at least jQuery is needed.

**Comment by Azef1** [comment]
Hi
I used an other strategy: I use a LiveStatus query and show the result in webpage.
I embed this page in NagVis. 
The URL method http://myShinken:7767/widget/impacts isn't good solution because i need an authentificate to acces this page and in Nagvis it's boring to authentificate to Shinken only for an iframe.

In other message, you talk about `REST API for WebUI`, Is it to replace Livestatus ?

**Comment by mohierf** [comment]
A REST API for the WebUI is an interesting feature, as it will allow, for your concern, to replace a Livestatus request, yes.

As you found out a solution, I close this issue.
