### ISSUE TITLE
Wrong count for Problems ack

### ISSUE THREAD

**Issue by alexstaz** [shinken-monitoring/mod-webui#504]
Hello,

When you have for example some service in problem state and acknowledged, if you restart shinken, they are no more counted. Please take a look a this screen capture :
![image](https://cloud.githubusercontent.com/assets/5681800/15512261/3e7a9cda-21df-11e6-8da2-64189f0a90c3.png)

I have made some investigation, and the problem seem to be that the service has the property 'is_problem' to false.
If I log some info in get_services_sythesis, I have :
Name: Process - Online, state: CRITICAL, is_problem: False, problem_has_been_acknowledged: True
Name: PKF StackManager Connection, state WARNING, is_problem: False, problem_has_been_acknowledged: True

I think that when we restart, the property is_problem is lost, but I don't find where it's initialized, or if it can be saved when we restart shinken.

Thanks for the help.

**Comment by alexstaz** [comment]
Hello,

Found that the is_problem is managed by the shinken core.
I use retention-mongodb for keeping informations across restart and I think the problem is here.
An idea ?

Thanks.

**Comment by mohierf** [comment]
I confirm ... the WebUI simply displays the host / service states are they are known by Shinken core. You should have a look at my own Mongo retention module: https://github.com/mohierf/mod-retention-mongodb ... I am using this fork on my own server since several months without any problems :wink:
