### ISSUE TITLE
[Bug] Servigroups hierarchy doesn't works

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#506]
Hi,

I noticed the servicegroups hierarchy doesn't works:
I using WebUI 2.4.1 and i edited this file `/usr/lib/python2.7/site-packages/shinken/objects/servicegroup.py` to add  'servicegroup_members': StringProp(fill_brok=['full_status']), between `servicegroup_name` and `alias`.

I haven't this icon in front of the servicegroup's name 
![iconnn](https://cloud.githubusercontent.com/assets/15362041/15646524/60d2a07e-265e-11e6-93d0-49dd97861a79.PNG)

For hostgroups the hierarchy works well.

**Comment by Azef1** [comment]
Have you same problem with Servigroups hierarchy ?

I would to thank you for your work and to bring the project alive.

**Comment by mohierf** [comment]
I have Shinken 2.4.3 and WebUI 2.4.2.

I did not noticed any problem with this configuration:

```
define servicegroup{
    servicegroup_name       dev
    alias dev
    servicegroup_members    dev_child, web
}
define servicegroup{
    servicegroup_name       dev_child
    alias dev_child
    # host/service list:
    # - service Https on host KNM-Glpi
    # - service Https on host KNM-Shinken
    members                 KNM-Glpi,Https,KNM-Shinken,Https
}
```

![image](https://cloud.githubusercontent.com/assets/2932687/16756342/bcb98ee4-4804-11e6-8570-563b0abd799d.png)

Check your groups configuration and copy it if the problem persists.

**Comment by Azef1** [comment]
Thank you for you answer. My bad i did one error (i wrote `define servicegroups { ... }`  instead of `define servicegroup { ... }`.

But i have a other problem the child group is empty.
I created a test conf:

```
define servicegroup{
    servicegroup_name       dev
    alias dev
    servicegroup_members    dev_child
}
define servicegroup{
    servicegroup_name       dev_child
    alias dev_child
    members     host,service
}

define host {
  host_name                 host
  name                      host
  alias                     host
  address                   0.0.0.0
  use                       aggregates
}
define service {
  service_description   service
  host_name             host
  use                   unit-service
  check_command         check_tcp!8888
}
```

![aaaemptycapture](https://cloud.githubusercontent.com/assets/15362041/16761913/9a55f018-4822-11e6-87fe-64318ee8da97.PNG)

I will recheck my conf

**Comment by mohierf** [comment]
Should be fixed
