### ISSUE TITLE
[Bug] Adding a service downtime results in 'generic modal' message.

### ISSUE THREAD

**Issue by ryanbsaunders** [shinken-monitoring/mod-webui#508]
Our Shinken architecture consists of multiple realms.  When scheduling a downtime for a service which belongs to a host in the 'All' realm, we receive a "Generic modal" box, but no option to add a downtime.  The same occurs when trying to remove a downtime on that host.

To reproduce:   

- From a host's page, click the 'Services' tab.
- Click on one of the services.
- Click the 'Downtimes' tab for that service.
- Click the 'Schedule a downtime' button.

The result of following the above steps is the generic modal box:

<img width="615" alt="generic_modal" src="https://cloud.githubusercontent.com/assets/3970377/16045728/c0cd0a4a-3217-11e6-9f4b-79453a0e4d22.png">

The same occurs when trying to delete a downtime that was scheduled as part of a host downtime:

<img width="1141" alt="service_downtime" src="https://cloud.githubusercontent.com/assets/3970377/16045761/e03a94e2-3217-11e6-8d8b-353a7882d241.png">

This issue doesn't occur on hosts that belong to a different realm.

We've attempted to restart the broker along with the rest of the Shinken services on the host, but did not have any success.

Shinken Framework:  2.4.3
Webui:  2.4.1

**Comment by mohierf** [comment]
Thanks for reporting. I will try to reproduce, but I still can request a few more information from you:
 - do you have any log in  your browser console? If so, should you copy them here.
- I am also interested by your `brokerd.log` ...

 Thanks

**Comment by ryanbsaunders** [comment]
I've tracked this down to having services with forward slashes as part of the name.  

Example:  _hostname/service-check-name_   

We've prefixed many of our service names with forward slashes as part of the way our automation works.  I've updated these service names to use hyphens instead of forward slashes to mitigate the issue.  

I'm going to close this issue since having forward slashes in service names is probably not a good idea.  If you'd like to address the problem, however, feel free to reopen the issue.

**Comment by mohierf** [comment]
Glad to see you fixed this ...
