### ISSUE TITLE
[Feature Request] Have different style between output and long output

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#509]
Hi,

I noticed a strange behaviour may be misleading for users:
In this page http://MyShinken:7767/all?search=type:service the output column showing the `output ` and just after the `long output`. So when outputs are same, the user cannot difference between outputs.

<h6>Example:</h6>
Here Output column not extended and showing `output `
![output3](https://cloud.githubusercontent.com/assets/15362041/16084868/91bd8442-331a-11e6-868c-2749c5d545fb.PNG)
<hr>
Here Output column extended and showing `output AND long output`
![output1](https://cloud.githubusercontent.com/assets/15362041/16085036/0ee15d4a-331b-11e6-8964-599424d865d7.PNG)
<hr>
Source code:
![output2](https://cloud.githubusercontent.com/assets/15362041/16085082/37caee7e-331b-11e6-8a83-271049dd960c.PNG)

So, it will be nice if there are more difference between outputs. For example with a different CSS style.

NB: In my case the output generated with a `business_rule_output_template` command

**Comment by mohierf** [comment]
Hi,
what seems strange to me is that your output and long_output are the same ... normally, thos fields are different. Can you tell me more about your check plugin ?

**Comment by Azef1** [comment]
Hi,
For traditionnal checks eg: tcp_check i haven't long_output generated.
When check_command is bp_rule!(...), in webui the output=long_output.
So the problem is only on bp_rule check:
![captureoputput](https://cloud.githubusercontent.com/assets/15362041/16110335/84ca2a2c-33ad-11e6-92c6-ca74ec52a4c0.PNG)
In source code: 
![longoutput](https://cloud.githubusercontent.com/assets/15362041/16110390/c39de5e0-33ad-11e6-8095-88d8ad44f72a.PNG)

It may be a problem from shinken and not webui


![aaa](https://cloud.githubusercontent.com/assets/15362041/16110711/682da284-33af-11e6-9395-9c69842b6e4d.png)

**Comment by mohierf** [comment]
I do confirm that it is a problem of Shinken. You should open an issue in the Shinken project ... I close this one
