### ISSUE TITLE
[Bug] Bad link to show hosts UP on hostgroups

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#513]
Hi,

On hosts groups page, if you click on the button to show all hosts UP of hostgroup the page show "We couldn't find anything." 
Because the link contain too quotes.

Example:
![hhhhhhhhhhhhhhhh](https://cloud.githubusercontent.com/assets/15362041/16299808/7995d270-393c-11e6-882c-e7ebb240bfaa.PNG)

The title link is:  `http://myShinken:7767/all?search=type:host hg:"mysql"`
The UP link is:   `http://myShinken:7767/all?search=type:host hg:'"mysql"' is:up`

---
The correct link could be `http://myShinken:7767/all?search=type:host hg:"mysql" is:up`

Thx

**Comment by mohierf** [comment]
Thanks for reporting
