### ISSUE TITLE
[Bug] Widget notification toggle switch button broken.

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#514]
Hi,

I doesn't know why, but the widget show a button broken. The soluce it's to refresh page until to have a good button.

![aaaaaaaaaaaaaaaaaaadd](https://cloud.githubusercontent.com/assets/15362041/16300252/3b188c88-393f-11e6-9174-7098d3665c7d.PNG)
![bbbb](https://cloud.githubusercontent.com/assets/15362041/16300268/53878c1a-393f-11e6-8053-44f973775797.PNG)
Good:
![aaaaaaaadddees](https://cloud.githubusercontent.com/assets/15362041/16300289/70decaf8-393f-11e6-87fd-355d05f69121.PNG)

This widget is very useful.

**Comment by mohierf** [comment]
I will try to reproduce the problem to fix it ...

**Comment by strom18** [comment]
Same for me : 
![image](https://cloud.githubusercontent.com/assets/2601967/16520816/fe35024c-3f92-11e6-98dd-9b3d2c574ce2.png)

Couple refresh solve the issue

**Comment by mohierf** [comment]
What I noticed is that, sometimes, the javascript file associated with the plugin is not loaded correctly by the WebUI on a refresh ... do not known yet why this occurs!

**Comment by bmalynovytch** [comment]
Sadly, in latest (2.7.2) webui release, the issue still exists :(

**Comment by bmalynovytch** [comment]
In fact, the problem isn't the same: it's not random but permanent and maybe related to 983dd0d1d446a8287da1afefe2a5d643ff3892e1 as bootstrap-switch CSS and JS were deleted.

I'll open a new issue => #610
