### ISSUE TITLE
Share alerts with…

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#516]
This is just an idea, I don't know if I want to implement it, but I would like your input on it.

I think it could be very useful to have a « share » button along with downtime, ack, recheck, etc. To be generic, this functionality could be developed with plugins. Right know, I think I could use an email plugin to notify external users (like clients) and a Trello plugin to send an issue in Trello (where it can be assigned to an adminsys).  But any ticket system could be connected that way.

What do you think?

**Comment by mohierf** [comment]
Nice idea! I made a test with the Glpi ticketing system and you will find the source code  in the ticket plugin ... currently I do not have time to build a new version for the WebUI, but if you have some ;)

**Comment by maethor** [comment]
Since I will not work on this, I'm closing this issue.
