### ISSUE TITLE
Installation on fresh Shinken setup fails due to missing directory

### ISSUE THREAD

**Issue by UweSauter** [shinken-monitoring/mod-webui#521]
This is on an up-to-date CentOS 7.2 with Shinken installed from EPEL.

When I try to install WebUI2 from shell the installation fails with the following output:

[root@shinken ~]# shinken install webui2
Grabbing : webui2
[1468264211] ERROR: [Shinken] The installation directory /var/lib/shinken/doc is missing!

Is this an issue with packaging for CentOS or can this addressed by the install routine?

**Comment by mohierf** [comment]
This is an issue of the Shinken packaging ... the `shinken install` script tries to copy the WebUI _doc_ directory into the Shinken main _doc_ directory ... anyway it is not an issue of the WebUI.

The _/var/lib/shinken/doc_ is created during the Shinken installation process...

**Comment by UweSauter** [comment]
I'll open a bug in Red Hats bugzilla.
