### ISSUE TITLE
New action menu

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-webui#526]
Hi,

I really don't like the new actions menu in the problems view. I may have missed the discussion, but what motivates it? I don't see the point of forcing the user to open the menu. When we select a service, actions should displayed and available in one click.

Moreover, I think there is a display bug when the actions button is not displayed. The footer should not be that high.

Finally, this is quite ugly. and we are loosing a lot of vertical screen space for nothing. It's particulary true in service and host view where the bar is displayed all the time.

**Comment by mohierf** [comment]
This modification improves the display on mobile devices that was not rendered correctly before.

I agree that it should not be necessary to open the menu ... it may be opened as default and its position should be some pixels lower on the screen.

**Comment by maethor** [comment]
Hum. I think I still had some cache that missed up the rendering. Now it's better, the footer is not ugly anymore.

But I think the menu should be open. Maybe a [list group](http://getbootstrap.com/components/#list-group-linked) could do it ?

For simplicity, the menu and the select boxes could be hidden on mobile, because we can always find this action when we unfold a service.

**Comment by mohierf** [comment]
+1 for the cache ;)

Is is easy to have the dropup menu automatically opened ... I will commit a small patch for this

**Comment by maethor** [comment]
Ahah, funny, I forget I already noticed it in the past :)

I fixed it in 2ba736035cfab355b6ed6a9313a0187a7d34f11c

The new action menu is open, we don't need to get through a button. And I added some CSS for mobile screen to display the action buttons horizontally in the footer.
