### ISSUE TITLE
[2.4.2c] and firefox

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-webui#528]
Hi,

I find two problems with firefox ESR 45.2.0 : 
- There 's a bug with "worldmap" and "worldmap widget" in Firefox 
  ![capture2](https://cloud.githubusercontent.com/assets/12746104/16909097/87c61fc4-4cd0-11e6-81a1-7719948ebcbb.PNG)
- When I scroll down on the minemap view, there's a little problem with the top menu...
  ![capture3](https://cloud.githubusercontent.com/assets/12746104/16909267/e22e7370-4cd1-11e6-9446-d844bb7d964c.PNG)
  those problems are not present on Chromium 51.0.2704.106...

And the look of the action button is a little strange ... (same with chromium) 
![capture4](https://cloud.githubusercontent.com/assets/12746104/16909294/21befbae-4cd2-11e6-9327-97efefa8452e.PNG)

Do you confirm ?
Thanks

**Comment by b-keller** [comment]
Today,

The first bug is gone... no change on shinken server or Firefox but the map loads normally.("worldmap" and "worldmap widget")

**Comment by mohierf** [comment]
Perharps something with the server or client cache ...

**Comment by b-keller** [comment]
Hi,

the second also...
Yesterday I have not tested the "minemap view", and now it's ok....
finally, there is only the action button...

**Comment by mohierf** [comment]
For the action menu, you should try this patch: https://github.com/mohierf/mod-webui/commit/af8b91d5fa554550d7ba3864a2b60711c63271f1

**Comment by b-keller** [comment]
Ok, sorry for the delay... I close...

Thx
