### ISSUE TITLE
Timeline ... seems interesting for downtime periods

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#53]
What do you think about it ?
![image](https://f.cloud.github.com/assets/2932687/2389642/69e2c67c-a950-11e3-9842-4ab70da9f3c9.png)

Mock-up built with https://github.com/almende/chap-links-library, JSON timeline data built from MongoDB logs database.

**Comment by mohierf** [comment]
Closing ... to be discussed for future release.

**Comment by mohierf** [comment]
Timeline plugin to be updated if needed ...

**Comment by Simage** [comment]
Is the time line perhaps better implemented by pushing events to graphite and being able to correlate state changes with changes in the perfdata metrics?
