### ISSUE TITLE
External Command issues

### ISSUE THREAD

**Issue by claneys** [shinken-monitoring/mod-webui#532]
Hi,

I'm not sure that it is webui that in fault, but I got some problems using webui2 to use actions like recheck or submit a manual result.

I got log message that indicate me that action have been submitted but scheduler doesn't have them like there is a communication issue passing the command between shinken components.

```
[1470747919] INFO: [broker-master] [WebUI-actions] got command: SCHEDULE_FORCED_SVC_CHECK with args: ['arvsfgdbsup', 'Oracle-sudb-invalid-objects', '$NOW$'].
[1470747919] INFO: [broker-master] [WebUI-actions] external command: [1470747919] SCHEDULE_FORCED_SVC_CHECK;arvsfgdbsup;Oracle-sudb-invalid-objects;1470747919.
```

What can I do ? I search what is the next component called by `self.from_q.put(e)`...

**Comment by mohierf** [comment]
I am quite sure it is not a WebuI problem ...

When the command is posted to the scheduler queue, it should get the command from its queue. You should confirm this with Debug logs on the scheduler daemon ... and even on the arbiter daemon.

You should also activate the external commands log in the shinken.cfg file.

On my configuration the commands sent by the WebUI are executed.

**Comment by claneys** [comment]
It isn't a webui problem. But debug logs on the scheduler daemon didn't show these commands come up into its queue. I see the commands leave the broker but I can't figure out where it goes then.

I'll continue working on it. Thanks.
