### ISSUE TITLE
Filter the currently dashboard

### ISSUE THREAD

**Issue by efficks** [shinken-monitoring/mod-webui#534]
It would be really usefull for my team to be able to filter the currently dashboard.
Be able to select host and service groups.

**Comment by mohierf** [comment]
Filter the currently dashboard ... you mean being able to select which panel should be displayed, right?

**Comment by efficks** [comment]
@mohierf No I mean be able to add this the the URL ::

`?search=hg%3AsomeHostGroup`

It would need modification to currently.tpl in the call to get_synthesis to add the search string.

**Comment by mohierf** [comment]
Ok, understood. Not sure this will be very easy to deal with ... I will have a look to this feature for a next version.

**Comment by efficks** [comment]
@mohierf I've made a pull request. Fell free to merge it or not.

**Comment by mohierf** [comment]
Nice shot! It has been a long time since I had a look in this code ... I did not expected as easy as you did :wink: 

I will merge your PR for the next version

**Comment by efficks** [comment]
@mohierf Any plan for the next version?

**Comment by mohierf** [comment]
Hi @efficks 
Sincerely I do not know. Because of the very lack of activity on the Shinken project since several months as of now, I am not really motivated to make more efforts to maintain and upgrade this UI :disappointed: 

I am currenlty fully engaged on the Alignak project and do not have much time for anything else.

**Comment by maethor** [comment]
@efficks I'm working on UI improvements so I will try to publish a new version soon, with your PR in it.

**Comment by eduault** [comment]
And it would be intersting for the user to be able to filter hosts and services in the dasbord using a widget. For example, I would be able to add a checkbox in the dashboard. When the user checks this checkbox, only hosts and services which are KO would be displayed (only in the page this user displays in his browser, not for all users).
