### ISSUE TITLE
Error 500 on contact groups

### ISSUE THREAD

**Issue by ceso** [shinken-monitoring/mod-webui#540]
Hi, frist of all english is a foreign language so, sorry if something is strange.

I got this issue too:

https://github.com/shinken-monitoring/mod-webui/issues/495

But the version of shinken I have is 2.4.3, in the comments mohierf says that this should be fixed in 2.4.2, but the issue is still there.

**_Exception:**_
`AttributeError("'Contact' object has no attribute 'get_groupnames'",)`
**_Traceback:**_
`Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 521, in lock_version
    return f(**args)
  File "/usr/bin/bottle.py", line 3615, in wrapper
    result = func(*args, **kwargs)
  File "/var/lib/shinken/modules/webui2/plugins/problems/problems.py", line 65, in get_all
    items = app.datamgr.search_hosts_and_services(search, user)
  File "/var/lib/shinken/modules/webui2/datamanager.py", line 562, in search_hosts_and_services
    if group.get_name() in contact.get_groupnames().split(', '):
AttributeError: 'Contact' object has no attribute 'get_groupnames'`

If more info is needed, please tall me, thanks!

Regards!

**Comment by cleonn** [comment]
We have the same problem, and running 2.4.3.

**Comment by theogfx** [comment]
I can also confirm: same issue on `2.4.3`

**Comment by guillaume-u** [comment]
I have the same issue on `Shinken 2.4.3 — Web User Interface 2.4.2c`

**Comment by maethor** [comment]
I fix it in the development branch.

Thanks you all for reporting and reproducing.
