### ISSUE TITLE
Bookmark use only "all" view

### ISSUE THREAD

**Issue by ghost** [shinken-monitoring/mod-webui#541]
Hi, 
when I create a bookmark from a minemap view, it's created based only on the filter.
Indeed, the filter is kept but when I use the bookmark I go only to the "all" view, but not on the minemap one.

example :
my URL : http://shinken.mycompany.com/minemap?search=type%3Ahost+htag%3Adb-prod-server#
I bookmark it, but when I use the bookmark, I go to:
http://shinken.mycompany.com/all?search=type%3Ahost+htag%3Adb-prod-server#

which is not what I expect to have a global view for dba...

**Comment by mohierf** [comment]
You are right, but there is no real simple solution to this problem ...
