### ISSUE TITLE
double quote in a filter give issue when using bookmarks

### ISSUE THREAD

**Issue by ghost** [shinken-monitoring/mod-webui#542]
Hi,
in complement to my previous reports (#541), when I set the filter to
type:host hg:"oracle-servers" htag:db-prod-server, The bookmark failed.
Indeed, the URL retained by the system is :
http://shinken.mycompany.com/all?search=type:host%20hg:
(in which you could also view that the "minemap" keyword had been replaced by "all")

instead of 
http://shinken.mycompany.com/minemap?search=type:host+hg:%22oracle-servers%22+htag:db-prod-server

**Comment by mohierf** [comment]
Thanks for reporting. I will have a look for a next version

**Comment by maethor** [comment]
Should be fixed by #580 in Shinken WebUI 2.5.4. I'm closing the issue, ping me if it is not fixed.
