### ISSUE TITLE
Google/OAuth2 authentication?

### ISSUE THREAD

**Issue by thequailman** [shinken-monitoring/mod-webui#546]
Hello, are there any plans to add Google/OAuth2 authentication providers?  Or support some kind of delegated authentication with the webserver where a header is passed containing the username?

**Comment by mohierf** [comment]
Nope, Google authentication is not in our roadmap currently ...

But it is yet possible to have an HTTP header with authentication, see here for more information about it: https://github.com/shinken-monitoring/mod-webui/wiki/Configuration---Main-parameters. Not very well documented but I hope you will find it useful anyway ...
