### ISSUE TITLE
Problems Page: State filters that are not selected always show 0

### ISSUE THREAD

**Issue by eherot** [shinken-monitoring/mod-webui#549]
...even when the actual number of items is more than that

![screen shot 2016-11-01 at 5 23 06 pm](https://cloud.githubusercontent.com/assets/400447/19908046/e0034da8-a057-11e6-9cf6-dc743fded910.png)
![screen shot 2016-11-01 at 5 23 22 pm](https://cloud.githubusercontent.com/assets/400447/19908054/e927eb8c-a057-11e6-8d23-ebef2df5c42a.png)

**Comment by mohierf** [comment]
I do not understand the problem ... can you provide more information please?

If you filter to get only the OK services, you will have only OK services and thus all other counters will be 0 ... and this is the expected behaviour.

**Comment by eherot** [comment]
Hmm. Ok, I guess it's working as expected then. I guess I just find it a bit misleading because unless you actually click through all of the individual categories (or pull down the menu at the top) you would think that they are all empty. I think it would be more useful if each category was gray when it wasn't selected, but the number still showed the actual number of items that would be displayed if you clicked on it.

**Comment by eherot** [comment]
Or just don't bother having numbers there at all since, by the current design, they're just redundant to the "XX services" number in black on the left.

**Comment by mohierf** [comment]
When you have an active filter, you can have (for instance) all WARNING and CRITICAL services and then you will have the count of services for each state. Also interesting, if you filter the ACK services ...

**Comment by eherot** [comment]
The problem is that if the filter isn't actually displaying items in a particular state, it can give you the misleading impression that there are no items in that state.

E.g. If I use a filter like this:

```
type:service is:ok isnot:ack isnot:downtime
```

The bar will show:
![screen shot 2016-11-02 at 11 30 58 am](https://cloud.githubusercontent.com/assets/400447/19935286/deadaeb0-a0ef-11e6-85cf-4be7a5eec193.png)
Indicating pretty clearly (I think) that there are "0 services critical" (a fact that is corroborated by the mouseover message on the critical icon. But this is not actually true: There are critical services but the UI gives you no indication of this until you click on the critical icon.

**Comment by mohierf** [comment]
I do agree ... but we chose to display the state of the services that match the current filter ... we should probably enhance this. What do you think about this @maethor ?

**Comment by maethor** [comment]
I understand the potential problem, but I will not fix it. 

As @mohierf said, This panel displays an abstract of the search results. So yes, I you filter only on 'is:ok', it will count only ok services. This is an extreme case, but in the problem page I think the current behavior is what we want.

If you want global stats, you have the "currently" dashboard and the popovers in the navigation bar.

**Comment by eherot** [comment]
I guess I wonder then why bother having that box at all when it's just redundant to the page title and current filter. The only purpose it really serves when not in "global" mode is to show you how many items are on the currently displayed list (which is also kind of redundant unless the list is really long). Basically you're missing an opportunity to succinctly display data that the user might actually care about and gaining nothing in return (as far as I can tell).

**Comment by maethor** [comment]
I agree with you that this box is not essential, but I can't see how it is redundant. The page title doesn't give that kind of information, and the current filter says nothing about it's result.

Actually, the list can be really long. For instance I have 400 hosts and around 4000 services. So even with filter, there can be a lot of items.

![2017-05-31-180051_1920x2280_scrot](https://cloud.githubusercontent.com/assets/2410576/26641615/78ae2fe0-462b-11e7-96b8-cf7f75efbc92.png)

And this is useful information. It's actually what you care about, filtered stats. Because you don't care about global stats. They contains "business_impact 0" host and services, etc.

With that said, I agree that I don't use this box a lot. I even make a commit to hide it on mobile screens in the next version. So I'm open to suggestions. But global stats, you already have them in the top bar.

**Comment by maethor** [comment]
What do you think @eherot ?

![2017-05-31-184845_731x132_scrot](https://cloud.githubusercontent.com/assets/2410576/26643554/0096275e-4632-11e7-90d4-393499f4915e.png)

or maybe

![2017-05-31-185548_727x134_scrot](https://cloud.githubusercontent.com/assets/2410576/26643783/ca6b4f96-4632-11e7-8ff2-a9890d616d25.png)

I remain open to suggestions.

**Comment by eherot** [comment]
Ooh I like that actually

**Comment by eherot** [comment]
It took me a second to intuit what it was telling me (so maybe a tooltip might be useful? I dunno), but now that I get it I have to say I think this would be immediately useful to me.

**Comment by maethor** [comment]
There is tooltips actually, but I still have to adapt them.

OK then, this will come in the next version :smile:

Thanks for your contribution. Don't hesitate to report other ideas.

**Comment by maethor** [comment]
I have to limit this new display to medium and large screen. On small screens there is not enough space, it doesn't align properly.

But, I improved the tooltips to clarify this. So you can always have the full information:

> 20 hosts down (10%)
> 2 with current filter

**Comment by eherot** [comment]
Yeah that's awesome. Thanks for considering this!
