### ISSUE TITLE
Menu bar (enhancement): Let me go directly to state filtered results

### ISSUE THREAD

**Issue by eherot** [shinken-monitoring/mod-webui#551]
It would be great if I could click on the individual items in this box rather than having the box disappear when I try to mouse over it:
![screen shot 2016-11-01 at 5 27 17 pm](https://cloud.githubusercontent.com/assets/400447/19908189/858141ae-a058-11e6-98b7-70c587ad17fa.png)

**Comment by mohierf** [comment]
:+1: for this

**Comment by maethor** [comment]
It works in development branch. Will be merged soon.
