### ISSUE TITLE
Memory issue with Shinken 2.4.3 on RHEL 6

### ISSUE THREAD

**Issue by akqopensystems** [shinken-monitoring/mod-webui#554]
Hello community,

we use RHEL 6.8 (64-Bit) fully patched with python 2.6.
It is a Hardware Server with 2 socket CPU (E5-2620 @ 2.00GHz) and 24-GB Ram.
Software is shinken 2.4.3 with shinken-modules, both are up2date.
We use mongoDB (3.2.10-1) to store the status retention and also use it for storing history event data.
A mariaDB is storing the performance data via the tondodb-mysql module on an external VM System. (mariaDB Version 5.5.47-1.el7_2)
Thruk (2.10-2) is used as an alternative frontend, configured to access the livestatus module via unix socket.

The system has to monitor about 2500 hosts and around 24000 service checks.
Following shinken-modules are used:
- broker: NPCDMOD,livestatus,webui
- arbiter: ws-arbiter,mongodb
- poller: booster-nrpe
- scheduler: retention-mongodb
- receiver: nsca

The issue:
After running the system for five days we observe the behavior, that the system began to consume the whole memory (ram and swap).
We can see in diffrent logs, that the oom-killer starts to kill the processes, which results in a non functional system state.

**A short example:**
Nov  6 11:28:44 monitor kernel: check_interface invoked oom-killer: gfp_mask=0x280da, order=0, oom_adj=0, oom_score_adj=0
Nov  7 00:11:24 monitor kernel: python2.6 invoked oom-killer: gfp_mask=0x201da, order=0, oom_adj=0, oom_score_adj=0
[...]

It seems to be the broker which allocated more and more of memory but don't unallocate it back.
Here a short view of our notes, showing the allocation of the memory in the time periode of three days. (ps aux |grep broker |grep -v grep)

**Nov  2**
shinken  14333 71.2 20.9 6703276 5148088 ?     Sl   Nov01 876:10 python2.6 /usr/bin/shinken-broker -d -c /etc/shinken/daemons/brokerd.ini

**Nov 3**
shinken  14333 40.3 41.7 11833260 10253420 ?   Sl   Nov01 1094:38 python2.6 /usr/bin/shinken-broker -d -c /etc/shinken/daemons/brokerd.ini

**Nov 4**
shinken  14333 33.2 65.1 17642052 16016040 ?   Rl   Nov01 1443:46 python2.6 /usr/bin/shinken-broker -d -c /etc/shinken/daemons/brokerd.in
[...]

We found following articles, which looks like they can resolve the issue.
- https://github.com/naparuba/shinken/pull/1828
- https://github.com/naparuba/shinken/issues/1869
The suggested settings were set, but don't resolve the problem.
We still have the issue with the memory. Please feel free to ask for more details or config files.

Please help us.

**Comment by akqopensystems** [comment]
**Further information:**
After a while less hosts and services are displayed in the thruk frontend.
For example we see around 200 hosts and 1200 services.

**Comment by ddurieux** [comment]
Thruk use livestatus, perhaps it's a livestatus problem... but your problem is the webui, not thruk ?

**Comment by akqopensystems** [comment]
Hello ddurieux,
thanks for your fast reply. We do not know exactly if the memory leak is part of livestatus, webui or broker itself. While Thruk is receiving his data via livestatus and webui is bind directly to broker, we just can say thruk is showing less and less systems and services after a while.

Do you have any ideas or suggestions what to do? 
Regards,
akqopensystems

**Comment by hvad** [comment]
Hi,

Can you test without livestatus ? 

Thanks

**Comment by maethor** [comment]
@akqopensystems any news?

**Comment by akqopensystems** [comment]
We are no longer using this solution.
