### ISSUE TITLE
User permissions are not effective on the "currently" dashboard

### ISSUE THREAD

**Issue by hugosxm** [shinken-monitoring/mod-webui#556]
Hi, 

let's say i have two group of users, one admin, full right everywhere and one guest, contact group of only some hosts

If i go in the top right corner on WebUI and click the eye to open the "curretnly" dashboard as guest, i have the statictics of ALL the hosts... not only the host that have "guest" as a contact

Feel free to ask for some logs or config file 

Hope that help

Have a nice day

**Comment by mohierf** [comment]
Thanks for reporting. I will try to have a look for a next version

**Comment by ThomasBarach** [comment]
+1

**Comment by rednach** [comment]
In module/plugins/dashboard/views/currently.tpl, you may patch

%synthesis = app.datamgr.get_synthesis()
%s = synthesis['services']
%h = synthesis['hosts']

with

%s = app.datamgr.get_services_synthesis(None, user)
%h = app.datamgr.get_hosts_synthesis(None, user)

(I'll send the pr asap)
Regards.

**Comment by mohierf** [comment]
Thanks @rednach :wink:

**Comment by ThomasBarach** [comment]
Thanks for your work @rednach  !

**Comment by Furiml** [comment]
I have the same issue with the widgets in the "Dashboard" view, the "All ressources" view, the "Problems" view, the "Wall" view (and "currently" view)
On the "Problems" view, I can click on the problematic service I'm not supposed to see and have the usual overview. However if I click on the host on which the problematic service is happening, I get a 404.
Wasn't this supposed to be fix ? (#520)

F.

**Comment by maethor** [comment]
Patched merged. Will be fixed in the next version.
