### ISSUE TITLE
Groups and contact deleted still appear in UI after reload

### ISSUE THREAD

**Issue by tchene** [shinken-monitoring/mod-webui#558]
Hi, I work with shinken 2.4.2 and webui 2.2.1.

I have some issue with groups and contact deletion. When I delete  an hostgroup, servicegroup, contactgroup or contact from my configuration, after I reload shinken, they stayed in the webui, I don't understand why.
I got the right data when I log scheduler at reload (in load_conf function scheduler.py:160), but not in the data manager in webui (get_hostgroups function datamanager.py:596)

Service and host are delete successfully. 

Anyone else have the same issue or can reproduce this bug,

**Comment by mohierf** [comment]
Hi
sorry but I cannot reproduce ...

The WebUI is using only the data that Shinken has loaded. As such, you should have exactly the same data ... moreover I do not understand why this problem happens only with contacts/contactgroups and not iwth hosts and services :/

Do you haveany retention module installed?

**Comment by tchene** [comment]
Yes I have retention-mongodb. And this problem happen too to hostgroups and servicegroups, and I see the commands are also concerned.
As I see, I have good data in the scheduler but not into the broker and I don't understand where shinken reload the data, so I can't verify much more.

**Comment by mohierf** [comment]
As far as I know, the scheduler loads the data and create some broks that are sent to the broker. The broker uses a *regenerator* to restore the data and it cannot "create" data that so no exist any more :/ 

This means to me that the scheduler has those data, what I suspect is that it restores those data from the saved retention ... you should give a try without the retention module ?

**Comment by tchene** [comment]
I will test without the retention module this morning and give you a feedback.

**Comment by tchene** [comment]
Ok so, I test reloading after delet retention module and things stay the same, have you any variable that I can log to follow the reload process and the data between arbiter and broker?

**Comment by mohierf** [comment]
All is in the Regenerator class ...

**Comment by maethor** [comment]
@tchene do you still have this bug with the last version of the webui?

**Comment by tchene** [comment]
I did a fresh Shinken 2.4.2 install with the last webui version (2.5.0-beta) and I still have the same bug.

I tried to create a windows hostgroup with 2 hosts in it and an linux hosgroups with the same hosts number. I see all of it in the webui. Then, I deleted the windows hostgroups and reload Shinken. After that, I still see the windows hostgroups in the webui but without any host in it.
After a restart, all was ok.

I don't try with another group or item but I think it's the same as hostgroup.

Ubuntu Server 14.04.3:

Shinken==2.4.2
Webui2==2.5.0-beta
arrow==0.10.0
bottle==0.12.8
passlib==1.7.1
pymongo==3.0.3
requests==2.2.1

If you need another information on my install, feel free to ask.

**Comment by maethor** [comment]
Shinken reload can be really buggy. I always use restart.

**Comment by mohierf** [comment]
If still any interest to keep this issue open, please re-open
