### ISSUE TITLE
use sqlite instead of mongodb

### ISSUE THREAD

**Issue by arthurzenika** [shinken-monitoring/mod-webui#565]
Sorry to hear that this project is not maintained anymore... any recommendations for an alternative ? 

It seems that since the last time I deployed webui mongodb was introduced. It seems that it is a hard dependency, is it the case ? Can I still use sqlite ? or a file ?  If so, how do I configure it ? 

Using a sqlite uri

```
   uri          sqlite://webui.sqlite

``` 

 I get :  

```
broker_1       | [1493377304] ERROR: [broker-master] [WebUI-MongoDBPreferences] Exception: Invalid URI scheme: sqlite
```

**Comment by mohierf** [comment]
With the most recent versions of this project, we decided to use mongodb as the webui backend, this to have a better integration with several other Shinken modules: logs, retention, ... I must admit that we deprecated the sqlite backend and I am not sure this may be easy to restore it (indeed I never tried).

I do not know of any alternative solution for Shinken. On my own, I moved to the Alignak project

**Comment by arthurzenika** [comment]
do you know if there is a way to install a previous version of webui2 that supports sqlite ? (with the shinken install command ? )

**Comment by mohierf** [comment]
No way ... sorry

**Comment by maethor** [comment]
@arthurlogilab  since webui2 mongodb is indeed a hard dependency because we choose to make one setup that work instead of 5 that don't.

With that said, for this need mongodb is stable and just work. If your server is dedicated to monitoring, you don't need to worry about installing it.
