### ISSUE TITLE
Missing state_down.png and state_up.png images

### ISSUE THREAD

**Issue by rdoursenaud** [shinken-monitoring/mod-webui#57]
In Shinken 2.0-RC2 (don't know the mod-webui version), the generic-host.cfg templates states we can use server, database, disk or network_service as icon_set.
But state_down.png and state_up.png images only exists for server.
This leads to broken image links in WebUI.

**Comment by Dual-Boot** [comment]
Hi,

 I met the same problem and used this simple workaround : 
cp -a /var/lib/shinken/modules/webui/htdocs/images/sets/database/state_ok.png /var/lib/shinken/modules/webui/htdocs/images/sets/database/state_up.png
You can also rename it only but I prefer to have an old copy.

Regards,
