### ISSUE TITLE
save_user_preference is not defined 

### ISSUE THREAD

**Issue by cedlerouge** [shinken-monitoring/mod-webui#570]
Hi, 

With the installation of webui2 version 2.5.0, /static/js/shinken-actions.js seems not be requested and so when a user wants to add widgets, he can't because of the javascript error : `save_user_preference is not defined (widjets.js:166)`  . 

to turn around : 
```
git clone --branch 2.4.2c https://github.com/shinken-monitoring/mod-webui.git /tmp/mod-webui
mv /var/lib/shinken/modules/webui2 /var/lib/shinken/modules/webui2_2.5.0
rsync -a /tmp/mod-webui/module/ /var/lib/shinken/modules/webui2
```
Then you can go back to the web interface and add widgets.

Does someone have the same behaviour ?

**Comment by lermit** [comment]
I think this issue is resolve here : https://github.com/shinken-monitoring/mod-webui/pull/569

:)

**Comment by cedlerouge** [comment]
Yes this is it, I didn't saw this issue. 
Thx

**Comment by bmalynovytch** [comment]
Same problem applies to "currently" dashboard, same fix works fine.
