### ISSUE TITLE
issues with dashboard currently

### ISSUE THREAD

**Issue by pirona** [shinken-monitoring/mod-webui#582]
Hello,

I have a non-updated shinken in production.
I also have an updated shinken, separated from the first one including this commit : https://github.com/shinken-monitoring/mod-webui/commit/ccdf31341a7c347bd09bccd3cc6e030102062905
I have two because I want to move the first one to another server.

Except that : 

I'm meeting this following issue, when going to dashboard/currently.
I'm a bit confused because my non-updated server don't have the correction from the commit, and dont have any issues : https://github.com/shinken-monitoring/mod-webui/commit/ccdf31341a7c347bd09bccd3cc6e030102062905

The second on is updated hence corrected but this page (clicking on the eye on the dashboard) give me that : 
`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 1737, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 509, in lock_version
    return f(**args)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3622, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3598, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3402, in render
    self.execute(stdout, env)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3389, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/dashboard/views/currently.tpl", line 570, in <module>
    %pct_known_problems=round(100.0 * known_problems / h['nb_elts'], 2)
ZeroDivisionError: float division by zero`

Do you have an idea ?

**Comment by maethor** [comment]
Hi @pirona 

It seems you are not running the code you think you are. On your paste I can't see the modification added by https://github.com/shinken-monitoring/mod-webui/commit/ccdf31341a7c347bd09bccd3cc6e030102062905

**Comment by pirona** [comment]
Hello,

thanks for answering. I got rid of several configuration error by checking this : 
/usr/bin/shinken-arbiter -v -c /etc/shinken/shinken.
- in broker.cfg and arbiter.cfg : webui was called in modules instead of webui2

but the error is still there.

This is strange indeed because the one getting the error is the most recent one : 
Shinken Logo Shinken 2.4.3 — Web User Interface 2.5.3, ©2011-2016

The other one running smoothly is  : 
 Shinken 2.4.3 — Web User Interface 2.4.2c, ©2011-2016 

I'll keep digging and keep this post up-to-date.

**Comment by pirona** [comment]
Also,

I checked the updated file of that commit which appears to be right : 
![image](https://user-images.githubusercontent.com/31767324/30266737-96fd0dd0-96e0-11e7-8e3b-84173a0baee8.png)

EDIT : I also checked line 570, which is identical to the one in the functional shinken
Maybe I'm reading this wrong, or missing a line ?

**Comment by maethor** [comment]
You are right, the file is fine, but I think it is not this file which is loaded by your app. I don't know. How did you installed the two webuis ? I don't think you are supposed to run two different versions at the same time.

**Comment by pirona** [comment]
You're right I'm not ! 

I'm not exactly sure of how it was done because I didn't do it ... I'm there to analyze and correct whatever is wrong.
Obviously I'm having a hard time to do it :D

**Comment by maethor** [comment]
I don't think I will be able to help you. Two shinken on the same server seems to be a recipe for disaster.

**Comment by pirona** [comment]
Maybe I was unclear about that : the two shinkens are not on the same server.

The old and functional one is in production.
The other updated one with problems is still a work in progress, running but not in production.

They are installed on two different servers.

**Comment by maethor** [comment]
Oh, ok then.

**Comment by pirona** [comment]
Do you think it is risk free to follow this process : 
```
# Log in with your shinken user account ...
$ su - shinken

# Save previous configuration ...
$ cp /etc/shinken/modules/webui2.cfg /etc/shinken/modules/webui2.bak

# Install update package ...
$ shinken install webui2

# Restore previous configuration ...
$ cp /etc/shinken/modules/webui2.bak /etc/shinken/modules/webui2.cfg
```
 ?

**Comment by maethor** [comment]
I don't know. The package is already installed so I don't think shinken-cli will reinstall it.

Try `shinken update webui2` maybe.

**Comment by pirona** [comment]
I m gonna try another approach : my own installation from scratch. We 'll see where this issue comes from then.

**Comment by pirona** [comment]
Solved it not sure how.
-maybe user permissions, not elevated enough
