### ISSUE TITLE
Global bookmarks

### ISSUE THREAD

**Issue by willowpet** [shinken-monitoring/mod-webui#587]
last release of webui:

how to access to global bookmarks ? I can only view this with manage bookmarks (I need to create a user bookmark before to acces to this menu)

**Comment by maethor** [comment]
Hi @willowpet,

Since you didn't post any screenshot, I'm not sure to understand your problem.

To create a global bookmark you need to create a user bookmark, then go to "Manage bookmarks", and use the button to make it global. After doing that, you should see a global bookmark in the bookmarks menu.

**Comment by willowpet** [comment]
Hi,

I added some global and user bookmarsk but there are not bookmarks in the bookmarks menu.

**Comment by maethor** [comment]
I can't reproduce. Bookmarks are working well on my setup.

Was it working on the last version? (2.5?)

**Comment by willowpet** [comment]
2.6

**Comment by maethor** [comment]
I'm sorry, was it working on the previous version, 2.5?

**Comment by willowpet** [comment]
yes, it worked with the previous version

**Comment by maethor** [comment]
I'm sorry but since I cannot reproduce the problem, can you describe me exactly what is working and what is not. Do you see all the bookmarks in the modal popup ? Do you see user bookmarks in the menu, or no bookmark at all ? Please add screenshots if you can.

**Comment by willowpet** [comment]
I don't see any bookmarks in the modal popup., just "No defined bookmarks"

**Comment by maethor** [comment]
Can you paste me the output of `sudo grep Preferences /var/log/shinken/brokerd.log` ?

**Comment by willowpet** [comment]
no match

**Comment by maethor** [comment]
It seems you don't have the mongodb storage backend configured. Can you check that your webui2.cfg didn't changed when you did the update? But I don't understand, you should have at least an exception of some kind.

`sudo grep prefs /var/log/shinken/brokerd.log` ?

**Comment by willowpet** [comment]
We use mongodb at storage backend
uri                        mongodb://.....

**Comment by maethor** [comment]
With all respect, if you don't answer half of my questions I will let you debug this by yourself.
I do this on my free time, so please make an effort.

**Comment by willowpet** [comment]
no match for grep prefs /var/log/shinken/brokerd.log
no change for webui2.cfg

**Comment by willowpet** [comment]
I restart shinken and grep Preferences match:

[1506688681] INFO: [broker-master] [WebUI-MongoDBPreferences] mongo uri: mongodb://xxxx1:27017,xxxx2:27017,xxxx3:27017,xxx4x:27017
[1506688681] INFO: [broker-master] [WebUI-MongoDBPreferences] database: shinken, user: None
[1506688681] INFO: [broker-master] [WebUI-MongoDBPreferences] Trying to open a Mongodb connection to mongodb://xxxx1:27017,xxxx2:27017,xxxx3:27017,xxxx4:27017, database: shinken
[1506688681] INFO: [broker-master] [WebUI-MongoDBPreferences] connected to mongodb: mongodb://xxxx1:27017,xxxx2:27017,xxxx3:27017,xxxxx4:27017
[1506688681] INFO: [broker-master] [WebUI-MongoDBPreferences] connected to the database: shinken
[1506688681] INFO: [broker-master] [WebUI-MongoDBPreferences] searching connection test item in the collection ...
[1506688681] INFO: [broker-master] [WebUI-MongoDBPreferences] updated connection test item
[1506688681] INFO: [broker-master] [WebUI-MongoDBPreferences] database connection established

**Comment by maethor** [comment]
Can you open a console in your brower and (on chrome, right click, inspect, console), reload any shinken webui page, and tell me if you see an error about bookmarks.

If so, I just fixed your bug, it will be pushed in the coming 2.7 unless I need to make a 2.6.1.

**Comment by willowpet** [comment]
Hello,

I have this error:

dashboard:116 Uncaught ReferenceError: declare_bookmark is not defined at dashboard:116
(anonymous)	@	dashboard:116

Thanks for your help

**Comment by willowpet** [comment]
that's works, thank you very much
