### ISSUE TITLE
Support for grafana

### ISSUE THREAD

**Issue by torgiren** [shinken-monitoring/mod-webui#588]
Hi.
There are plugins for graph from pnp4nagios and graphite...
Is there any chance, for plugin for grafana?

**Comment by maethor** [comment]
Hi @torgiren,

Sadly not, and I don't use grafana myself so I cannot help. But I know @guillaume-u is really motivated to make one. That's right @guillaume-u ? :)

@torgiren If you know how to develop in Python, I can also explain to you how to do it. You just need a function that return an list of images for a given element between two given timestamps. For example,  `mod-ui-pnp` is just a matter of 100 lines of code.

**Comment by torgiren** [comment]
ok, thanks.
I will look at this, when I configure my new installation of shinken and grafana
