### ISSUE TITLE
tooltips in «Minemap» break the table columns

### ISSUE THREAD

**Issue by ornoone** [shinken-monitoring/mod-webui#590]
### version
Shinken 2.4.3 — Web User Interface 2.6.1,

### page

minemap

### expected behavior 

when I mouse over un item in the table, a tooltip apeare to show me detail on the over status. (ie: warning 12 sec ago)

### current behavior

the tooltip is there, but it shift all item to the right. 

### hypothesis

after a small inspection, it seem that the tooltip is anchored to the <td>, and the <div> which host the tooltip is appended after this <td>. so the table tr is broken with a <div> surrounded with <td>

![screenshot-shinken](https://user-images.githubusercontent.com/5380232/31342488-3aa32e5a-ad0d-11e7-9ee5-35cd846de314.png)

as seen in this screenshot, an empty col is visible, but the next check (ok) was hier before the tooltip

**Comment by maethor** [comment]
Thank you @ornoone, I will take a look.

**Comment by bmalynovytch** [comment]
I can confirm the behavior.
I also noticed that hovering the row moves everything one column to the right, while hovering the circles messes everything on its right.
