### ISSUE TITLE
Webui2 does not show host/service overview panel,

### ISSUE THREAD

**Issue by khanga6tm** [shinken-monitoring/mod-webui#596]
Dear all,

I am facing big problem with webui in my production (I did not face in my lab). That is webui does not show overview panel, my staff does not get IP Address of problem host to process. 
In my lab it showed 
![image](https://user-images.githubusercontent.com/27798807/31765287-152ec920-b4ee-11e7-90eb-5960a54957e6.png)

But in production it does not show.

**Comment by maethor** [comment]
Hi @khanga6tm 

That is not what I would call a big problem :)

This panel has been removed 2 or 3 versions ago. So I think your lab is just outdated. What WebUI version are you running? Anyway, you should upgrade to the last version (2.7.0).

**Comment by khanga6tm** [comment]
Hi Maethor,

Thanks for your feedback, I did upgrade to 2.7.0 yesterday. 

For me that is ready big problem because no ip address is no escalation. 

I am using thruk right now, it is old and works slow.

**Comment by maethor** [comment]
I'm sorry, I don't understand. What are you trying to do? Escalations are not managed by the WebUI, but directly by Shinken. What do you need this overview panel for?

**Comment by maethor** [comment]
Oh, I understand now. Indeed, the address is not displayed in the Information tab. I will fix this. Thank you.

**Comment by maethor** [comment]
@khanga6tm I just published 2.7.1 which fixes your problem and should be available in shinken.io in a couple of minutes. Please update and tell me if that's ok for you.

![toto](https://user-images.githubusercontent.com/2410576/31807854-b8f4aa48-b570-11e7-8751-1eb63cb75619.jpg)

**Comment by khanga6tm** [comment]
Great! thanks for your support!

**Comment by maethor** [comment]
Your welcome :)
