### ISSUE TITLE
Is Webui running on Windows ?

### ISSUE THREAD

**Issue by SriRaoul** [shinken-monitoring/mod-webui#597]
Hello,

   

 I'm trying to start Webui 2.5.4 on a Windows Server 2012 R2. Among many errors, I've got 

[91m[1508493694] ERROR: [broker-master] Could not import bare 'module.py' from C:\shinken\var\modules\webui2 : No module named crypt

Since crypt is an unix specific module, and that I ran into other issues which I think are related to multiprocessing on Windows, I wonder : is webui meant to run on Windows ?

Thanks

**Comment by maethor** [comment]
Hi @SriRaoul 

First, please use the last version of the WebUI, that is 2.7.0. I will not offer support on old versions.

I really don't know if you will be able to run the webui on Windows. I'm not using Windows myself, sorry.

**Comment by mohierf** [comment]
IMHO I think it should run on Windows ... nothing in the source code should fail ... but I never tried.
