### ISSUE TITLE
Time on Webui2 is not correct

### ISSUE THREAD

**Issue by khanga6tm** [shinken-monitoring/mod-webui#599]
Hi all,
Thanks for reading! 
I faced issue about time in webui2. My time and webui2 time is not correct. does anyone suggest me a solution or hot-fix for it? 
![image](https://user-images.githubusercontent.com/27798807/32649228-d805615e-c62b-11e7-8d4c-39047b332f3b.png)

**Comment by ornoone** [comment]
hi khanga6tm

- what is the timezone of your shinken server ?
- whit is the timezone in your shinken's conf ?
- is it the same timezone as your desktop ? 
- is your server sync with a time server ? `apt-get install ntpdate`

**Comment by khanga6tm** [comment]
Thanks for your response. Off course before sending a post I checked it.
First - Time in server and my laptop
![image](https://user-images.githubusercontent.com/27798807/32709977-4ab3a16a-c867-11e7-9195-75490b984a00.png)
2nd - Ntpd is working
![image](https://user-images.githubusercontent.com/27798807/32709978-53324968-c867-11e7-94fe-382397d52215.png)

3rd - I configured Time zone already in shinken.cfg 
![image](https://user-images.githubusercontent.com/27798807/32709996-6b0e53a6-c867-11e7-9c1d-451d423a6b25.png)

**Comment by ornoone** [comment]
can you check the timezone of your webui2.cfg ?
you set your timezone of shinken daemon, which is good, but the webui use a different config file located in `module/webui2.cfg` 

edit: I did successfully change my tz displayed by changing this settings and restarting in order the arbiter and the broker

**Comment by khanga6tm** [comment]
Thank you! 

I changed as your guide. The dashboard time is correct. 

![image](https://user-images.githubusercontent.com/27798807/32877952-833bc492-cad6-11e7-8621-220d1fd822ae.png)


But the time check is not correct

![image](https://user-images.githubusercontent.com/27798807/32877986-a577623c-cad6-11e7-93ac-6968e194bc8c.png)

**Comment by khanga6tm** [comment]
Hi all,

I would like to announce the issue was over. After reboot the server, time is correct. 

Thank for all feedback!
