### ISSUE TITLE
[Webui 2.7.1] Issue with service description which contain accented letters

### ISSUE THREAD

**Issue by xsylx** [shinken-monitoring/mod-webui#600]
We running Web ui 2.7.1.

When you are on a host, you can see all service and you can click on "service description" to check details. When a service description contain an accented letter a 404 page is displayed.

If you replace accented letters by letters, it's works fine.

**Comment by maethor** [comment]
Hi Sylvain,

It may be a bug in the regex search, honestly I don't think I will fix it.

**Comment by xsylx** [comment]
Hi Maethor,

Thanks for your answer. We can try to fix it if you tell us where we have to search. 

Accented letters works fine in 2.6.x.

Thx

**Comment by maethor** [comment]
Hm, so it is a regression. That's odd, I didn't touch the datamanager too much. So I really don't know where to begin the search. Maybe check if the link points to the same URL in 2.6 and 2.7, to check if the problem is the link generation or the routing of the URL.

**Comment by xsylx** [comment]
My bad, it doesn't work on 2.6.x .... and 2.4.x....

So if you won't fix it, i will close this issue.
