### ISSUE TITLE
clean old or resolved issues

### ISSUE THREAD

**Issue by ornoone** [shinken-monitoring/mod-webui#601]
I know it can be boring, but i think it can be a good idea to refresh actives issues. I can bring some support with you, but it will be easier to start from scratch. 

what do you think @maethor ?

**Comment by maethor** [comment]
Hi @darius,

What do you mean by "start from scratch"? Do you think we should completely purge the tracker?

**Comment by ornoone** [comment]
no, but check if some are really outdated and if some other will probably never be fixed. maybe add some tags like «won't fix» or «need details». I am sure that some open issues is no revelants anymore

**Comment by maethor** [comment]
OK. I'm doing it from time to time. If you want to take a tour now, be my guest :)
