### ISSUE TITLE
Output parsed wrong

### ISSUE THREAD

**Issue by cleonn** [shinken-monitoring/mod-webui#602]
https://github.com/shinken-monitoring/mod-webui/blob/0b890c06c2f63dca84293079733e58144cfa514f/module/plugins/problems/views/problems.tpl#L185

This will parse a line looking like:

`>>> /path/to/file: syntax error near line 2 <<<`

wrong and output it like:

`<!---->&gt;&gt; /path/to/file: syntax error near line 2 &lt;&lt;&lt;--&gt;`

This entire line could be removed? I'm guessing it's there for debugging purposes? 

Or one could remove the exclamation mark to get unparsed text.

**Comment by maethor** [comment]
Hi,

Thank you for your comment. Indeed, this is not the good way to comment jinja stuff. We should use `{# #]` instead. It could be a huge cleanup work, not only this line, so I will need some to fix this.

Thanks you.
