### ISSUE TITLE
Webui2 with network map on shinken

### ISSUE THREAD

**Issue by kmay83** [shinken-monitoring/mod-webui#608]
Hi everyone ! 
I'm on CentOS, with shinken 2.4.3 and webui2
I'm looking for widget like to network map on nagios.

Can you help me ?
Thx

**Comment by b-keller** [comment]
You can use world map in tactical views or Worldmap widget !
You must define `_LOC_LAT` and `_LOC_LNG` in all host config file you whish to see in world map.

https://github.com/shinken-monitoring/mod-webui/wiki/Configuration---Worldmap
