### ISSUE TITLE
[2.7.2]element view access

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-webui#609]
Hi,

I can't access any elements from search, group or problem views : 
Actually, if I clic on any elements from this views, the link send me back to search... 
`http://xxx.xxx.xxx.xxx:7767/all?search=host:sw4` 
but it shoud be 
`http://xxx.xxx.xxx.xxx:7767/host/sw4`

I missed something ?
Thx

**Comment by maethor** [comment]
This is a behavior change in 2.7. For an host, I think the "search" view is more useful and well designed than eltview. This is true only for hosts. If you clic on a service name you are linked directly in the element view.

To access an element you have a "Details" link in the accordion. Do you see it?

**Comment by b-keller** [comment]
Ok, perfect.
thanks for the explanations !
I close.
