### ISSUE TITLE
Services remain shown as in downtime after end of downtime

### ISSUE THREAD

**Issue by bmalynovytch** [shinken-monitoring/mod-webui#611]
Webui2 reports services in downtime for ever.
The services stuck in this case are passive checks.
If think it's only webui related, because we still get notified when the services changes state.

WebUI: 2.7.2

**Comment by maethor** [comment]
Hi @bmalynovytch 

I don't use passive checks so it will be quite hard to debug for me. Do you have the problem everywhere in the webui, or only in some pages?

**Comment by bmalynovytch** [comment]
It seem to be general.
If you could point me the code that gathers the state to be displayed or handlers the "state to display", I'll run some tests to check wether it's GUI or core related.

**Comment by maethor** [comment]
I can't, this code is in shinken core, not in the webui. I really think it is core related because in the webui we just use `element.in_scheduled_downtime` to know if an element is in downtime.
