### ISSUE TITLE
Add service tags in service view

### ISSUE THREAD

**Issue by DessaiImrane** [shinken-monitoring/mod-webui#62]
Hi,

This is a non critical enhancement that can help in some cases.

On webui, we can see at the top right corner of a host page, the tags (templates) that apply to the host.

It should be cool, if we can have somewhere in the service page, the service's tags.

I'm very bad at web design but I can help anywhere else if you help me (by telling where to look for instance)

**Comment by mohierf** [comment]
Closing ... future release includes this feature.
