### ISSUE TITLE
Update of wiki - installing webui authentication modules

### ISSUE THREAD

**Issue by thifranc** [shinken-monitoring/mod-webui#625]
Hi,

I've recently got into minor trouble to set up auth-active-directory module.
I think that community could benefit from a warning about the fact that we still need a cfg/contact file even if we have correctly set up the auth-active-directory module.

So I took the liberty to clone the wiki and update it on my side, because we can't create PR for this, I chose to follow those guidelines :  https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

Hence, here is my repo with the doc updated.

https://github.com/thifranc/shinken-webui-wiki-up

**Comment by maethor** [comment]
I agree this is quite a pain to work with. But it is said in the documentation https://github.com/shinken-monitoring/mod-auth-active-directory

Anyway, please open an issue in mod-auth-active-directory if needed.
