### ISSUE TITLE
webui2 dashboard currently

### ISSUE THREAD

**Issue by esebille** [shinken-monitoring/mod-webui#627]
hello,
i wanted to know how to keep the states between refreshes of the dashboard currently. I dopnt know which plugin to use for the retention of the dashboard currently

**Comment by maethor** [comment]
Hi @esebille 

The only retention plugin officially supported is mongodb. The module is embedded in the WebUI, so you only need to install the mongodb service and mongodb python packages, as described here : https://github.com/shinken-monitoring/mod-webui/wiki/Installing-WebUI-storage-modules

**Comment by esebille** [comment]
The service and plugin are installed but each time i refresh the dashboard currently all graphs are back to zero. I think there is something i don't understand.

Thanks

**Comment by maethor** [comment]
I'm not sure to understand the problem. When we talk about retention, it's data retention between shinken restarts. Typically, if you configure the dashboard for your user and you restart shinken, you should get the same dashboard after restart.

A simple way to test this is to go in the "problems" page, where you see the list of problems. By default the page displays 20 elements. In the bottom you can change this number, and select 100 elements. Do this, leave the page, restart shinken, come back, you should see "100" in the selector. If you see 20 the retention does'nt work.

Can you explain exactly what you are doing, step by step, what should be the result and what is the result?

**Comment by esebille** [comment]
The problem is that graphs generated by the webui are not stored. each time i reload the dashboard page previous problems disapears. I want to be able to reload the page without losing informations. Sorry if i am not clear in my explanations it's not really clear in my head.  
here's a snapshot of the graphs that i want to be stored between refreshes of the page

[https://ibb.co/eoXfcq](url)

**Comment by maethor** [comment]
Ok, this is completely normal. I have to say that I don't understand what is the point of these graphs (I don't even see the point of the dashboard view, /problems is so much better). Seems completely useless to me. But this is legacy stuff so I didn't what to remove them from webui2.

**Comment by esebille** [comment]
Ok i thought i've really does not understand how it works. But still i want to be able to make yearly reports of my monitoring. Is it possible ?

Thanks

**Comment by maethor** [comment]
Depends, what do you want to display exactly in your reports?

Anyway, yearly will not be possible with standalone webui because the retention is configured for 3 months by default (and you shouldn't set more because it's quite a computational challenge).

If you send alerts to a slack, you can have some nice stats in `\stats`, although I have to admit it is a beta and undocumented feature.

You can also have graphs for each service by configuring graphing modules (https://github.com/shinken-monitoring/mod-webui/wiki/Installing-WebUI-graph-modules), but this will not provides you with some meta graphs about the monitoring itself.

**Comment by esebille** [comment]
i want to display rapports about hosts availability through the year to give a report to my boss. I know it is possible in nagios but i don't know about shinken

Thanks

**Comment by maethor** [comment]
In tactical view -> host availability, but only for the last 3 months.

**Comment by esebille** [comment]
I dont have this option under tactical view ! 
![shinken](https://user-images.githubusercontent.com/44777114/48144134-9a8f3c80-e2b0-11e8-9297-86da0d320173.png)

**Comment by maethor** [comment]
Please check the documentation https://github.com/shinken-monitoring/mod-webui/wiki/Installing-WebUI-logs-and-availability-modules to check if you have enable everything. 

If you don't have `Tactical view -> Availability` and `System -> History`, it means you do not have any log module enabled.

**Comment by esebille** [comment]
Here's the result of my shinken inventory command 
ui-pnp
imap
npcdmod
ldap
rhev
http-proxy
retention-redis
dns
mod-mongodb
smtp
switch
graphite
ui-graphite2
mongodb
dhcp
ssh
mod-mongodb-notification-broker
pack-rhev
oracle
graphite2
linux-ssh
linux-snmp
pickle-retention-file-scheduler
logstore-mongodb
mod-mongodb-dt-ct-retention-scheduler
auth-active-directory
mod-influxdb
logstore-sqlite
mongo-logs
http
webui2
webui
hp
livestatus
mod-mongodb-retention-scheduler
ui-graphite
windows
I do think i have a log module installed. And by the way is there a way to remove unused modules from shinken ?

Thanks

**Comment by maethor** [comment]
I am sorry I cannot do this kind of support. Please seek help on shinken's IRC, mailing list or forum.

It seems you have a lot of unwanted modules.
