### ISSUE TITLE
Availability menu is always present

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#629]
The Availability menu is always present in the left menu pane even if no availability log are available. 

If the `hav_collection` configuration parameter is set to an empty value removed to indicate that the feature is not available., the menu should not be displayed.

**Comment by mohierf** [comment]
The same behaviour may be implemented for the System and hosts logs and history if the `logs_collection` parameter is empty

**Comment by maethor** [comment]
I'm not sure about this. I think these menus can encourage users to configure logs_collection and hav_collection, because they are useful, but hidden, features. Don't you think?

**Comment by mohierf** [comment]
@maethor: yes, I do agree. But if a user configures `uri=` in the configuration, it means that he/she intentionaly do not want any mongo connection. As such, hiding th unuseful menu looks like a good solution.

**Comment by maethor** [comment]
OK, seems good to me, with a comment in the configuration to explain the behaviour.
