### ISSUE TITLE
Add "custom text block" to service definition

### ISSUE THREAD

**Issue by DessaiImrane** [shinken-monitoring/mod-webui#63]
Hi,

This is a non critical enhancement that can help in some cases.

Here is my use case. I have a KnowledgeBase (KB) with many resolution page.

A good idea (for me and for my technicians) is to link each service to a resolution page. So that in case of alert, the technician can click on the service page on WebUI and click to the resolution link given there. It will help him in solving the problem.

If we look any further, this feature can be used by admins to add some custom messages/notes to services (or even host)

Maybe, this can be achieved by using a new (or existing) property of Host and Service.
Then WebUi just have to output it properly.

May be we can go any further (again) by making this property able to be defined multiple time. So that we can add multiple custom text/message/note

Here is an exemple : 

```
define service{
   service_description           Snapshots Count
   use           vmware-service
   register       0
   host_name	  vmware-vcenter
   check_command  check_vmware_snapshots_count


   notes   "KB : http://..../KB-number-X
   notes   "Explanation : This service checks ....
}
```

Each "notes" can be a small box (or widget) in webui which can have a title.
The title can be defined as the string before the ":" 

I post this idea because I have the need and I guess I'm not the only one.
It can be a "gadget" feature than can help "managers" to accept Shinken.

What do you think ?

**Comment by mohierf** [comment]
Should be included in a future release ...
