### ISSUE TITLE
Login page - logo is very very pale...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#652]
On the login page, the logo is really very very pale ...

For Shinken:
![image](https://user-images.githubusercontent.com/2932687/49058946-a8c4de80-f206-11e8-86bc-03dada406c5a.png)

For Alignak:
![image](https://user-images.githubusercontent.com/2932687/49058724-87afbe00-f205-11e8-8f0e-183fe968865f.png)

**Comment by mohierf** [comment]
Several tests:
- bootstrap info 
![image](https://user-images.githubusercontent.com/2932687/49059252-3f45cf80-f208-11e8-9ea0-b4df52d0a9c6.png)

- bootstrap primary
![image](https://user-images.githubusercontent.com/2932687/49059232-2806e200-f208-11e8-8357-b15905eb08f9.png)

- simple grey
![image](https://user-images.githubusercontent.com/2932687/49059413-1a059100-f209-11e8-8a95-ab89ec6d9032.png)

What do you think about it @maethor ?

**Comment by maethor** [comment]
Primary seems really fine to me.
