### ISSUE TITLE
Clean the breadcrumb ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#667]
Replacing this: 
![image](https://user-images.githubusercontent.com/2932687/49689001-c35a5a00-fb1a-11e8-87ec-d8febc2751fc.png)
![image](https://user-images.githubusercontent.com/2932687/49689032-44195600-fb1b-11e8-8a83-cb2c8fd87de7.png)

with this:
![image](https://user-images.githubusercontent.com/2932687/49689006-d53bfd00-fb1a-11e8-9379-f2ebb65ad54f.png)
![image](https://user-images.githubusercontent.com/2932687/49689040-585d5300-fb1b-11e8-974f-f3209239d864.png)

makes the UI cleaner, no?

Anyway, the Home in front of the breacrumb is always present and it is unuseful!

**Comment by maethor** [comment]
OK.
