### ISSUE TITLE
Contact list, improvements proposal

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#676]
As of now, the contacts list:
![image](https://user-images.githubusercontent.com/2932687/49936285-d29f2600-fed3-11e8-96d0-63601c316f57.png)

The yellow star indicates an administrator conatct (`is_admin`)
The green start indicates a power user (`can_submit_commands`)

Replacement proposal:
---
![image](https://user-images.githubusercontent.com/2932687/49937760-1b58de00-fed8-11e8-957f-608a96bf3519.png)

The ides behind:
- the color is not useful for the icon ... only the icon indicates the profile
- the icon is significant for the profile

An eye for the administrators that can view everything ...
A bullhorn for the users that can send commands ...

To be discussed 😉

**Comment by maethor** [comment]
OK.
