### ISSUE TITLE
Notes display in the problems view

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#677]
When an host has some notes defined, their display in the problems view is not really nice rendered ...

![image](https://user-images.githubusercontent.com/2932687/49939585-8bb62e00-fedd-11e8-97fb-859105aaeeae.png)

**Comment by mohierf** [comment]
This is mainly due to the notes encoding format ... I will fix this 😉

**Comment by mohierf** [comment]
The same problem exist in the element view:
![image](https://user-images.githubusercontent.com/2932687/50199617-3dc47e80-0352-11e9-836d-9bb82d713a80.png)


Furthermore, there is no more tags in the element view whereas tags are really useful as search criteria ... find all hosts base on a specific template 😉

**Comment by mohierf** [comment]
The rendering may be this in the element view:
![image](https://user-images.githubusercontent.com/2932687/50267998-784d1a80-0429-11e9-9028-085162002403.png)

**Comment by mohierf** [comment]
And this in the problems view:
![image](https://user-images.githubusercontent.com/2932687/50268666-ee528100-042b-11e9-9be1-4efd6616467e.png)

**Comment by maethor** [comment]
@mohierf So it does not manage URL anymore ? I agree we could find a way to manage HTML, but I don't agree with what you did, I'm reverting the PR.

Moreover,  I don't know how you configured what you are showing here, but `notes` and `notes_url` are not lists of notes and urls. You should only define one note and one URL (and one action url), as documented here : https://shinken.readthedocs.io/en/latest/08_configobjects/host.html

**Comment by maethor** [comment]
I reverted your commits. We need to discuss it because it is adding a lot of complexity, both in the UI and the code, and as I understand it in the documentation you are not supposed to declare multiple notes and URLs like what you are doing here. So I prefer to keep it simple.

If you want to improve and manage multiple notes and URL, why not, but it needs to be way simpler in the UI.

**Comment by mohierf** [comment]
Indeed, it is very simple as I did it ... and it is documented in the project Wiki. The solution I implemented still existed since a long time and it is quite commonly used in the Nagios configuration files ... 

Sure that your are not supposed to declare list in notes (and you are not obliged indeed...) but if you want to declare some, the implementation I did allows to do it. And if you do not use any list in notes, notes_url or actions_url, you are not obliged to do so ...

If they are not lists:
- notes is rendered simply as a text
- notes_url is rendered as a button instead of displaying the URL. 
- same for actions_url

**Comment by mohierf** [comment]
As an example:
```
   notes                This is a MongoDB host!
   notes_url            http://www.my-KB.fr?host=$HOSTADDRESS$
   action_url           http://google.fr
```
is rendered as:
![image](https://user-images.githubusercontent.com/2932687/50604017-dcf28580-0ebd-11e9-8c91-8601e45d9429.png)

**Comment by maethor** [comment]
This is the display since I reverted your commits. But it didn't displayed like this before. Cf your own screenshots in this issue 14 days ago.

**Comment by mohierf** [comment]
The screenshot I posted 14 days ago are rendering when you define some lists as explained in the wiki ... not for a Nagios-like configuration without any list.

If I revert your revert 😉 I get this with the same configuration:
```
   notes                This is a MongoDB host!
   notes_url            http://www.my-KB.fr?host=$HOSTADDRESS$
   action_url           http://google.fr
```
![image](https://user-images.githubusercontent.com/2932687/50625356-ef090e00-0f27-11e9-8373-a1b57215cbe1.png)

The only differences are:
- tags are displayed if any are defined 
- actions and notes are separated

What is the point with this ?

**Comment by maethor** [comment]
And what about the note in a ugly and useless box which seem clickable when I over with the mouse?

Also, I want to keep url notes as links instead of buttons, at least in /problems view. I find it cleaner.

**Comment by mohierf** [comment]
Ok. I clean this and send a new PR

**Comment by maethor** [comment]
My mistake : https://shinken.readthedocs.io/en/latest/07_advanced/multiple-urls.html

**Comment by mohierf** [comment]
@maethor: I will refactor my initial PR with the Shinken doc described format. I will make it also available for notes and notes_url.

*Note that my initial PR is the same implementation as the one that did existed in older Shinken UI versions. We will be able to restore if some users compalin about this...*

**Comment by mohierf** [comment]
In the element view:
-----
![image](https://user-images.githubusercontent.com/2932687/51251037-952d2d00-1998-11e9-9418-9e5e742d00bf.png)

1. one note with HTML content
1. several notes_url. If a title is set it will be rendered as a button with/without an icon. If no title nor icon, it is rendered as the 1st link...
1. same for the actions url


In the problems view:
-----
![image](https://user-images.githubusercontent.com/2932687/51251274-3b793280-1999-11e9-81c3-357ccf5e9833.png)

In the custom host view:
-----
![image](https://user-images.githubusercontent.com/2932687/51252578-7761c700-199c-11e9-8b26-064f920617e2.png)

**Comment by maethor** [comment]
@mohierf can we close?
