### ISSUE TITLE
Display of the action bar on small screens

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#708]
Still  a responsive layout problem on small screens .... grrrrr:
![image](https://user-images.githubusercontent.com/2932687/50989725-6cc4af00-1510-11e9-8df9-84dfd5e1389f.png)

**Comment by mohierf** [comment]
This would be better indeed 😉 

X-small devices:
![image](https://user-images.githubusercontent.com/2932687/51016046-176bba80-156f-11e9-9251-2fde00ab5eb6.png)

Small devices::
![image](https://user-images.githubusercontent.com/2932687/51016078-3c602d80-156f-11e9-8285-04304271cb08.png)

Large devices:
![image](https://user-images.githubusercontent.com/2932687/51016099-4c780d00-156f-11e9-9830-439a5f26e032.png)

**Comment by maethor** [comment]
Can we close this issue?
