### ISSUE TITLE
Frontend Apache Web server with SSL

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-webui#714]
Hi,

I have some trouble to set correctly my apache virtual host config file to allow reverse proxy with shinken and pnp4nagios. I know that's not a webui problem but if someone have any suggestion...
Here is my config file :
```
<VirtualHost *:80>
    ServerName shinken.mydomain.com
    Redirect / https://shinken.mydomain.com/
</VirtualHost>

<VirtualHost *:443>
    ServerName shinken.mydomain.com
    
    SSLEngine On
    SSLCertificateFile /etc/pki/tls/certs/mycert.mydomain.com.crt
    SSLCertificateKeyFile /etc/pki/tls/certs/mycert.mydomain.com.key
    SSLCertificateChainFile /etc/pki/tls/certs/MY_CA.crt
    SSLOptions +StdEnvVars
    SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
    SSLCipherSuite          ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
    SSLHonorCipherOrder     on
    SSLCompression          off
        
    ProxyPreserveHost On
    ProxyRequests On
       
    ProxyPass /pnp4nagios/ http://xyz.xyz.xyz.xyz/pnp4nagios/
    ProxyPassReverse /pnp4nagios/ http://xyz.xyz.xyz.xyz/pnp4nagios/
      		
    ProxyPass / http://xyz.xyz.xyz.xyz:7767/
    ProxyPassReverse / http://xyz.xyz.xyz.xyz:7767/
 
    ErrorLog /var/log/httpd/shinken_error.log
    CustomLog /var/log/httpd/shinken_access.log combined
</VirtualHost>
```
If I enable 
`Redirect / https://shinken.mydomain.com/`
webui work with no problem but pnp4nagios is unreachable (wrong redirection error on web browser)

If I disable
`# Redirect / https://shinken.mydomain.com/`
pnp4nagios is reachable but webui is not redirect to https...

I made some tests with rewrite, directives ordering... no results. I looked at webui wiki with nginx example, I don't understand what I am doing wrong.

**Comment by maethor** [comment]
It seems you have an infinite redirection loop problem. I believe this problem is not on the scope of this vhost only, but finds an explication in all apache2 configuration.

Do you have a default vhost configured in apache2?

With the `Redirect` enabled, if you do `curl -I http://xyz.xyz.xyz.xyz/pnp4nagios/` on your laptop, what do you get? http://xyz.xyz.xyz.xyz should not be managed by this vhost.

Also, you can try to use `localhost` instead of xyz.xyz.xyz.xyz. I would do that, and do not let 7767 port open. But I don't think that alone will fix your problem. First you need to make sure you have a default vhost and pnp4nagios queries are managed by this default vhost.

Lastly, if you don't find any better solution, in the http vhost you can add a condition before Redirect, to avoid redirecting pnp4nagios queries.

**Comment by b-keller** [comment]
Hi,

I found "a" solution, here is the new virtualhost config file : 
```
<VirtualHost shinken.mydomain.com:80>
    ServerName shinken.mydomain.com
    Redirect / https://shinken.mydomain.com/
</VirtualHost>

<VirtualHost *:443>
    ServerName shinken.mydomain.com
    
    SSLEngine On
    SSLCertificateFile /etc/pki/tls/certs/mycert.mydomain.com.crt
    SSLCertificateKeyFile /etc/pki/tls/certs/mycert.mydomain.com.key
    SSLCertificateChainFile /etc/pki/tls/certs/MY_CA.crt
    SSLOptions +StdEnvVars
    SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
    SSLCipherSuite          ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
    SSLHonorCipherOrder     on
    SSLCompression          off
        
    ProxyPreserveHost On
    ProxyRequests On
       
    ProxyPass /pnp4nagios/ http://localhost:80/pnp4nagios/
    ProxyPassReverse /pnp4nagios/ http://localhost:80/pnp4nagios/
      		
    ProxyPass / http://xyz.xyz.xyz.xyz:7767/
    ProxyPassReverse / http://xyz.xyz.xyz.xyz:7767/

    ErrorLog /var/log/httpd/shinken_error.log
    CustomLog /var/log/httpd/shinken_access.log combined
</VirtualHost>
```
I modified : 
`<VirtualHost *:80>` to `<VirtualHost shinken.mydomain.com:80>`

and
```
 ProxyPass /pnp4nagios/ http://xyz.xyz.xyz.xyz/pnp4nagios/
 ProxyPassReverse /pnp4nagios/ http://xyz.xyz.xyz.xyz/pnp4nagios/
```
to
```
ProxyPass /pnp4nagios/ http://localhost:80/pnp4nagios/
ProxyPassReverse /pnp4nagios/ http://localhost:80/pnp4nagios/
```
All is working as expected.

What do you mean with ?
> do not let 7767 port open

Is it possible to add this one or another example of apache config in the wiki ?

Thx

**Comment by maethor** [comment]
When you configure a proxy, like this, it is best practice to close the direct port of the service. Here, you have configured a proxy on apache to transfer requests to port 7767, so you can close 7767 on the firewall to avoid direct queries on it. It's not a big deal, just best practice.

In the wiki there is already a proxy documentation, with Nginx which allows a better controlled configuration than Apache2.

**Comment by b-keller** [comment]
Ok, thanks for your help.
I close.
