### ISSUE TITLE
acknowledge and notify

### ISSUE THREAD

**Issue by vkuharkov** [shinken-monitoring/mod-webui#720]
Hello! 
In our company we use the shinken monitoring.
I have problem with save settings acknowledge and notofication for host in webui2. 
repeat:
1. Go to host info
2. If host have a problem, i'm click to "Acknowledge" or off notification
3. I'm doing restart all shinken or shinken-scheduler and Acknowledge or notification come back to default. 
I have not found unequivocal answer an this question...
Please, help!

We used plugin mongodb, for scheduler we use MemcacheRetention

**Comment by maethor** [comment]
Hi @vkuharkov, thanks for using this webui.

This problem does not concerns the webui, but main shinken app. You need to configure retention for Arbiter and Scheduler (I am not sure to know which one is responsible for this).

**Comment by maethor** [comment]
That is the Scheduler retention which is responsible.
