### ISSUE TITLE
Business rules downtime/acknowledge

### ISSUE THREAD

**Issue by vkuharkov** [shinken-monitoring/mod-webui#721]
Hello! Sorry if I write in the wrong place.

I have problem with a business rule in shinken.
Repeat:

I have a hostgroup, a group that the business rule is configured for
I off a host, he in status "CRITICAL"
business rule goes into state "CRITICAL"
I doing downtime or acknowledge this host
I expect the business rule to become OK.

business_rule_smart_notifications and business_rule_downtime_as_ack on.

I need alerts to come from a business rule when one of the hosts is in downtime or acknowledge, but crashed another host. But since the business rule in critical notification state does not come. Notification come only from host.

Please help!
Thanks!

**Comment by maethor** [comment]
Hi @vkuharkov,

Indeed you are in the wrong place. This repository is dedicated to shinken web interface module. I would have help you but I don't use business rules myself.

You should ask your question in [shinken repository](https://github.com/naparuba/shinken).

Good luck.
