### ISSUE TITLE
[2.8.0] Worldmap not working anymore ?

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-webui#722]
Hi,

I just test the new webui version (thanks a lot for your jobs), and I have some trouble to access woldmap page and dashboard widget.

**Steps to reproduce : world map page**
1. from side menu
2. Click on tactical views
3. Click on worldmap
4. I See  this error
`Error: 500 Internal Server Error
Sorry, the requested URL 'http://x.y.z/worldmap' caused an error:
Internal Server Error`

**Steps to reproduce : world map widget**
1. Click on dashboard icon
2. I See  this error
`Error loading this widget:` 

**Expected behavior**
Access and display worldmap page.
Display world map widget on dashboard

**Screenshots**
![Screenshot_2019-12-03 Error 500 Internal Server Error](https://user-images.githubusercontent.com/12746104/70037081-43908f80-15b6-11ea-881e-dc1386343e44.png)

**Shinken:**
 - Shinken 2.4.2
 - WebUI 2.8.0

I missed some thing ?

Thx

**Comment by maethor** [comment]
I can reproduce. I don't use worlmap myself so this kind of thing might happen :/ I will look at it tomorrow.

**Comment by mohierf** [comment]
I gave a try this morning and I got this error message. It may help @maethor :
```
Error: 500 Internal Server Error

Sorry, the requested URL 'http://localhost/worldmap' caused an error:

Internal Server Error

Exception:

KeyError('hosts_level',)

Traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 703, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3615, in wrapper
    result = func(*args, **kwargs)
  File "/var/lib/shinken/modules/webui2/plugins/worldmap/worldmap.py", line 113, in show_worldmap
    'hosts': search_hosts_with_coordinates(search, user)}
  File "/var/lib/shinken/modules/webui2/plugins/worldmap/worldmap.py", line 73, in search_hosts_with_coordinates
    if h.business_impact not in params['hosts_level']:
KeyError: 'hosts_level'

```

**Comment by maethor** [comment]
Yep, I fixed it. Will be released soon.

Thank you @b-keller
