### ISSUE TITLE
[2.8.0] Contacts not working

### ISSUE THREAD

**Issue by ayaloulameche** [shinken-monitoring/mod-webui#723]
Hello,

I am currently testing the webui version 2.8.0 and I have an error accessing the "Contacts" page (on "Configuration" menu).

Here is the screenshot : 
![image](https://user-images.githubusercontent.com/16012726/70307954-93679480-180a-11ea-88b8-fea0a2beb787.png)

I try to run the webui log in DEBUG mode but there are no additionnal informations about this error in the log :(

I'm on :
OS : Centos 7.7
Shinken : 2.4.3
Webui2 : 2.8.0

Can you have a look ?

Thanks for your help :)

Regards

**Comment by maethor** [comment]
It seems the worldmap is not the only thing that you have broker @mohierf :)

Thank you @ayaloulameche . I will fix it and a new version will be released soon.

**Comment by maethor** [comment]
There, it is fixed, thank you @ayaloulameche. It will be released in 2.8.1 soon.
