### ISSUE TITLE
[2.8.1] logout not working

### ISSUE THREAD

**Issue by ayaloulameche** [shinken-monitoring/mod-webui#724]
Hello,

Thanks for the quick fix of the Webui ;)

I keep testing the 2.8.1 version and I have an error when I try to logout . I try with different contacts (local account or ldap account) and I get the same error every time.

Here is the screenshot :
![image](https://user-images.githubusercontent.com/16012726/70789001-6da23880-1d92-11ea-9d55-6baee239ee9c.png)

I'm on :
OS : Centos 7.7
Shinken : 2.4.3
Webui2 : 2.8.1

Can you have a look ?

Thanks in advance.

Regards

**Comment by maethor** [comment]
Thank you @ayaloulameche , I will have a look next week.

**Comment by Scandiskfr** [comment]
For info !
Same pb for me, it's begin on Webui2 2.8.0 : 
OS : Centos 7.7.1908
Shinken : 2.4.3
Webui2 : 2.8.1
thx.

**Comment by maethor** [comment]
Hi, sorry for the delay and happy new year :)

@ayaloulameche @Scandiskfr I am sorry I cannot reproduce.

Can you activate debug mode in the webui? That would make it display the stacktrace in the error page. To do so:
- Edit `/var/lib/shinken/modules/webui2/module.py` (maybe you will need to adapt the path to fit your install)
- Under line 107, create a new line and add `bottle.debug(True)`, without any indentation
- Restart the broker

Then the webui should display some details on your error.

I will try to make this process easier in the next minor version.

**Comment by ayaloulameche** [comment]
Hello Maethor, 

Happy new year ;)

I have modifying the file /var/lib/shinken/modules/webui2/module.py and restarting the broker, and here is the error with details : 
![image](https://user-images.githubusercontent.com/16012726/71725278-97033100-2e33-11ea-99f0-d5ddf5393305.png)

Thank you.

**Comment by mohierf** [comment]
As far as I remember, I met this problem recently also...

@maethor : you should try:
```
app.response.set_cookie(str(app.session_cookie), cookie_value, secret=app.auth_secret, path='/')
```

See the `str` that makes the cookie a single string rather than a dict

**Comment by ayaloulameche** [comment]
Hello,

Just to let you know, I tested the modification suggested by Mohierf. I modify the file :
/var/lib/shinken/modules/webui2/plugins/login/login.py

Line 90 : 
app.response.set_cookie(app.session_cookie, False, secret=app.auth_secret, path='/')
by 
 app.response.set_cookie(str(app.session_cookie), False, secret=app.auth_secret, path='/') 

and Line 92 : 
app.response.set_cookie(app.session_cookie, '', secret=app.auth_secret, path='/')
by 
 app.response.set_cookie(str(app.session_cookie), '', secret=app.auth_secret, path='/')

And then, the logout works perfectly.
Thank you.

**Comment by maethor** [comment]
Sorry for the delay, and thank you very much for the fix. I will publish this soon.
