### ISSUE TITLE
Dependencies graph page

### ISSUE THREAD

**Issue by reox22** [shinken-monitoring/mod-webui#725]
Hello,All,
In the webui one we can find a dependency page for a host and his witget.

"Dependencies graph widget
Configured with an host, it displays the dependency graph of this host."

see image here : https://github.com/shinken-monitoring/mod-webui/wiki/User-manual-Dashboard

is it in feature we can find again the the webui2.
in the wiki i can t see how to have it.

**Comment by maethor** [comment]
Hi @reox22,

This feature was not working well and depended on a lot of javascripts, so we choose to remove it from webui2. Sorry :)
