### ISSUE TITLE
Log history in element view

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#73]
Based upon the logs plugin, I added a log history tab in the element view ... currently in BS3 branch.

![image](https://cloud.githubusercontent.com/assets/2932687/3759776/4b1cab02-1865-11e4-89d1-00ad7d8ebed9.png)

**Comment by tarak666** [comment]
Hi , 
Can you please give pull request details for history tab.

Thanks,Tarak

**Comment by tarak666** [comment]
Hi,

Can you help me out from this issue, I cant check logs and History from webui.
using: Webui-Bs3 
Shinken 2.2
Error: Sorry, I cannot load the service history!
On log tab: Error : Unable to create mongo DB connection localhost:27017

![hc1](https://cloud.githubusercontent.com/assets/3509727/7881498/50e75a32-0621-11e5-9b10-bbd1e19ead06.PNG)

**Comment by mohierf** [comment]
Have you installed and configured the mongodb module ? and logstore-mongo ?

 If so you should have logs in this tab ...

**Comment by tarak666** [comment]
Yes, I have mongodb and logstore-mongo installed and i see log generating in mongo.
My logstore_mongodb.cfg 
define module {
    module_name     logstore-mongodb
    module_type     logstore_mongodb
    mongodb_uri     mongodb://localhost/?safe=false  ; Set to your value
    # If you are running a MongoDB cluster (called a “replica set” in MongoDB),
    # you need to specify it's name here.
    # With this option set, you can also write the mongodb_uri as a comma-separated
    # list of host:port items. (But one is enough, it will be used as a “seed”)
    #replica_set
    database   shinkenLivestatusLogs
    #collection
    #max_logs_age
}

==================
> show dbs
local   0.078125GB
logs    0.203125GB
shinken 0.203125GB
shinkenLivestatusLogs
use shinkenLivestatusLogs
switched to db shinkenLivestatusLogs
> show tables
logs
system.indexes
ui_user_preferences
> db.logs.find()
{ "_id" : ObjectId("5550574c693dc30ba94e75d7"), "comment" : "", "plugin_output" : "", "attempt" : 0, "message" : "[1431328587] PASSIVE SERVICE CHECK: localhost;Disks;2;", "logclass" : 4, "options" : "", "state_type" : "", "lineno" : 643, "state" : "2", "host_name" : "localhost", "time" : 1431328587, "service_description" : "Disks", "logobject" : 2, "type" : "PASSIVE SERVICE CHECK", "contact_name" : "", "command_name" : "" }
======================================================

**Comment by mohierf** [comment]
The database name is not the default one ... so you should configure the WebUI plugin. Please have a look to the file plugin.cfg in the plugins/logs directory. You should have this self explanatory configuration file : 
```
[plugin]
# Mongo DB server connection
mongo_host=localhost
mongo_port=27017

# Database name
db_name=shinken_logs

# Logs information
# Log type may be:
#  CURRENT SERVICE STATE
#  INITIAL SERVICE STATE
#  SERVICE ALERT
#  SERVICE DOWNTIME ALERT
#  SERVICE FLAPPING ALERT
#  CURRENT HOST STATE
#  INITIAL HOST STATE
#  HOST ALERT
#  HOST DOWNTIME ALERT
#  HOST FLAPPING ALERT
#  SERVICE NOTIFICATION
#  HOST NOTIFICATION
#  PASSIVE SERVICE CHECK
#  PASSIVE HOST CHECK
#  SERVICE EVENT HANDLER
#  HOST EVENT HANDLER
#  EXTERNAL COMMAND

# Filter for these log types (leave empty for no filtering)
#logs_type=PASSIVE HOST CHECK, HOST NOTIFICATION, PASSIVE SERVICE CHECK, SERVICE NOTIFICATION
logs_type=

# Filter for these hosts (leave empty for no filtering)
#logs_hosts=
logs_hosts=

# Filter for these services (leave empty for no filtering)
logs_services=

# Maximum logs
logs_limit=1000

```

**Comment by tarak666** [comment]
okay, I changed database name and even in logstore-mongodb.cfg, but no luck.

My plugin.cfg
===========
[plugin]
# Mongo DB server connection
mongo_host=localhost
mongo_port=27017

# Database name
db_name=shinken_logs

**Comment by mohierf** [comment]
Have you declared mongodb as a module of your webui in webui.cfg ?

Your database name seems to be *shinkenLivestatusLogs* ... and the one used by the webui is *shinken_logs* ... they do not match!

**Comment by tarak666** [comment]
I have changed both databases names as shinken_logs and declared in webui.cfg.
i see log generated in new database.

> show dbs
local   0.078125GB
logs    0.203125GB
shinken 0.203125GB
shinkenLivestatusLogs   0.203125GB
shinken_logs    0.203125GB
test    (empty)
> use shinken_logs
switched to db shinken_logs
> db.logs.find()
 "_id" : ObjectId("55685c52693dc30ec24b179f"), "comment" : "", "plugin_output" : "", "attempt" : 0, "message" : "[1432902737] EXTERNAL COMMAND: [1432902735] DEL_SVC_COMMENT;5", "logclass" : 5, "options" : "", "state_type" : "", "lineno" : 646, "state" : 0, "host_name" : "", "time" : 1432902737, "service_description" : "", "logobject" : 0, "type" : "EXTERNAL COMMAND", "contact_name" : "", "command_name" : ""

**Comment by mohierf** [comment]
Closing ... future release includes this feature.
