### ISSUE TITLE
Acknowledges using the WebUI gesture don't work

### ISSUE THREAD

**Issue by t0xicCode** [shinken-monitoring/mod-webui#84]
The WebUI sends the command with the host `Acknowledged by WebUI gesture.` rather than the correct host/service.

**Comment by tarak666** [comment]
Hi,

We have shinken2.2 installed using pip, everything working fine for me but only downtime is not working.
When i add downtime it showing in log, but not showing on webui or commant box.

Shinken Version:- shinken 2.2

Log in shinken.log

EXTERNAL COMMAND: [142912347187] SCHEDULE_SVC_DOWNTIME;localhost;Check Memory Usage;142345340;142345540;1;0;0;tarak;sdsad

Can any one help me to fix this issue

Thanks in advance.

**Comment by t0xicCode** [comment]
We switched to the bs3 branch, which doesn't have gestures.

**Comment by mohierf** [comment]
In BS3 branch you can activate gesture with a simple parameter (tab_gesture=yes
) in the file *eltdetail/plugin.cfg* file ...

I am not quite sure that this feature is fully operationnal because I never use ... and I intend to remove from the WebUI.

**Comment by hvad** [comment]
Hi,

i use webui since 2 years and i never use gesture. i think it's not
necessary.

Good job on BS3.

Best regard

2015-05-02 1:49 GMT+02:00 Frédéric MOHIER <notifications@github.com>:

> In BS3 branch you can activate gesture with a simple parameter
> (tab_gesture=yes
> ) in the file *eltdetail/plugin.cfg* file ...
>
> I am not quite sure that this feature is fully operationnal because I
> never use ... and I intend to remove from the WebUI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shinken-monitoring/mod-webui/issues/84#issuecomment-98262331>
> .
>



-- 
David Hannequin

**Comment by mohierf** [comment]
Thanks !

**Comment by naparuba** [comment]
gestures did work on the past, but it was more a joke than a real feature
to use ^^

**Comment by t0xicCode** [comment]
At this point I wouldn't mind removing them

**Comment by mohierf** [comment]
Closing ... future release does include this feature.
