### ISSUE TITLE
change "print" to "logger.info"

### ISSUE THREAD

**Issue by andyxning** [shinken-monitoring/mod-webui#90]
the `print` clause in the `get_instance` function should be replaced as `logger.info` since the process runs in a damon env, any `print` can get nothing. Thus `logger.info` should be used.

**Comment by t0xicCode** [comment]
@david-guenault any update?

**Comment by david-guenault** [comment]
not at the moment, working on multiple projects (shinken, docker, kunai .... ) with so little time. Gona check this out this monday

**Comment by mohierf** [comment]
@andyxning : BS3 has improved the logging in WebUI ... many prints were removed and replaced. Your feedback about it is interesting ... do not hesitate to request for more logs if you need.
